insert into Items (Name, Code, Active, CreateDate) values
('1911 silver', '1911', 1, date('now')),
('Grenade 40 Mm', '40mm_G', 1, date('now')),
('Shotgun Ammunition Box closed', '12_Gauge_Ammobox_Closed', 1, date('now')),
('Shotgun Shell - Empty', '12_Gauge_Catrige', 1, date('now')),
('Shotgun Ammunition Box open', '12_Gauge_Ammobox_Open1', 1, date('now')),
('12 Gauge Shell', '12_Gauge', 1, date('now')),
('Pitchfork', '2H_Pitchfork', 1, date('now')),
('Shovel', '2H_Shovel_02', 1, date('now')),
('Pickaxe', '2H_Pickaxe', 1, date('now')),
('Katana', '2H_Katana', 1, date('now')),
('Baseball Bat with spikes', '2H_Baseball_Bat_with_spikes', 1, date('now')),
('Baseball Bat with wire', '2H_Baseball_Bat_with_wire', 1, date('now')),
('Stone Axe', '2H_Stone_Axe', 1, date('now')),
('Pitchfork Bent', '2H_Pitchfork_Bent', 1, date('now')),
('Baseball Bat', '2H_Baseball_Bat', 1, date('now')),
('Improvised shovel', '2H_Improvised_shovel', 1, date('now')),
('Metal Baseball Bat', '2H_Metal_Baseball_Bat', 1, date('now')),
('Wooden Sword', '2H_Wooden_Sword', 1, date('now')),
('Stone Axe Head', '2H_Stone_Axe_Head', 1, date('now')),
('Metal Axe', '2H_Metal_Axe', 1, date('now')),
('Spade Shovel', '2H_Shovel_01', 1, date('now')),
('Ax', '2H_Axe', 1, date('now')),
('Hunter', '1H_Hunter', 1, date('now')),
('Stone Axe Head', '1H_Stone_Axe_Head', 1, date('now')),
('Improvised Hammer', '1H_Improvised_Hammer', 1, date('now')),
('Kitchen Knife', '1H_KitchenKnife', 1, date('now')),
('N9 Bayonet', '1H_N9_White', 1, date('now')),
('Cleaver', '1H_Cleaver', 1, date('now')),
('Stone Axe', '1H_Stone_Axe', 1, date('now')),
('Kitchen Knife', '1H_KitchenKnife_04', 1, date('now')),
('Crowbar', '1H_Crowbar', 1, date('now')),
('Metal Knife', '1H_Improvised_metal_knife', 1, date('now')),
('Kunai', '1H_Kunai', 1, date('now')),
('MK5000 black', '1H_MK5000_Black', 1, date('now')),
('Bushman', '1H_Bushman', 1, date('now')),
('Improvised Hatchet', '1H_Hatchet', 1, date('now')),
('Police Baton', '1H_Police_Baton', 1, date('now')),
('Mk5000', '1H_MK5000_Metal', 1, date('now')),
('Brass Knuckles', '1H_Brass_knuckles', 1, date('now')),
('Scout White', '1H_Scout_White', 1, date('now')),
('Metal Sword', '1H_Metal_Sword', 1, date('now')),
('Shuriken', '1H_Shuriken', 1, date('now')),
('Stone Knife', '1H_ImprovisedKnife', 1, date('now')),
('Wooden club', '1H_Wooden_club', 1, date('now')),
('Wrench Pipe', '1H_Wrench_Pipe', 1, date('now')),
('N9 Bayonet', '1H_N9_Black_1h_Melee', 1, date('now')),
('Small Spade', '1H_Little_Spade', 1, date('now')),
('Scout Black', '1H_Scout_Black', 1, date('now')),
('N9 Bayonet', '1H_N9_Black', 1, date('now')),
('Kitchen Knife', '1H_KitchenKnife_03', 1, date('now')),
('Scalpel', '1H_Scalpel', 1, date('now')),
('Kitchen Knife', '1H_KitchenKnife_02', 1, date('now')),
('Wooden club with spikes', '1H_Wooden_club_with_spikes', 1, date('now')),
('Wooden club with wire', '1H_Wooden_club_with_wire', 1, date('now')),
('Small Meat Skewer', 'Skewer_Meat_small', 1, date('now')),
('Chop_Horse_Skinned', 'Chop_Horse_Skinned', 1, date('now')),
('Cabbage', 'Cabbage', 1, date('now')),
('Zombie_Jeans_01_02', 'Zombie_Jeans_01_02', 1, date('now')),
('Magazine_DEagle_50', 'Magazine_DEagle_50', 1, date('now')),
('Coconut', 'Coconut', 1, date('now')),
('Chop_Debree_Log_Big', 'Chop_Debree_Log_Big', 1, date('now')),
('Smoke_Dry_food', 'Smoke_Dry_food', 1, date('now')),
('Human Arm', 'Prisoner_Right_Arm', 1, date('now')),
('Fish Trap', 'Fish_trap', 1, date('now')),
('Cartridge Sleeve 7.62 × 39 Mm', 'Cal7_62x39mm_Empty', 1, date('now')),
('Pie', 'Pate_02', 1, date('now')),
('Chop_Tree_03', 'Chop_Tree_03', 1, date('now')),
('Zombie_01_Right_Leg', 'Zombie_01_Right_Leg', 1, date('now')),
('Ammunition Box .45 Acp', 'Cal45_AmmoboxOpen', 1, date('now')),
('Vegetable Oil', 'VegetableOil', 1, date('now')),
('antipsychotic Pils', 'antipsychotic_Pils', 1, date('now')),
('Salted Fish', 'Salted_fish_01', 1, date('now')),
('Ak-74 (aks)', 'AK-74', 1, date('now')),
('Chop_Wolf', 'Chop_Wolf', 1, date('now')),
('Spoon', 'Spoon', 1, date('now')),
('Stones', 'SearchForRocks', 1, date('now')),
('Caramel Shower', 'PETBottle02', 1, date('now')),
('Chop_Tinder_LWS', 'Chop_Tinder_LWS', 1, date('now')),
('Grapefruit', 'GrapeFruit', 1, date('now')),
('Donkey Hull', 'Donkey_Torso', 1, date('now')),
('Cartridge 9 Mm', 'Cal_9mm_5_Bullets', 1, date('now')),
('Holzgabel', 'Wooden_Fork', 1, date('now')),
('Chop_Chicken_Torso', 'Chop_Chicken_Torso', 1, date('now')),
('Onion Rings', 'Chips3', 1, date('now')),
('Car Battery Cable', 'Car_Battery_Cables', 1, date('now')),
('Slice_Clothes_01', 'Slice_Clothes_01', 1, date('now')),
('Pantherpilz', 'Amanita_Pantheria', 1, date('now')),
('Weapon_98k_Karabiner', 'Weapon_98k_Karabiner', 1, date('now')),
('Pigeon Breasts', 'Pigeon_Breasts', 1, date('now')),
('Chop_Crow', 'Chop_Crow', 1, date('now')),
('Chocolate Toaster Pastries', 'Toaster_Pastries2', 1, date('now')),
('Scrap Metal', 'Metal_Scrap_03', 1, date('now')),
('Jersey Shirt', 'Zombie_Jersey_02', 1, date('now')),
('Cooked Vegetables', 'CookVegetables2', 1, date('now')),
('Bubbles', 'Can03', 1, date('now')),
('Grapefruit Juice', 'GlassBottle02', 1, date('now')),
('Chop_Destroy_Improvised_Metal_Chest', 'Chop_Destroy_Improvised_Metal_Chest', 1, date('now')),
('Pine Cones', 'Pine_Cone', 1, date('now')),
('Veal Steak', 'Veal_Steak', 1, date('now')),
('Animal Skin', 'Animal_skin', 1, date('now')),
('Army Glasses', 'Military_Goggles', 1, date('now')),
('Night_Vision', 'Night_Vision', 1, date('now')),
('Chillies', 'Chilipeper', 1, date('now')),
('Electrician`s Tool', 'Electrician_Tools', 1, date('now')),
('Bait Trap For Small Animals', 'Bait_trap_for_small_animals', 1, date('now')),
('Zombie_Work_Jacket_02', 'Zombie_Work_Jacket_02', 1, date('now')),
('Animal Fat', 'Small_Animal_Fat', 1, date('now')),
('9mm Ammunition Box', 'Cal_9mm_AmmoboxOpen', 1, date('now')),
('Spitfire Jacket', 'Zombie_College_Jacket_05', 1, date('now')),
('Skewer_Sausages_small', 'Skewer_Sausages_small', 1, date('now')),
('Sledgehammer', 'Sledgehammer', 1, date('now')),
('Burger Bun', 'Burger_PATTIES', 1, date('now')),
('Ak47_Strap_For_Holster', 'Ak47_Strap_For_Holster', 1, date('now')),
('Celery', 'Celery', 1, date('now')),
('Chop_Swan', 'Chop_Swan', 1, date('now')),
('Chop_Destroy', 'Chop_Destroy', 1, date('now')),
('Wolf Leg', 'Wolf_Left_Back_Leg', 1, date('now')),
('Skewer', 'Skewer_Meat', 1, date('now')),
('Zombie_Raincoat_Up_04', 'Zombie_Raincoat_Up_04', 1, date('now')),
('Chop_Tree_02', 'Chop_Tree_02', 1, date('now')),
('Chocolate', 'ChocolateCandy_07', 1, date('now')),
('1 M Wire', 'Wire', 1, date('now')),
('Rehbein', 'Doe_Right_Back_Leg', 1, date('now')),
('Torch', 'Torch', 1, date('now')),
('Flannel Shirt', 'Zombie_Woodcutter_Shirt_01', 1, date('now')),
('Cake', 'Cake', 1, date('now')),
('Baseball Cap', 'Zombie_Baseball_Cap_12', 1, date('now')),
('Soldiers-shirt', 'Zombie_Military_Shirt_02', 1, date('now')),
('Blueberries', 'Blueberries', 1, date('now')),
('Cannon Ammunition Container', 'Cal20mm_Empty', 1, date('now')),
('Chop_Human_Limb', 'Chop_Human_Limb', 1, date('now')),
('Zombie_Shirt_03', 'Zombie_Shirt_03', 1, date('now')),
('Cheese', 'Cheese', 1, date('now')),
('Branches Of A Shrub', 'Bush_Branches', 1, date('now')),
('Fried Egg', 'Fried_Egg_01', 1, date('now')),
('Weapon_Hunter85', 'Weapon_Hunter85', 1, date('now')),
('Soup', 'Soup_02', 1, date('now')),
('Canned Corn', 'Canned_Corn', 1, date('now')),
('UI_ClockFaceWidget', 'UI_ClockFaceWidget', 1, date('now')),
('Currant', 'Currant', 1, date('now')),
('Fishing Rod', 'Fishing_rod', 1, date('now')),
('Cal_357_1pcs', 'Cal_357_1pcs', 1, date('now')),
('Cigarettes "lucky Star"', 'Cigarettes1', 1, date('now')),
('Cat Food', 'CannedCatfood', 1, date('now')),
('Canned Tuna', 'Canned_Tuna', 1, date('now')),
('Spring', 'Spring', 1, date('now')),
('Wild Cherry', 'Wild_Cherry', 1, date('now')),
('Improvised Compass', 'Improvised_compass', 1, date('now')),
('Human Hull', 'Prisoner_Torso', 1, date('now')),
('Carrot Juice', 'GlassBottle01', 1, date('now')),
('Right Rabbit Fore-piece', 'Rabbit_Right_Front', 1, date('now')),
('Dietrich', 'Lockpick', 1, date('now')),
('Bundle Of Rags', 'Bundle_Of_Rags', 1, date('now')),
('Matches', 'Matches', 1, date('now')),
('Ammunition Box 7.92 X 57 Mm', 'Cal_7_92x57mm_AmmoboxOpen', 1, date('now')),
('Flames Defense Shield', 'Fire_deflector_shield', 1, date('now')),
('Barberry', 'Barberry', 1, date('now')),
('Oysters', 'Oysters', 1, date('now')),
('Scissors', 'Scissors_01', 1, date('now')),
('Barrel With Salted Mutton', 'Salted_meat_barrel_01', 1, date('now')),
('Spaghetti Bolognese', 'Spaghetti_Bolognese', 1, date('now')),
('Wild Steak', 'Deer_Steak', 1, date('now')),
('Half Bear Hull', 'Bear_Left_Torso_Half', 1, date('now')),
('Chop_Goat', 'Chop_Goat', 1, date('now')),
('Chop_Horse_Torso_Half', 'Chop_Horse_Torso_Half', 1, date('now')),
('Cricket', 'Cricket', 1, date('now')),
('Piece Of Rubber', 'Rubber_sheet', 1, date('now')),
('Parachute', 'Parachute', 1, date('now')),
('Black Pepper', 'BlackPepper', 1, date('now')),
('Chop_Doe_Skinned', 'Chop_Doe_Skinned', 1, date('now')),
('Absinthe "father"', 'Absinthe', 1, date('now')),
('Ammunition Box 5.45 × 39 Mm', 'Cal_5_45x39_AmmoboxClosed', 1, date('now')),
('Baked Meat', 'Baked_meat', 1, date('now')),
('Pilot Jacket', 'Zombie_MA1_Spitfire_02', 1, date('now')),
('Logs', 'Wooden_Log_Small_01', 1, date('now')),
('Firesteel', 'Flint_And_Steel', 1, date('now')),
('Lens', 'Camera_Lens', 1, date('now')),
('Scorzonera Hispanica', 'Salsify_roots', 1, date('now')),
('BPC_BerettaM9', 'BPC_BerettaM9', 1, date('now')),
('Cartridge Caliber .22', 'Cal22_Bullet', 1, date('now')),
('Mp5 Magazine', 'Magazine_MP5', 1, date('now')),
('Wolf Hull', 'Wolf_Torso', 1, date('now')),
('Chop_Chicken', 'Chop_Chicken', 1, date('now')),
('Popcorn', 'Popcorn_01', 1, date('now')),
('Bear Paws', 'Bear_Back_Paws', 1, date('now')),
('Cartridge .50 Bwg', 'Cal50', 1, date('now')),
('Rose Hip', 'Dog_Rose', 1, date('now')),
('Small Bunch Of Wooden Sticks', 'Wooden_Sticks_Bundle_Meduim', 1, date('now')),
('Pizza', 'Pizza', 1, date('now')),
('Joints Of Meat', 'Bird_Legs_Medium', 1, date('now')),
('Bear Paws', 'Bear_Front_Paws', 1, date('now')),
('Chop_Donkey_Limb_Back', 'Chop_Donkey_Limb_Back', 1, date('now')),
('Chop_Rabbit_lIMB', 'Chop_Rabbit_lIMB', 1, date('now')),
('Hirsch Hull', 'Buck_Torso', 1, date('now')),
('Chop_Wolf_Limbs', 'Chop_Wolf_Limbs', 1, date('now')),
('BPC_Deagle_357', 'BPC_Deagle_357', 1, date('now')),
('Event_2H_Baseball_Bat_with_wire', 'Event_2H_Baseball_Bat_with_wire', 1, date('now')),
('Zombie_01_Torso', 'Zombie_01_Torso', 1, date('now')),
('Agaricus Campestris', 'Agaricus_Campestris', 1, date('now')),
('Chop_Boar', 'Chop_Boar', 1, date('now')),
('Zombie_Driving_Gloves_04', 'Zombie_Driving_Gloves_04', 1, date('now')),
('Gimlet', 'Hand_Drill', 1, date('now')),
('Chop_Car_Cables', 'Chop_Car_Cables', 1, date('now')),
('Nails', 'Nails', 1, date('now')),
('Smartphone Battery', 'Smartphone_Battery', 1, date('now')),
('Cal_50_AE_5pcs', 'Cal_50_AE_5pcs', 1, date('now')),
('Rags', 'Rag_Stripes', 1, date('now')),
('Scrap Metal', 'Metal_Scrap_04', 1, date('now')),
('Glass', 'Jar', 1, date('now')),
('Chop_Tinder_SWS', 'Chop_Tinder_SWS', 1, date('now')),
('Zombie_Jock_Jacket_03', 'Zombie_Jock_Jacket_03', 1, date('now')),
('Cartridge 7.92 X 57 Mm', 'Cal_7_92x57mm_5_bullets', 1, date('now')),
('Hacksaw', 'Saw', 1, date('now')),
('Chop_Human', 'Chop_Human', 1, date('now')),
('Crab Claw', 'Crab_Right_Pincer', 1, date('now')),
('Salted Potato Chips', 'Chips4', 1, date('now')),
('Cream', 'Cream', 1, date('now')),
('Beetroot', 'Beet', 1, date('now')),
('Agaricus Augustus', 'Agaricus_Augustus', 1, date('now')),
('Fork', 'Steel_Fork', 1, date('now')),
('Pork Steak', 'Pork_Steak', 1, date('now')),
('Smoked Rodent Meat', 'Smoked_RodentMeat', 1, date('now')),
('Horse`s Rump', 'Horse_Torso', 1, date('now')),
('Slice_Clothes_05', 'Slice_Clothes_05', 1, date('now')),
('Soda', 'Can01', 1, date('now')),
('Cooking Pot', 'Pot1', 1, date('now')),
('Vitamin Tablets (glass)', 'Vitamins_03', 1, date('now')),
('Beanie', 'Zombie_Beenie_02', 1, date('now')),
('Wolf Leg', 'Wolf_Right_Back_Leg', 1, date('now')),
('Event Improvised Metal Spear', 'Event_Improvised_Metal_Spear', 1, date('now')),
('Ziegenkopf', 'Goat_Head', 1, date('now')),
('Slice_Rags_Into_Stripes', 'Slice_Rags_Into_Stripes', 1, date('now')),
('Bundle_Rag_Stripes', 'Bundle_Rag_Stripes', 1, date('now')),
('Souse', 'Salted_meat_02', 1, date('now')),
('Chop_Swan_Skinned', 'Chop_Swan_Skinned', 1, date('now')),
('5 M Rope', 'Rope1', 1, date('now')),
('SeaSalt_02', 'SeaSalt_02', 1, date('now')),
('Banana', 'Banana', 1, date('now')),
('Rabbit Meat', 'RabbitMeat', 1, date('now')),
('Take_Page_out_of_diary', 'Take_Page_out_of_diary', 1, date('now')),
('Slice_Zombie_Clothes_03', 'Slice_Zombie_Clothes_03', 1, date('now')),
('Magazine_DEagle_357', 'Magazine_DEagle_357', 1, date('now')),
('Bark Rope', 'Improvised_Plant_rope', 1, date('now')),
('Candle', 'Candle_01', 1, date('now')),
('Batteries', 'Batteries', 1, date('now')),
('Joints Of Meat', 'Bird_Legs_Large', 1, date('now')),
('Cal30-06_Ammobox_Open', 'Cal30-06_Ammobox_Open', 1, date('now')),
('Prisoners Shirt', 'Zombie_Inmate_shirt', 1, date('now')),
('Cartridge Caliber .22', 'Cal22_Pile_5pcs', 1, date('now')),
('People Sausage', 'Human_Sausages_01', 1, date('now')),
('Smoked Dog Steak', 'Smoked_Dog_Steak', 1, date('now')),
('Cal7_62x39mm_20_bullets', 'Cal7_62x39mm_20_bullets', 1, date('now')),
('Chop_Seagull_Skinned', 'Chop_Seagull_Skinned', 1, date('now')),
('Donkey Leg', 'Donkey_Front_Leg', 1, date('now')),
('Chop_Bush_03', 'Chop_Bush_03', 1, date('now')),
('College Jacket', 'Zombie_Jock_Jacket_01', 1, date('now')),
('Peach', 'Peach', 1, date('now')),
('Apple', 'Apple', 1, date('now')),
('Green Peas', 'CannedPeas', 1, date('now')),
('Salted Fish', 'Salted_fish_02', 1, date('now')),
('Plastic Scissors', 'Scissors_Plastic', 1, date('now')),
('NightVisionGoggles3_test', 'NightVisionGoggles3_test', 1, date('now')),
('Hippie_Pants_02_04', 'Hippie_Pants_02_04', 1, date('now')),
('Camouflage Jacket', 'Camouflage_Jacket_01', 1, date('now')),
('Combat Boots', 'CombatBoots', 1, date('now')),
('Cotton Hoodie', 'Hoodie_01', 1, date('now')),
('Cotton Shirt', 'Shirt_01', 1, date('now')),
('Croatia Jersey', 'Jersey_03', 1, date('now')),
('Auto Gloves', 'Driving_Gloves_01', 1, date('now')),
('Angler', 'Boonie_Hat_01', 1, date('now')),
('Flannel Shirt', 'Woodcutter_Shirt_01', 1, date('now')),
('High-tops', 'Sneakers_02_01', 1, date('now')),
('Hiking Backpack', 'Hiking_Backpack_01', 1, date('now')),
('Walking Boots', 'Hiking_Boots_01', 1, date('now')),
('Hippy Pants', 'Hippie_pants_01_01', 1, date('now')),
('Bush Hat', 'Boonie_Hat_03', 1, date('now')),
('Hippie-shirt', 'Hippie_Shirt_01', 1, date('now')),
('Improvised Backpack', 'Improvised_Backpack_Big', 1, date('now')),
('Improvised Boots', 'Improvised_Shoes_01', 1, date('now')),
('Improvised Courier Backpack', 'Improvised_Bag_Small_01', 1, date('now')),
('Santa_Pants', 'Santa_Pants', 1, date('now')),
('Prisoners Pants', 'Inmate_pants', 1, date('now')),
('Prisoners Shirt', 'Inmate_shirt', 1, date('now')),
('Jeans', 'Jeans_01_01', 1, date('now')),
('Jersey Shirt', 'Jersey_01', 1, date('now')),
('College Jacket', 'Jock_Jacket_01', 1, date('now')),
('Kroks', 'Slippers_01', 1, date('now')),
('Leather Backpack', 'Small_Leather_Backpack_01', 1, date('now')),
('Tarnfleck Hiking Backpack', 'Camo_Backpack_01', 1, date('now')),
('Bee Pollen Pills', 'BeePollen_Pils_01', 1, date('now')),
('Leather Shoes', 'Leather_Shoes', 1, date('now')),
('Animal Skin Jacket', 'Bear_Improvised_Jacket', 1, date('now')),
('DEagle_50Gold', 'DEagle_50Gold', 1, date('now')),
('Ak47 Magazine', 'Magazine_AK47', 1, date('now')),
('Chop_Goat_Limb_Front', 'Chop_Goat_Limb_Front', 1, date('now')),
('Zombie_Jeans_01_03', 'Zombie_Jeans_01_03', 1, date('now')),
('Slice_Zombie_Clothes_04', 'Slice_Zombie_Clothes_04', 1, date('now')),
('Chop_Bush_01', 'Chop_Bush_01', 1, date('now')),
('Chop_Destroy_Wooden_Chest', 'Chop_Destroy_Wooden_Chest', 1, date('now')),
('Bear Leg', 'Bear_Right_Front_Leg', 1, date('now')),
('MeatSnack_02', 'MeatSnack_02', 1, date('now')),
('Bear Leg', 'Bear_Right_Back_Leg', 1, date('now')),
('Wurfpieß', 'Javelin', 1, date('now')),
('Activated Carbon', 'ActivatedCharcoal_01', 1, date('now')),
('Animal Skin Pants', 'Bear_Improvised_Pants', 1, date('now')),
('Bear Boots', 'Bear_Shoe', 1, date('now')),
('Anti-radiation Pills', 'Anti_Radiation_Pils_01', 1, date('now')),
('Antibiotics', 'Antibiotics_01', 1, date('now')),
('Anti-malarial Pills', 'AntiMalariaPils_01', 1, date('now')),
('Antiparasitic', 'Antiparasitics_01', 1, date('now')),
('Assault Backpack', 'Backpack_01_01', 1, date('now')),
('Backpack', 'Backpack_02_01', 1, date('now')),
('Balaclava', 'Beenie_3_hole_01', 1, date('now')),
('Baseball Cap', 'Baseball_Cap_01', 1, date('now')),
('Santa_Hat', 'Santa_Hat', 1, date('now')),
('Beanie', 'Beenie_01', 1, date('now')),
('Bear Gloves', 'Bear_Pow', 1, date('now')),
('Bear Head Cap', 'Bear_Head_Cap', 1, date('now')),
('Leather Jacket', 'Jacket_01', 1, date('now')),
('Marine Cap', 'Marine_Cap_01', 1, date('now')),
('Horse`s Leg', 'Horse_Back_Limb', 1, date('now')),
('Sniper', 'SnipingSkill', 1, date('now')),
('Rags Footwear', 'Improvised_Shoe_02', 1, date('now')),
('Slicker', 'Raincoat_Down_01', 1, date('now')),
('Respirator', 'Respirator_01', 1, date('now')),
('Rifles', 'RiflesSkill', 1, date('now')),
('Helmet Use', 'Fireman_Helmet_01', 1, date('now')),
('Improvised_Stabproof', 'Improvised_Stabproof', 1, date('now')),
('Einsatzweste', 'Stabproof_Vest_05', 1, date('now')),
('Satchel', 'School_Backpack_boy_01', 1, date('now')),
('Shirt', 'Military_Shirt_06', 1, date('now')),
('Shorts', 'Shorts_Pants_01', 1, date('now')),
('Small Improvised Backpack', 'Improvised_Bag_Small_02', 1, date('now')),
('Spitfire Jacket', 'College_Jacket_01', 1, date('now')),
('Quinine Sulfate Tablets', 'QuinineSulphate_Pils_01', 1, date('now')),
('Training Pants', 'Tracksuit_Pants_01_01', 1, date('now')),
('Tactical Gloves', 'Tactical_Gloves_01', 1, date('now')),
('Santa_Jacket', 'Santa_Jacket', 1, date('now')),
('Tactical Jacket', 'Tactical_Jacket_01', 1, date('now')),
('Tactical Army Pants', 'MilitaryPants_02', 1, date('now')),
('Tactical Sweater', 'Tactical_Sweater_01', 1, date('now')),
('Training Jacket', 'Tracksuit_Top_01_01', 1, date('now')),
('Sneakers', 'HighTop_Shoes', 1, date('now')),
('Trucker Jacket', 'Trucker_Jacket_01', 1, date('now')),
('Hüfttasche', 'Waist_Bag_Small_01', 1, date('now')),
('Wool Sweater', 'Sweater_01', 1, date('now')),
('Work Jacket', 'Work_Jacket_01', 1, date('now')),
('Rags Footwear', 'Zombie_Improvised_Shoe_02', 1, date('now')),
('Potassium Iodide Pills', 'PotassiumIodide_Pils_01', 1, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_01', 1, date('now')),
('Night_Vision_Helmet_Down_08', 'Night_Vision_Helmet_Down_08', 1, date('now')),
('MilitaryBoots JNA', 'MilitaryBoots_JNA', 1, date('now')),
('Night_Vision_Googles', 'Night_Vision_Googles', 1, date('now')),
('Soldier`s Cap', 'Military_Cap_01', 1, date('now')),
('Night_Vision_Helmet_Up_06', 'Night_Vision_Helmet_Up_06', 1, date('now')),
('Night_Vision_Helmet_Up_03', 'Night_Vision_Helmet_Up_03', 1, date('now')),
('Night_Vision_Helmet_Up_08', 'Night_Vision_Helmet_Up_08', 1, date('now')),
('Night_Vision_Helmet_Down_05', 'Night_Vision_Helmet_Down_05', 1, date('now')),
('Night_Vision_Helmet_Up_02', 'Night_Vision_Helmet_Up_02', 1, date('now')),
('Night_Vision_Helmet_Down_06', 'Night_Vision_Helmet_Down_06', 1, date('now')),
('Night_Vision_Helmet_Up_05', 'Night_Vision_Helmet_Up_05', 1, date('now')),
('Night_Vision_Helmet_Down_09', 'Night_Vision_Helmet_Down_09', 1, date('now')),
('Night_Vision_Helmet_Down_04', 'Night_Vision_Helmet_Down_04', 1, date('now')),
('Night_Vision_Helmet_Up_07', 'Night_Vision_Helmet_Up_07', 1, date('now')),
('Police Body Armor', 'Stabproof_Vest_01', 1, date('now')),
('Night_Vision_Helmet_Up_04', 'Night_Vision_Helmet_Up_04', 1, date('now')),
('Night_Vision_Helmet_Up_01', 'Night_Vision_Helmet_Up_01', 1, date('now')),
('Night_Vision_Helmet_Up_09', 'Night_Vision_Helmet_Up_09', 1, date('now')),
('Night_Vision_Helmet_Down_07', 'Night_Vision_Helmet_Down_07', 1, date('now')),
('Night_Vision_Helmet_Down_02', 'Night_Vision_Helmet_Down_02', 1, date('now')),
('Night_Vision_Helmet_Down_01', 'Night_Vision_Helmet_Down_01', 1, date('now')),
('Night_Vision_Helmet_Down_03', 'Night_Vision_Helmet_Down_03', 1, date('now')),
('Soldier Helmet', 'Military_Helmet_01', 1, date('now')),
('Soldiers-shirt', 'Military_Shirt_01', 1, date('now')),
('Mma Gloves', 'MMA_Glove', 1, date('now')),
('Fingerless Gloves', 'Open_Finger_Gloves_01', 1, date('now')),
('Painkillers', 'Painkillers_01', 1, date('now')),
('Watermelon Slice', 'Watermelon_slice', 1, date('now')),
('Kitchen Board', 'Kitchen_Board_01', 1, date('now')),
('Chop_Bush_02', 'Chop_Bush_02', 1, date('now')),
('Razor_Blade', 'Razor_Blade', 1, date('now')),
('Chop_Pigeon', 'Chop_Pigeon', 1, date('now')),
('Smoked Bird Meat', 'Smoked_BirdMeat', 1, date('now')),
('Slice_Clothes_03', 'Slice_Clothes_03', 1, date('now')),
('Chop_Boar_Skinned', 'Chop_Boar_Skinned', 1, date('now')),
('Cereal UpNGo', 'Cereal_UpNGo', 1, date('now')),
('Zombie_Police_Cap_01', 'Zombie_Police_Cap_01', 1, date('now')),
('Chop_Rat_Torso', 'Chop_Rat_Torso', 1, date('now')),
('Zombie_Baseball_Cap_18', 'Zombie_Baseball_Cap_18', 1, date('now')),
('Ammunition Box Caliber .22', 'Cal22_Ammobox_Closed', 1, date('now')),
('Zombie_01_Right_Arm', 'Zombie_01_Right_Arm', 1, date('now')),
('Riot_Helmet2', 'Riot_Helmet2', 1, date('now')),
('Cartridge 7.92 X 57 Mm', 'Cal_7_92x57mm_Bullet', 1, date('now')),
('Pie', 'Pate_01', 1, date('now')),
('Helmet Use', 'Riot_Helmet', 1, date('now')),
('Egg', 'Egg', 1, date('now')),
('Mango', 'Mango', 1, date('now')),
('Chop_Log_Big', 'Chop_Log_Big', 1, date('now')),
('Sodium Hydroxide', 'Sodium_Hydroxide', 1, date('now')),
('Frag Grenade', 'Frag_Grenade', 1, date('now')),
('Skinned Deer', 'Doe_Skinned', 1, date('now')),
('Chop_Rabbit', 'Chop_Rabbit', 1, date('now')),
('Chop_Destroy_Improved_Wooden_Chest', 'Chop_Destroy_Improved_Wooden_Chest', 1, date('now')),
('Zombie_01_Right_Foot', 'Zombie_01_Right_Foot', 1, date('now')),
('Chop_Horse_Torso', 'Chop_Horse_Torso', 1, date('now')),
('Cartridge 7.62 × 54 Mm R', 'Cal7_62x54mmR_5_bullets', 1, date('now')),
('Ammunition Box 7.92 X 57 Mm', 'Cal_7_92x57mm_AmmoboxClosed', 1, date('now')),
('Chop_Zombie_Limb', 'Chop_Zombie_Limb', 1, date('now')),
('Steak With Potatoes', 'Steak_With_Potatoes_02', 1, date('now')),
('Half Horse Swamp', 'Horse_Torso_Half', 1, date('now')),
('Marine Cap', 'Zombie_Marine_Cap_01', 1, date('now')),
('Tactical Army Pants', 'Zombie_MilitaryPants_02', 1, date('now')),
('Rehbein', 'Doe_Left_Back_Leg', 1, date('now')),
('Smoked Goose Meat', 'Smoked_GooseMeat', 1, date('now')),
('Prisoners Pants', 'Zombie_Inmate_pants', 1, date('now')),
('Orange Juice', 'Can02', 1, date('now')),
('Tin', 'CannedFood2', 1, date('now')),
('Bear Hull', 'Bear_Torso', 1, date('now')),
('Chop_Debree_Log_Big_02', 'Chop_Debree_Log_Big_02', 1, date('now')),
('Wolf Leg', 'Wolf_Right_Front_Leg', 1, date('now')),
('Right Rabbit Spine Piece', 'Rabbit_Right_Back', 1, date('now')),
('Boar Leg', 'Boar_Back_Leg', 1, date('now')),
('Bean Stew', 'Beans_Stew_01', 1, date('now')),
('Bark', 'Tree_Bark', 1, date('now')),
('Bone Needle', 'Bone_Needle', 1, date('now')),
('Chop_Donkey_Skinned', 'Chop_Donkey_Skinned', 1, date('now')),
('Toadstool', 'Amanita_Muscaria', 1, date('now')),
('Fingerless Gloves', 'Zombie_Open_Finger_Gloves_01', 1, date('now')),
('0_Empty', '0_Empty', 1, date('now')),
('Slice_Clothes_04', 'Slice_Clothes_04', 1, date('now')),
('Wolf Steak', 'Wolf_Steak', 1, date('now')),
('Stew', 'Stew1', 1, date('now')),
('Olive', 'Olives', 1, date('now')),
('Human Foot', 'Prisoner_Left_Foot', 1, date('now')),
('Mp5', 'Weapon_MP5', 1, date('now')),
('Deagle 50', 'Deagle_50', 1, date('now')),
('Plucked Chicken', 'Hen_Torso', 1, date('now')),
('Hot Nachos', 'Chips2', 1, date('now')),
('Chop_Long_Wooden_Stick', 'Chop_Long_Wooden_Stick', 1, date('now')),
('Marine Cap', 'Zombie_Marine_Cap_06', 1, date('now')),
('Horse Steak', 'Horse_Steak', 1, date('now')),
('Donkey Leg', 'Donkey_Back_Leg', 1, date('now')),
('Butter', 'Butter', 1, date('now')),
('Crab Hull', 'Crab_Torso', 1, date('now')),
('Ring Of Fire', 'Fireplace1', 1, date('now')),
('Improved_Wooden_Chest', 'Improved_Wooden_Chest', 1, date('now')),
('Bag of Almonds', 'Bag_of_Almonds', 1, date('now')),
('Zombie_MA1_Spitfire_04', 'Zombie_MA1_Spitfire_04', 1, date('now')),
('Pelinkovac', 'Pelinkovac', 1, date('now')),
('Rehrumpf', 'Doe_Torso', 1, date('now')),
('Bone', 'Bone', 1, date('now')),
('Deer Head', 'Buck_Head', 1, date('now')),
('Cooked Vegetables', 'BakeVegetables2', 1, date('now')),
('Chop_Deer_Torso', 'Chop_Deer_Torso', 1, date('now')),
('Chop_Rabbit_Skinned', 'Chop_Rabbit_Skinned', 1, date('now')),
('Skinned Horse', 'Horse_Skinned', 1, date('now')),
('Crab Claw', 'Crab_Left_Pincer', 1, date('now')),
('Cartridge 7.92 X 57 Mm', 'Cal_7_92x57mm', 1, date('now')),
('Chocolate Bar', 'ChocolateCandy_01', 1, date('now')),
('Zombie_01_Left_Leg', 'Zombie_01_Left_Leg', 1, date('now')),
('Chop_Bear_Limbs', 'Chop_Bear_Limbs', 1, date('now')),
('Make_Rag_Stripes', 'Make_Rag_Stripes', 1, date('now')),
('Cal_5_45x39_5_pcs', 'Cal_5_45x39_5_pcs', 1, date('now')),
('Cal30-06', 'Cal30-06', 1, date('now')),
('Chop_Pigeon_Skinned', 'Chop_Pigeon_Skinned', 1, date('now')),
('Souse', 'Salted_meat_01', 1, date('now')),
('Sunflower Seeds', 'Sunflower_Seeds', 1, date('now')),
('Chop_Bear_Torso', 'Chop_Bear_Torso', 1, date('now')),
('Chop_Bear_Torso_Half', 'Chop_Bear_Torso_Half', 1, date('now')),
('Barrel', 'Barrel', 1, date('now')),
('Wool Sweater', 'Zombie_Sweater_03', 1, date('now')),
('Smoker', 'Smoker_02', 1, date('now')),
('Glasses', 'Geek_Goggels', 1, date('now')),
('Chop_Goat_Torso', 'Chop_Goat_Torso', 1, date('now')),
('Tipi', 'Tepee', 1, date('now')),
('Boar Leg', 'Boar_Front_Leg', 1, date('now')),
('Toolbox', 'Tool_Box', 1, date('now')),
('Vitamin Tablets (blister)', 'Vitamins_01', 1, date('now')),
('Ammunition Box 7,62 × 54 Mm R', 'Cal7_62x54mmR_Ammobox_Closed', 1, date('now')),
('Chop_Bear', 'Chop_Bear', 1, date('now')),
('Bear Steak', 'Bear_Steak', 1, date('now')),
('Rag', 'Rags1', 1, date('now')),
('Tactical Army Pants', 'Zombie_MilitaryPants_06', 1, date('now')),
('SpicesMix_02', 'SpicesMix_02', 1, date('now')),
('Bolt', 'Bolts', 1, date('now')),
('Fingerless Gloves', 'Zombie_Open_Finger_Gloves_02', 1, date('now')),
('Hirschbein', 'Buck_Right_Back_Leg', 1, date('now')),
('Toast', 'Toast', 1, date('now')),
('Chop_Boar_Limbs', 'Chop_Boar_Limbs', 1, date('now')),
('Slice_Zombie_Clothes_05', 'Slice_Zombie_Clothes_05', 1, date('now')),
('Cooked Pasta', 'Cooked_Pasta_01', 1, date('now')),
('Glass', 'Jar_02', 1, date('now')),
('Dolls Meat', 'ZombieMeat', 1, date('now')),
('Chocolate Bar', 'ChocolateCandy_09', 1, date('now')),
('Zombie_01_Head', 'Zombie_01_Head', 1, date('now')),
('Chop_Deer_Limbs', 'Chop_Deer_Limbs', 1, date('now')),
('Weapon_Improvised_Handgun', 'Weapon_Improvised_Handgun', 1, date('now')),
('Horsehead', 'Horse_Head', 1, date('now')),
('Take_Bandage_Out', 'Take_Bandage_Out', 1, date('now')),
('Cracker', 'Crackers', 1, date('now')),
('Dirty Rags', 'Rags_Dirty', 1, date('now')),
('Baked Beans', 'BakedBeans', 1, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_02_03', 1, date('now')),
('Hippy Pants', 'Zombie_Hippie_Pants_01_03', 1, date('now')),
('Logs', 'Wooden_Log_02', 1, date('now')),
('Egg For Cooking', 'CookEgg2', 1, date('now')),
('Human Foot', 'Prisoner_Right_Foot', 1, date('now')),
('Ammunition Box 5.45 × 39 Mm', 'Cal_5_45x39_AmmoboxOpen', 1, date('now')),
('Pear', 'Pear', 1, date('now')),
('Leather Strips', 'Leather_Strip', 1, date('now')),
('Slice_Zombie_Clothes_02', 'Slice_Zombie_Clothes_02', 1, date('now')),
('Skinned Bear', 'Bear_Skinned', 1, date('now')),
('Smoked Rabbit Meat', 'Smoked_RabbitMeat', 1, date('now')),
('Orange Juice', 'GlassBottle04', 1, date('now')),
('Cotton Shirt', 'Zombie_Shirt_01', 1, date('now')),
('Carrot', 'Carrot', 1, date('now')),
('Rehbein', 'Doe_Left_Front_Leg', 1, date('now')),
('Smoked Bear Steak', 'Smoked_Bear_Steak', 1, date('now')),
('Hirschbein', 'Buck_Right_Front_Leg', 1, date('now')),
('Beanie', 'Zombie_Beenie_07', 1, date('now')),
('Human Head', 'Prisoner_Head', 1, date('now')),
('Wild Steak', 'Doe_01_Steak', 1, date('now')),
('People Steak', 'Human_Steak', 1, date('now')),
('Improvised Water Tank', 'Improvised_Water_container', 1, date('now')),
('Wine', 'Wine', 1, date('now')),
('Brake Fluid', 'Break_Oil', 1, date('now')),
('Emergency bandage', 'Emergency_bandage', 1, date('now')),
('Cartridge Sleeve .50 Bwg', 'Cal50_Empty', 1, date('now')),
('Leather Pieces', 'Leather_Sheet', 1, date('now')),
('Magnifying Glass', 'Magnifying_Glass1', 1, date('now')),
('Wooden Spoon', 'Wooden_Spoon', 1, date('now')),
('Smoked Sausages', 'Smoked_Sausages', 1, date('now')),
('Lemon', 'Lemon', 1, date('now')),
('Chop_Duck_Skinned', 'Chop_Duck_Skinned', 1, date('now')),
('Grapes', 'Grapes_Raw', 1, date('now')),
('Emergency bandage Big', 'Emergency_bandage_Big', 1, date('now')),
('Bear Leg', 'Bear_Left_Back_Leg', 1, date('now')),
('TEC01 M9', 'M9', 1, date('now')),
('Blue Bald Head', 'Psilocybe_Cyanescens', 1, date('now')),
('Duck Legs', 'White_Duck_Legs', 1, date('now')),
('Stew', 'Stew2', 1, date('now')),
('Pasta', 'Cooked_Pasta_02', 1, date('now')),
('Zombie_01_Left_Arm', 'Zombie_01_Left_Arm', 1, date('now')),
('Coal', 'Charcoal', 1, date('now')),
('Breast Meat', 'Bird_Breasts_Small', 1, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_02_01', 1, date('now')),
('Donkey Steak', 'Donkey_Steak', 1, date('now')),
('Glue', 'Glue', 1, date('now')),
('Trucker Jacket', 'Zombie_Trucker_Jacket_02', 1, date('now')),
('Magazine SVD Dragunov', 'Magazine_SVD_Dragunov', 1, date('now')),
('M1 Rifle', 'Weapon_M1_Garand', 1, date('now')),
('Instant Oatmeal', 'Instant_OatMeal', 1, date('now')),
('Smoked Chicken Meat', 'Smoked_ChickenMeat', 1, date('now')),
('Gulls Keulen', 'Seagull_Legs', 1, date('now')),
('Sweet And Sour Chicken In Canton Style', 'Cantonese_Sweet_And_sour_01', 1, date('now')),
('Ammunition Box Caliber .22', 'Cal22_Ammobox_Open', 1, date('now')),
('Ammunition Container .50 Bwg', 'Cal50_AmmoboxOpen', 1, date('now')),
('Hippy Pants', 'Zombie_Hippie_Pants_02_01', 1, date('now')),
('Zombie_01_Left_Foot', 'Zombie_01_Left_Foot', 1, date('now')),
('ACOG Scope', 'WeaponScope_ACOG_01', 1, date('now')),
('Whiskey', 'Whiskey', 1, date('now')),
('Chop_Tree_01', 'Chop_Tree_01', 1, date('now')),
('Ris Adapter For Ak47', 'ScopeRail_AK47', 1, date('now')),
('Smoked Sheep Steak', 'Smoked_Sheep_Steak', 1, date('now')),
('Rubber Band', 'Rubber_band', 1, date('now')),
('Sardine', 'CannedSardine', 1, date('now')),
('Crow Breasts', 'Crow_Breasts', 1, date('now')),
('Canteen', 'Canteen', 1, date('now')),
('Kiwi', 'Kiwi', 1, date('now')),
('Bear Leg', 'Bear_Left_Front_Leg', 1, date('now')),
('Cartridge .45 Acp', 'Cal45', 1, date('now')),
('Event_2H_Katana', 'Event_2H_Katana', 1, date('now')),
('Cannon Ammunition', 'Cal20mm_AmmoBoxClosed', 1, date('now')),
('Cal_50_AE_Ammobox_Open', 'Cal_50_AE_Ammobox_Open', 1, date('now')),
('Wooden Board', 'Wooden_Plank', 1, date('now')),
('Cartridge 7.62 X 51 Mm', 'Cal7_62x51mm', 1, date('now')),
('Chop_Watermelon', 'Chop_Watermelon', 1, date('now')),
('Slice_Clothes_02', 'Slice_Clothes_02', 1, date('now')),
('Smoked Calf Steak', 'Smoked_Veal_Steak', 1, date('now')),
('Cal_357_Ammobox_Open', 'Cal_357_Ammobox_Open', 1, date('now')),
('Cooked Vegetables', 'Cooked_Vegetables_01', 1, date('now')),
('Angler', 'Zombie_Boonie_Hat_13', 1, date('now')),
('Scrap Metal', 'Metal_Scrap_05', 1, date('now')),
('"uncle Pong" Rice', 'Rice', 1, date('now')),
('Stone', 'Stone', 1, date('now')),
('Cone-headed Tuber-leaved Mushroom', 'Amanita_Virosa', 1, date('now')),
('Dirty Rags', 'Rag_Stripes_Dirty', 1, date('now')),
('Mosin-nagant', 'Mosin_nagant', 1, date('now')),
('Improvised Rope', 'Improvised_rope', 1, date('now')),
('Beretta M9', 'BerettaM9', 1, date('now')),
('Date', 'Date', 1, date('now')),
('Chop_Crow_Skinned', 'Chop_Crow_Skinned', 1, date('now')),
('Guava', 'GuavaHalves', 1, date('now')),
('Paper', 'Paper', 1, date('now')),
('Skinned Rat', 'Rat_torso', 1, date('now')),
('Adrenaline Syringe', 'Adrenaline_Shot', 1, date('now')),
('Chips "classic"', 'Chips', 1, date('now')),
('Sausages', 'Sausages', 1, date('now')),
('Improvised Metal Spear', 'Improvised_Metal_Spear', 1, date('now')),
('Cal_50_AE_1pcs', 'Cal_50_AE_1pcs', 1, date('now')),
('Skewer', 'Skewer_Vegetables', 1, date('now')),
('Smoker', 'Smoker_01', 1, date('now')),
('Tin Opener', 'CanOpener', 1, date('now')),
('Rehbein', 'Goat_Horns', 1, date('now')),
('Produce Preserve', 'CanningFood', 1, date('now')),
('Bundle_Wooden_Plank', 'Bundle_Wooden_Plank', 1, date('now')),
('Copper Coins', 'Copper_Coins', 1, date('now')),
('Water Bottle', 'Water_05l', 1, date('now')),
('Tactical Gloves', 'Zombie_Tactical_Gloves_03', 1, date('now')),
('Pot Roast', 'Pot_meat', 1, date('now')),
('Big Nettle', 'Stinging_Nettle', 1, date('now')),
('Cal_50_AE_Ammobox_Closed', 'Cal_50_AE_Ammobox_Closed', 1, date('now')),
('Walnut', 'Walnut', 1, date('now')),
('Tomato Sauce', 'TomatoSouce', 1, date('now')),
('Superglue', 'Super_Glue', 1, date('now')),
('Mulberry', 'Mulberry', 1, date('now')),
('Event_Sledgehammer', 'Event_Sledgehammer', 1, date('now')),
('Goats Hull', 'Goat_Torso', 1, date('now')),
('Ingredients For Chili Con Carne', 'Chili_con_Carne_Preparation', 1, date('now')),
('Spas-12', 'SPAS-12', 1, date('now')),
('Scrap Metal', 'Metal_Scrap_02', 1, date('now')),
('Sugar Beet', 'SugarBeet', 1, date('now')),
('Skewer_Sausages', 'Skewer_Sausages', 1, date('now')),
('Chop_Goat_Limb_Back', 'Chop_Goat_Limb_Back', 1, date('now')),
('Tangerine', 'Tangerine', 1, date('now')),
('Gunpowder', 'Gun_Powder', 1, date('now')),
('Tinder', 'Tinder', 1, date('now')),
('Skinned Swan', 'Swan_Skinned', 1, date('now')),
('Lime Shower', 'PETBottle04', 1, date('now')),
('Lighter', 'Lighter', 1, date('now')),
('Slice_Clothes_06_RagsWithAnimalSkin', 'Slice_Clothes_06_RagsWithAnimalSkin', 1, date('now')),
('Small Stone', 'Stone_Small', 1, date('now')),
('Car Battery', 'Car_Battery', 1, date('now')),
('Plastic Bowl', 'Pot2', 1, date('now')),
('Ammunition Box 7,62 × 54 Mm R', 'Cal7_62x54mmR_Ammobox_Open', 1, date('now')),
('Beef Stew Preserve', 'CannedGoulash', 1, date('now')),
('Eselskopf', 'Donkey_Head', 1, date('now')),
('Chop_Donkey', 'Chop_Donkey', 1, date('now')),
('Aks-74u', 'Weapon_AKS_74U', 1, date('now')),
('Santa_Glove', 'Santa_Glove', 1, date('now')),
('Skinned Boar', 'Boar_Skinned', 1, date('now')),
('Chop_Bear_Skinned', 'Chop_Bear_Skinned', 1, date('now')),
('Cantaloupe', 'CantaloupeMelon', 1, date('now')),
('Real Chanterelle', 'Cantharellus_Cibarius', 1, date('now')),
('Vodka "majestic Bear"', 'Vodka', 1, date('now')),
('Ammunition Box 7.62 X 51 Mm', 'Cal7_62x51mm_Ammobox_Open_2', 1, date('now')),
('Cartridge Sleeve .45 Acp', 'Cal45_Empty', 1, date('now')),
('Smoked Pork Steak', 'Smoked_Pork_Steak', 1, date('now')),
('Bunch Of Wooden Sticks', 'Wooden_Sticks_Bundle_Large', 1, date('now')),
('Fishing Hook', 'Fishing_hook', 1, date('now')),
('Smoked Cat Steak', 'Smoked_Cat_Steak', 1, date('now')),
('Breast Meat', 'Bird_Breasts_Large', 1, date('now')),
('Smoked Human Sausage', 'Smoked_Human_Sausages', 1, date('now')),
('Aspirin', 'Aspirin', 1, date('now')),
('Cola', 'Can04', 1, date('now')),
('Peachcompote', 'CannedPeach', 1, date('now')),
('Cartridge Sleeve Caliber .22', 'Cal22_Empty', 1, date('now')),
('Soap', 'Soap', 1, date('now')),
('CantaloupeMelon Slice', 'CantaloupeMelon_Slice', 1, date('now')),
('Slice_Zombie_Clothes_01', 'Slice_Zombie_Clothes_01', 1, date('now')),
('Skinned Seagull', 'Seagull_Skinned', 1, date('now')),
('Smoked Rat Meat', 'Smoked_RatMeat', 1, date('now')),
('Soy Sauce', 'SoySauce', 1, date('now')),
('Cannon Ammunition 20 Mm', 'Cal20mm', 1, date('now')),
('Orange', 'Orange', 1, date('now')),
('Penicillin', 'Penicillin01', 1, date('now')),
('MRE Stew', 'MRE_Stew', 1, date('now')),
('Cal30-06_5_bullets', 'Cal30-06_5_bullets', 1, date('now')),
('Pancakes', 'Pancakes', 1, date('now')),
('Cal_357_5pcs', 'Cal_357_5pcs', 1, date('now')),
('Blackberry', 'Blackberry', 1, date('now')),
('Slice_Dirty_Rags_Into_Stripes', 'Slice_Dirty_Rags_Into_Stripes', 1, date('now')),
('Logs', 'Wooden_Log_01', 1, date('now')),
('Cartridge 5.45 × 39 Mm', 'Cal_5_45x39_Bullet', 1, date('now')),
('Atropinspritze', 'AtropineInjection', 1, date('now')),
('Goat Steak', 'Goat_Steak', 1, date('now')),
('Small Wooden Stick', 'Wooden_Stick', 1, date('now')),
('Bone', 'Animal_Bone_Big', 1, date('now')),
('Coprinus Comatus', 'Coprinus_Comatus', 1, date('now')),
('Cartridge 5.45 × 39 Mm', 'Cal_5_45x39_empty', 1, date('now')),
('Dandelion', 'Dandelion', 1, date('now')),
('Dog Food', 'CannedDogFood', 1, date('now')),
('Jerrycan', 'Gasoline_Canister', 1, date('now')),
('Milk', 'Milk', 1, date('now')),
('Chop_Deer_Skinned', 'Chop_Deer_Skinned', 1, date('now')),
('Silberband', 'Silver_Strip', 1, date('now')),
('Wild Boar Head', 'Boar_head', 1, date('now')),
('Peachcompote', 'CannedPear', 1, date('now')),
('Fire Drill', 'Fire_Hand_Drill_new', 1, date('now')),
('Tactical Jacket', 'Zombie_Tactical_Jacket_01', 1, date('now')),
('Boar Claws', 'Boar_Hooves_Back', 1, date('now')),
('Bärenkopf', 'Bear_Head', 1, date('now')),
('Thread', 'Thread', 1, date('now')),
('Hüfttasche', 'Zombie_Waist_Bag_Small_01', 1, date('now')),
('Onion', 'Onion', 1, date('now')),
('Tomato', 'Tomato', 1, date('now')),
('Hirschbein', 'Buck_Left_Back_Leg', 1, date('now')),
('Apple_2', 'Apple_2', 1, date('now')),
('Slicker', 'Zombie_Raincoat_Down_01', 1, date('now')),
('Tin', 'CannedFood1', 1, date('now')),
('Big Stone', 'Stone_Large', 1, date('now')),
('Meat Snack Spicy', 'MeatSnack_01', 1, date('now')),
('Cucumber', 'Cucumber', 1, date('now')),
('Long Wooden Stick', 'Long_wooden_stick', 1, date('now')),
('Burger', 'Burger', 1, date('now')),
('Strawberry Toaster Pastries', 'Toaster_Pastries', 1, date('now')),
('Ammunition Box .45 Acp', 'Cal45_AmmoboxClosed', 1, date('now')),
('Chop_Zombie', 'Chop_Zombie', 1, date('now')),
('Cal_357_Ammobox_Closed', 'Cal_357_Ammobox_Closed', 1, date('now')),
('Joints Of Meat', 'Bird_Legs_Small', 1, date('now')),
('Smoked Duck Meat', 'Smoked_DuckMeat', 1, date('now')),
('Zucchini', 'Zucchini', 1, date('now')),
('Sea-salt', 'SeaSalt_01', 1, date('now')),
('Left Rabbit Spine Piece', 'Rabbit_Left_Back', 1, date('now')),
('Ammunition Box 7.62 × 39 Mm', 'Cal7_62x39mm_Ammobox_Open', 1, date('now')),
('Fat', 'Big_Animal_Fat', 1, date('now')),
('MRE TunaSalad', 'MRE_TunaSalad', 1, date('now')),
('Smoked Pheasant Meat', 'Smoked_PheasantMeat', 1, date('now')),
('Cal30-06_Bullet', 'Cal30-06_Bullet', 1, date('now')),
('Hammock', 'Hammock', 1, date('now')),
('Cal30-06_Ammobox_Closed', 'Cal30-06_Ammobox_Closed', 1, date('now')),
('Smoked Wild Boar Meat', 'Smoked_Boar_Steak', 1, date('now')),
('Lead Plate', 'Lead_Plate', 1, date('now')),
('Goose Meat', 'GooseMeat', 1, date('now')),
('Bean Stew', 'Beans_Stew_02', 1, date('now')),
('Cartridge Sleeve 9 Mm', 'Cal_9mm_empty', 1, date('now')),
('Cal7_62x39mm_5_Pile', 'Cal7_62x39mm_5_Pile', 1, date('now')),
('Event_2H_Axe', 'Event_2H_Axe', 1, date('now')),
('Safety Pin', 'Safety_pin', 1, date('now')),
('Horse`s Leg', 'Horse_Front_Limb', 1, date('now')),
('Caramel Shower', 'PETBottle01', 1, date('now')),
('Blue Jeans', 'Zombie_Jeans_01_01', 1, date('now')),
('Work Trousers', 'Zombie_MilitaryPants_01', 1, date('now')),
('Sedative', 'Sedative', 1, date('now')),
('Skinned Bird', 'Bird_Skinned_Large', 1, date('now')),
('Ammunition Box Caliber .500 S & M', 'Cal500SW_AmmoboxOpen', 1, date('now')),
('Duct Tape', 'Duct_Tape', 1, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_01_01', 1, date('now')),
('Hazel', 'Hazelnuts', 1, date('now')),
('Acorns', 'Oak_Nuts', 1, date('now')),
('Zombie_Tactical_Jacket_05', 'Zombie_Tactical_Jacket_05', 1, date('now')),
('Spaghetti Bolognese', 'Spaghetti_bolognese_02', 1, date('now')),
('Ziegenbein', 'Goat_Back_Limb', 1, date('now')),
('Smoke Grenade', 'Smoke_Grenade', 1, date('now')),
('Steak With Potatoes', 'Steak_With_Potatoes_01', 1, date('now')),
('Ammunition Box 7.62 × 39 Mm', 'Cal7_62x39mm_Ammobox_Closed', 1, date('now')),
('Chop_Donkey_Limb_Front', 'Chop_Donkey_Limb_Front', 1, date('now')),
('Motherboard', 'MOtherboard', 1, date('now')),
('Potato', 'Potato', 1, date('now')),
('Cooked Potato', 'Cooked_potato', 1, date('now')),
('Logs', 'Wooden_Log_Small_03', 1, date('now')),
('Tripwire Trap', 'Trip_wire_dead_fall_for_large_animals', 1, date('now')),
('Pigeons Keulen', 'Pigeon_Legs', 1, date('now')),
('TEC01 490', 'Weapon_590A11', 1, date('now')),
('Chop_Doe_Torso', 'Chop_Doe_Torso', 1, date('now')),
('Soup', 'Soup_01', 1, date('now')),
('Riesenbovist', 'Lycoperdon_Gigantea', 1, date('now')),
('Bicarbonate Of Soda', 'BakingSoda', 1, date('now')),
('Broccoli', 'Broccoli', 1, date('now')),
('Freshwater Fish', 'FishFreshwater', 1, date('now')),
('Lime Juice', 'GlassBottle03', 1, date('now')),
('Flashbang', 'Flashbang', 1, date('now')),
('Portable Gas Cooker', 'Portable_Gas_Stove', 1, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_01_02', 1, date('now')),
('Kitchen Board', 'Kitchen_Board_02', 1, date('now')),
('Anode Plate', 'Anode_Plate', 1, date('now')),
('Sewing', 'Sewing_kit', 1, date('now')),
('Flannel Shirt', 'Zombie_Woodcutter_Shirt_03', 1, date('now')),
('Intestines', 'Big_Animal_guts', 1, date('now')),
('Beef Stew', 'BeefStew', 1, date('now')),
('Vinegar', 'Vinegar', 1, date('now')),
('Ammunition Box Caliber .500 S & M', 'Cal500SW_Ammoboxclosed', 1, date('now')),
('Scope Rail (Dragunov)', 'ScopeRail_Dragunov', 1, date('now')),
('Cartridge 7.62 × 54 Mm R', 'Cal7_62x54mmR', 1, date('now')),
('Skinned Goat', 'Goat_Skinned', 1, date('now')),
('Aks-74u Magazine', 'Magazine_AKS_74U', 1, date('now')),
('Honeycomb', 'Honeycomb', 1, date('now')),
('Lime', 'Lime', 1, date('now')),
('Logs', 'Wooden_Log_Small_02', 1, date('now')),
('Left Rabbit Front Piece', 'Rabbit_Left_Front', 1, date('now')),
('Sheep Steak', 'Sheep_Steak', 1, date('now')),
('Spice Mix', 'SpicesMix_01', 1, date('now')),
('Pike', 'Skewer_02', 1, date('now')),
('Strawberry', 'Wild_Strawberry', 1, date('now')),
('Schokoküchlein', 'ChocolateCandy_03', 1, date('now')),
('Tactical Sweater', 'Zombie_Tactical_Sweater_06', 1, date('now')),
('Dogs Steak', 'Dog_Steak', 1, date('now')),
('Yeast', 'Yeast', 1, date('now')),
('Scrap Metal', 'Metal_Scrap_01', 1, date('now')),
('Pineapple', 'Pineapple', 1, date('now')),
('Parsley', 'Parsley', 1, date('now')),
('Chow Mein', 'Chow_Mein', 1, date('now')),
('Ammunition Container .50 Bwg', 'Cal50_AmmoboxClosed', 1, date('now')),
('Chop_Duck', 'Chop_Duck', 1, date('now')),
('Weapon_Improvised_Rifle', 'Weapon_Improvised_Rifle', 1, date('now')),
('Ingredients For Stew', 'StewPreparation', 1, date('now')),
('Barrel With Saltwater Fish', 'Salted_fish_Barrel_01', 1, date('now')),
('NightVisionGoggles2_Test', 'NightVisionGoggles2_Test', 1, date('now')),
('Grill', 'Grill', 1, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_02_02', 1, date('now')),
('Chop_Doe', 'Chop_Doe', 1, date('now')),
('Breast Meat', 'Bird_Breasts_Medium', 1, date('now')),
('Aloe Vera', 'Aloe_Vera', 1, date('now')),
('Hirschbein', 'Buck_Left_Front_Leg', 1, date('now')),
('Wolf Leg', 'Wolf_Left_Front_Leg', 1, date('now')),
('Diary', 'Diary', 1, date('now')),
('Ammunition Box 7.62 X 51 Mm', 'Cal7_62x51mm_Ammobox_Closed_2', 1, date('now')),
('Loaf', 'Bread', 1, date('now')),
('Needle', 'Needle', 1, date('now')),
('Apple Pie', 'Apple_Pie', 1, date('now')),
('Rodent Meat', 'RodentMeat', 1, date('now')),
('Zombie_Shirt_02', 'Zombie_Shirt_02', 1, date('now')),
('M1-loading Frame', 'M1_Clip', 1, date('now')),
('Chop_Horse_Back_Limb', 'Chop_Horse_Back_Limb', 1, date('now')),
('Improvised Wooden Spear', 'Improvised_Wooden_Spear', 1, date('now')),
('Skinned Crow', 'Crow_Skinned', 1, date('now')),
('Canned Meat', 'Spam', 1, date('now')),
('Skinned Bird', 'Bird_Skinned_Medium', 1, date('now')),
('Improvised Magnifying Glass', 'Magnifying_Glass', 1, date('now')),
('Aluminum Strips', 'Aluminium_Strip', 1, date('now')),
('Improvised_Wooden_Chest', 'Improvised_Wooden_Chest', 1, date('now')),
('Copper Tape', 'Copper_Strip', 1, date('now')),
('Duck Meat', 'DuckMeat', 1, date('now')),
('Skinned Rabbit', 'Rabbit_Skinned', 1, date('now')),
('Cigarettes "classics"', 'Cigarettes', 1, date('now')),
('ChocolateCandy_05', 'ChocolateCandy_05', 1, date('now')),
('Akm', 'BPC_Weapon_AKM', 1, date('now')),
('Swan Keulen', 'Swan_Legs', 1, date('now')),
('Boar Hull', 'Boar_Torso', 1, date('now')),
('Cotton Hoodie', 'Zombie_Hoodie_02', 1, date('now')),
('Smoked Human Steak', 'Smoked_Human_Steak', 1, date('now')),
('Swan Chest', 'Swan_Breasts', 1, date('now')),
('Boiled Egg', 'Cooked_egg', 1, date('now')),
('Cauliflower', 'Cauliflower', 1, date('now')),
('Antler', 'Buck_Antlers', 1, date('now')),
('Glossy Lackporling', 'Ganoderma_Lucidum', 1, date('now')),
('Skinned Wolf', 'Wolf_Skinned', 1, date('now')),
('Chili Con Carne', 'Chilli_Con_Carne_02', 1, date('now')),
('Garlic', 'Garlic', 1, date('now')),
('Cartridge 7.62 × 39 Mm', 'Cal7_62x39mm', 1, date('now')),
('Crab_Apple', 'Crab_Apple', 1, date('now')),
('Chop_Wolf_Torso', 'Chop_Wolf_Torso', 1, date('now')),
('Auto Gloves', 'Zombie_Driving_Gloves_03', 1, date('now')),
('Biscuits', 'Pastry', 1, date('now')),
('ChocolateCandy_06', 'ChocolateCandy_06', 1, date('now')),
('Zombie_Tactical_Gloves_07', 'Zombie_Tactical_Gloves_07', 1, date('now')),
('Cereal BunnyStars', 'Cereal_BunnyStars', 1, date('now')),
('Rice', 'Cooked_Rice', 1, date('now')),
('Improvised Stone Spear', 'Improvised_Stone_Spear', 1, date('now')),
('Honey Yellow Hamburger', 'Armillaria_Mellea', 1, date('now')),
('Cartridge 5.45 × 39 Mm', 'Cal_5_45x39_Pile', 1, date('now')),
('Baby Food', 'BabyFood', 1, date('now')),
('Shorts', 'Zombie_Shorts_Pants_07', 1, date('now')),
('Egg For Cooking', 'CookEgg1', 1, date('now')),
('Skinned Deer', 'Buck_Skinned', 1, date('now')),
('Make_Lead_Plates', 'Make_Lead_Plates', 1, date('now')),
('Pasta', 'Pasta', 1, date('now')),
('Chop_Seagull', 'Chop_Seagull', 1, date('now')),
('Cartridge Sleeve 7.62 × 54 Mm R', 'Cal7_62x54mmR_Empty', 1, date('now')),
('Popcorn', 'Popcorn_02', 1, date('now')),
('Half Bear Hull', 'Bear_Right_Torso_Half', 1, date('now')),
('Schokopraline', 'ChocolateCandy_10', 1, date('now')),
('Pheasant', 'PheasantMeat', 1, date('now')),
('Common Giant Parakeet', 'Lepiota_Procera', 1, date('now')),
('Chop_Horse', 'Chop_Horse', 1, date('now')),
('Chop_Wolf_Skinned', 'Chop_Wolf_Skinned', 1, date('now')),
('Chicken', 'ChickenMeat', 1, date('now')),
('Cartridge 9 Mm', 'Cal_9mm', 1, date('now')),
('M9 Magazine', 'Magazine_M9', 1, date('now')),
('Duck Breast', 'White_Duck_Breasts', 1, date('now')),
('Tactical Army Pants', 'Zombie_MilitaryPants_04', 1, date('now')),
('Slate Schillerporling', 'Inonotus_Obliquus', 1, date('now')),
('Zombie_WorkPants_03', 'Zombie_WorkPants_03', 1, date('now')),
('Camouflage Jacket', 'Zombie_Camouflage_Jacket_01', 1, date('now')),
('Cartridge Sleeve .500 S & M', 'Cal500SW_Empty', 1, date('now')),
('Skinned Donkey', 'Donkey_skinned', 1, date('now')),
('Vitamin Tablets (box)', 'Vitamins_02', 1, date('now')),
('Fruit Cocktail', 'CannedFruitCoctail', 1, date('now')),
('Saltwater Fish', 'SeaWaterFish', 1, date('now')),
('Work Jacket', 'Zombie_Work_Jacket_01', 1, date('now')),
('Cartridge .500 S & M', 'Cal500SW', 1, date('now')),
('Earthworm', 'Earthworm', 1, date('now')),
('Chop_Boar_Torso', 'Chop_Boar_Torso', 1, date('now')),
('Barbed Wire', 'Barbed_Wire', 1, date('now')),
('SVD Dragunov', 'Weapon_SVD_Dragunov', 1, date('now')),
('Paper', 'Test_Paper', 1, date('now')),
('Improvised_Metal_Chest', 'Improvised_Metal_Chest', 1, date('now')),
('Rehbein', 'Doe_Right_Front_Leg', 1, date('now')),
('Ziegenbein', 'Goat_Front_Limb', 1, date('now')),
('Pan', 'Pan', 1, date('now')),
('Common Cep', 'Boletus_Edulis', 1, date('now')),
('Animal Bones', 'Animal_Bone_SMall', 1, date('now')),
('Crow Keulen', 'Crow_Legs', 1, date('now')),
('Green Tuber Leaf Mushroom', 'Amantia_phalloides', 1, date('now')),
('Zombie_Working_pants_01', 'Zombie_Working_pants_01', 1, date('now')),
('Gear', 'Gear', 1, date('now')),
('Rat`s Head', 'Rat_Head', 1, date('now')),
('Chop_Deer', 'Chop_Deer', 1, date('now')),
('Chop_Horse_Front_Limb', 'Chop_Horse_Front_Limb', 1, date('now')),
('Chili Con Carne', 'Chilli_Con_Carne_01', 1, date('now')),
('Watermelon', 'Watermelon', 1, date('now')),
('Smoked Wild Steak', 'Smoked_Deer_Steak', 1, date('now')),
('Wolf Head', 'Wolf_Head', 1, date('now')),
('Coward', 'Fig', 1, date('now')),
('Skinned Duck', 'White_Duck_Skinned', 1, date('now')),
('Shelter', 'Shelter', 1, date('now')),
('Pike', 'Skewer', 1, date('now')),
('Fried Egg', 'Fried_Egg_02', 1, date('now')),
('Crab Legs', 'Crab_Legs', 1, date('now')),
('Tequila', 'Tequila', 1, date('now')),
('Leather Jacket', 'Zombie_Jacket_01', 1, date('now')),
('German Helmet (2nd Ww)', 'WW2_German_Helmet', 1, date('now')),
('Skinned Pigeon', 'Pigeon_Skinned', 1, date('now')),
('SVD Scope', 'WeaponScope_Dragunov', 1, date('now')),
('Standing_Torch_01', 'Standing_Torch_01', 1, date('now')),
('Ak-47', 'Weapon_AK47', 1, date('now')),
('Chocolate Bar', 'ChocolateCandy_08', 1, date('now')),
('Small Toolbox', 'Tool_Box_SMall', 1, date('now')),
('Spaghetti With Meatballs', 'CannedSpaghetti', 1, date('now')),
('Sugar', 'Sugar', 1, date('now')),
('MRE Cheeseburger', 'MRE_Cheeseburger', 1, date('now')),
('Chocolate Bar', 'ChocolateCandy_11', 1, date('now')),
('Carbon Electrodes', 'Carbon_Electrodes', 1, date('now')),
('Seagulls Chest', 'Seagull_Breasts', 1, date('now')),
('Black Olives', 'BlackOlives', 1, date('now')),
('Event_1H_N9_Black', 'Event_1H_N9_Black', 1, date('now')),
('PrepareCannedFood', 'PrepareCannedFood', 1, date('now')),
('Human Leg', 'Prisoner_Left_Leg', 1, date('now')),
('Peeled Tomatoes', 'TomatoPelate', 1, date('now')),
('Improvised Fireplace', 'Fireplace2', 1, date('now')),
('Rat Meat', 'RatMeat', 1, date('now')),
('Sweet And Sour Chicken In Canton Style', 'Cantonese_Sweet_And_sour_02', 1, date('now')),
('Chop_Goat_Skinned', 'Chop_Goat_Skinned', 1, date('now')),
('Chop_Debree_Log_Big_03', 'Chop_Debree_Log_Big_03', 1, date('now')),
('Isopropanol', 'Isopropyl_alcohol', 1, date('now')),
('Cornflakes', 'Corn_flakes', 1, date('now')),
('Shorts', 'Zombie_Shorts_Pants_04', 1, date('now')),
('Rehkopf', 'Doe_Head', 1, date('now')),
('NightVisionGoggles Test', 'NightVisionGoggles_Test', 1, date('now')),
('Chop_Donkey_Torso', 'Chop_Donkey_Torso', 1, date('now')),
('Chocolate', 'ChocolateCandy_04', 1, date('now')),
('Lime Shower', 'PETBottle03', 1, date('now')),
('Chop_Doe_Limbs', 'Chop_Doe_Limbs', 1, date('now')),
('Smoked Goat Steak', 'Smoked_Goat_Steak', 1, date('now')),
('Training Jacket', 'Vest_01_01', 1, date('now')),
('Human Leg', 'Prisoner_Right_Leg', 1, date('now')),
('Boar Claws', 'Boar_Hooves_front', 1, date('now')),
('Intestines', 'Small_Animal_guts', 1, date('now')),
('Skinned Bird', 'Bird_Skinned_Small', 1, date('now')),
('Human Arm', 'Prisoner_Left_Arm', 1, date('now')),
('Wild Garlic', 'Ramsons', 1, date('now')),
('E_1H_Small_Axe', 'E_1H_Small_Axe', 1, date('now')),
('Antenna', 'Antena', 1, date('now')),
('Corn', 'Corn', 1, date('now')),
('Beer', 'Beer', 1, date('now')),
('Chop_Big_Log', 'Chop_Big_Log', 1, date('now')),
('Wheat Flour', 'WhiteFlour', 1, date('now')),
('9mm Ammunition Box', 'Cal_9mm_AmmoboxClosed', 1, date('now')),
('Larva', 'Larve', 1, date('now')),
('Ravioli With Beef', 'BeefRavioli', 1, date('now')),
('Chop_Rat', 'Chop_Rat', 1, date('now')),
('Beefsteak Fungus', 'Fistula_Hepatica', 1, date('now')),
('Work Trousers', 'Working_pants_01', 1, date('now')),
('M9 Silver', 'M9_Silver', 1, date('now')),
('School Backpack Girl 03', 'School_Backpack_Girl_03', 1, date('now')),
('School Backpack Girl 02', 'School_Backpack_Girl_02', 1, date('now')),
('School Backpack Girl 01', 'School_Backpack_Girl_01', 1, date('now')),
('School Backpack Boy 03', 'School_Backpack_Boy_03', 1, date('now')),
('School Backpack Boy 02', 'School_Backpack_Boy_02', 1, date('now')),
('Cal7 62x54mm', 'Cal7_62x54mm', 1, date('now')),
('BeePollen Pils 03', 'BeePollen_Pils_03', 1, date('now')),
('BeePollen Pils 02', 'BeePollen_Pils_02', 1, date('now')),
('Antiparasitics 03', 'Antiparasitics_03', 1, date('now')),
('Antiparasitics 02', 'Antiparasitics_02', 1, date('now')),
('AntiMalariaPils 03', 'AntiMalariaPils_03', 1, date('now')),
('AntiMalariaPils 02', 'AntiMalariaPils_02', 1, date('now')),
('Antibiotics 03', 'Antibiotics_03', 1, date('now')),
('Antibiotics 02', 'Antibiotics_02', 1, date('now')),
('Anti Radiation Pils 03', 'Anti_Radiation_Pils_03', 1, date('now')),
('Anti Radiation Pils 02', 'Anti_Radiation_Pils_02', 1, date('now')),
('ActivatedCharcoal 03', 'ActivatedCharcoal_03', 1, date('now')),
('ActivatedCharcoal 02', 'ActivatedCharcoal_02', 1, date('now')),
('MilitaryBoots Peace', 'MilitaryBoots_Peace', 1, date('now')),
('Police Zombie Helmet2', 'Police_Zombie_Helmet2', 1, date('now')),
('Police Zombie Helmet', 'Police_Zombie_Helmet', 1, date('now')),
('Fireman Helmet 03', 'Fireman_Helmet_03', 1, date('now')),
('Fireman Helmet 02', 'Fireman_Helmet_02', 1, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_06', 1, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_05', 1, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_04', 1, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_03', 1, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_02', 1, date('now')),
('Bulletproof test', 'Bulletproof_test', 1, date('now')),
('Stabproof Vest 09', 'Stabproof_Vest_09', 1, date('now')),
('Stabproof Vest 08', 'Stabproof_Vest_08', 1, date('now')),
('Stabproof Vest 07', 'Stabproof_Vest_07', 1, date('now')),
('Stabproof Vest 06', 'Stabproof_Vest_06', 1, date('now')),
('Stabproof Vest 04', 'Stabproof_Vest_04', 1, date('now')),
('Stabproof Vest 03', 'Stabproof_Vest_03', 1, date('now')),
('Stabproof Vest 02', 'Stabproof_Vest_02', 1, date('now')),
('Camo Backpack 05', 'Camo_Backpack_05', 1, date('now')),
('Camo Backpack 04', 'Camo_Backpack_04', 1, date('now')),
('Camo Backpack 03', 'Camo_Backpack_03', 1, date('now')),
('Camo Backpack 02', 'Camo_Backpack_02', 1, date('now')),
('Assault Backpack', 'Backpack_01_09', 1, date('now')),
('Assault Backpack', 'Backpack_01_08', 1, date('now')),
('Assault Backpack', 'Backpack_01_07', 1, date('now')),
('Assault Backpack', 'Backpack_01_06', 1, date('now')),
('Assault Backpack', 'Backpack_01_05', 1, date('now')),
('Assault Backpack', 'Backpack_01_04', 1, date('now')),
('Assault Backpack', 'Backpack_01_03', 1, date('now')),
('Assault Backpack', 'Backpack_01_02', 1, date('now')),
('Backpack', 'Backpack_02_14', 1, date('now')),
('Backpack', 'Backpack_02_13', 1, date('now')),
('Backpack', 'Backpack_02_12', 1, date('now')),
('Backpack', 'Backpack_02_11', 1, date('now')),
('Backpack', 'Backpack_02_10', 1, date('now')),
('Backpack', 'Backpack_02_09', 1, date('now')),
('Backpack', 'Backpack_02_08', 1, date('now')),
('Backpack', 'Backpack_02_07', 1, date('now')),
('Backpack', 'Backpack_02_06', 1, date('now')),
('Backpack', 'Backpack_02_05', 1, date('now')),
('Backpack', 'Backpack_02_04', 1, date('now')),
('Backpack', 'Backpack_02_03', 1, date('now')),
('Backpack', 'Backpack_02_02', 1, date('now')),
('Raincoat Up 06', 'Raincoat_Up_06', 1, date('now')),
('Raincoat Up 05', 'Raincoat_Up_05', 1, date('now')),
('Raincoat Up 04', 'Raincoat_Up_04', 1, date('now')),
('Raincoat Up 03', 'Raincoat_Up_03', 1, date('now')),
('Raincoat Up 02', 'Raincoat_Up_02', 1, date('now')),
('Raincoat Up 01', 'Raincoat_Up_01', 1, date('now')),
('Raincoat Down 06', 'Raincoat_Down_06', 1, date('now')),
('Raincoat Down 05', 'Raincoat_Down_05', 1, date('now')),
('Raincoat Down 04', 'Raincoat_Down_04', 1, date('now')),
('Raincoat Down 03', 'Raincoat_Down_03', 1, date('now')),
('Raincoat Down 02', 'Raincoat_Down_02', 1, date('now')),
('Abundant_01', 'Abundant_01', 1, date('now')),
('Abundant_02', 'Abundant_02', 1, date('now')),
('Abundant_03', 'Abundant_03', 1, date('now')),
('Animal_Skin_Jacket', 'Animal_Skin_Jacket', 1, date('now')),
('Animal_Skin_Pants', 'Animal_Skin_Pants', 1, date('now')),
('Assault_Backpack', 'Assault_Backpack', 1, date('now')),
('Assault_Backpack1', 'Assault_Backpack1', 1, date('now')),
('Assault_Vest', 'Assault_Vest', 1, date('now')),
('Aviators', 'Aviators', 1, date('now')),
('Balaclava', 'Balaclava', 1, date('now')),
('Bandana', 'Bandana', 1, date('now')),
('Baseball_Cap_02', 'Baseball_Cap_02', 1, date('now')),
('Baseball_Cap_10', 'Baseball_Cap_10', 1, date('now')),
('Baseball_Cap_11', 'Baseball_Cap_11', 1, date('now')),
('Baseball_Cap_12', 'Baseball_Cap_12', 1, date('now')),
('Baseball_Cap_13', 'Baseball_Cap_13', 1, date('now')),
('Baseball_Cap_14', 'Baseball_Cap_14', 1, date('now')),
('Baseball_Cap_15', 'Baseball_Cap_15', 1, date('now')),
('Baseball_Cap_16', 'Baseball_Cap_16', 1, date('now')),
('Baseball_Cap_17', 'Baseball_Cap_17', 1, date('now')),
('Baseball_Cap_18', 'Baseball_Cap_18', 1, date('now')),
('Baseball_Cap_19', 'Baseball_Cap_19', 1, date('now')),
('Basic_Shirt', 'Basic_Shirt', 1, date('now')),
('Bear_Pow_One_Hand', 'Bear_Pow_One_Hand', 1, date('now')),
('Bear_Pow_Shoe', 'Bear_Pow_Shoe', 1, date('now')),
('Beenie_02', 'Beenie_02', 1, date('now')),
('Beenie_03', 'Beenie_03', 1, date('now')),
('Beenie_04', 'Beenie_04', 1, date('now')),
('Beenie_05', 'Beenie_05', 1, date('now')),
('Beenie_06', 'Beenie_06', 1, date('now')),
('Beenie_07', 'Beenie_07', 1, date('now')),
('Beenie_08', 'Beenie_08', 1, date('now')),
('Beenie_09', 'Beenie_09', 1, date('now')),
('Beenie_3_hole_02', 'Beenie_3_hole_02', 1, date('now')),
('Beenie_3_hole_03', 'Beenie_3_hole_03', 1, date('now')),
('Beenie_3_hole_04', 'Beenie_3_hole_04', 1, date('now')),
('Beenie_3_hole_05', 'Beenie_3_hole_05', 1, date('now')),
('Beenie_3_hole_06', 'Beenie_3_hole_06', 1, date('now')),
('Beenie_3_hole_07', 'Beenie_3_hole_07', 1, date('now')),
('Beenie_3_hole_08', 'Beenie_3_hole_08', 1, date('now')),
('Beenie_3_hole_09', 'Beenie_3_hole_09', 1, date('now')),
('Beenie_Test_02', 'Beenie_Test_02', 1, date('now')),
('BeerCan', 'BeerCan', 1, date('now')),
('Beret_Hat', 'Beret_Hat', 1, date('now')),
('Biker_Goggles', 'Biker_Goggles', 1, date('now')),
('Biker_Hat', 'Biker_Hat', 1, date('now')),
('Biker_Sunglasses', 'Biker_Sunglasses', 1, date('now')),
('Boonie_Hat_02', 'Boonie_Hat_02', 1, date('now')),
('Boonie_Hat_04', 'Boonie_Hat_04', 1, date('now')),
('Boonie_Hat_05', 'Boonie_Hat_05', 1, date('now')),
('Boonie_Hat_06', 'Boonie_Hat_06', 1, date('now')),
('Boonie_Hat_07', 'Boonie_Hat_07', 1, date('now')),
('Boonie_Hat_08', 'Boonie_Hat_08', 1, date('now')),
('Boonie_Hat_09', 'Boonie_Hat_09', 1, date('now')),
('Boonie_Hat_10', 'Boonie_Hat_10', 1, date('now')),
('Boonie_Hat_11', 'Boonie_Hat_11', 1, date('now')),
('Boonie_Hat_12', 'Boonie_Hat_12', 1, date('now')),
('Boonie_Hat_13', 'Boonie_Hat_13', 1, date('now')),
('Boonie_Hat_14', 'Boonie_Hat_14', 1, date('now')),
('Boonie_Hat_15', 'Boonie_Hat_15', 1, date('now')),
('Borage', 'Borage', 1, date('now')),
('DropZoneKey', 'DropZoneKey', 1, date('now')),
('BPC_Weapon_98k_Karabiner_EVENT', 'BPC_Weapon_98k_Karabiner_EVENT', 1, date('now')),
('Bracken', 'Bracken', 1, date('now')),
('Buckwheat_grains', 'Buckwheat_grains', 1, date('now')),
('Business_Pants', 'Business_Pants', 1, date('now')),
('BusinessSuit', 'BusinessSuit', 1, date('now')),
('Cal20mm_AmmoBoxOpen', 'Cal20mm_AmmoBoxOpen', 1, date('now')),
('Cal7_62x39mm_20_Pile', 'Cal7_62x39mm_20_Pile', 1, date('now')),
('Cal7_62x39mm_5_bullets', 'Cal7_62x39mm_5_bullets', 1, date('now')),
('Camouflage_Jacket_02', 'Camouflage_Jacket_02', 1, date('now')),
('Camouflage_Jacket_03', 'Camouflage_Jacket_03', 1, date('now')),
('Cargo_Pants', 'Cargo_Pants', 1, date('now')),
('Cateye_Sunglasses', 'Cateye_Sunglasses', 1, date('now')),
('Chicory', 'Chicory', 1, date('now')),
('Chocolate_Milk', 'Chocolate_Milk', 1, date('now')),
('College_Jacket_02', 'College_Jacket_02', 1, date('now')),
('College_Jacket_03', 'College_Jacket_03', 1, date('now')),
('College_Jacket_04', 'College_Jacket_04', 1, date('now')),
('College_Jacket_05', 'College_Jacket_05', 1, date('now')),
('College_Jacket_06', 'College_Jacket_06', 1, date('now')),
('College_Jacket_07', 'College_Jacket_07', 1, date('now')),
('College_Jacket_08', 'College_Jacket_08', 1, date('now')),
('Common_01', 'Common_01', 1, date('now')),
('Common_02', 'Common_02', 1, date('now')),
('Common_03', 'Common_03', 1, date('now')),
('Cowboy_boots', 'Cowboy_boots', 1, date('now')),
('Cowboy_Hat', 'Cowboy_Hat', 1, date('now')),
('Cuff_Beanie_Hat', 'Cuff_Beanie_Hat', 1, date('now')),
('Dr_Gl', 'Dr_Gl', 1, date('now')),
('Driving_Gloves_02', 'Driving_Gloves_02', 1, date('now')),
('Driving_Gloves_03', 'Driving_Gloves_03', 1, date('now')),
('Driving_Gloves_04', 'Driving_Gloves_04', 1, date('now')),
('Duffle_Bag', 'Duffle_Bag', 1, date('now')),
('Energy_Drink', 'Energy_Drink', 1, date('now')),
('ExtremelyRare_01', 'ExtremelyRare_01', 1, date('now')),
('ExtremelyRare_02', 'ExtremelyRare_02', 1, date('now')),
('ExtremelyRare_03', 'ExtremelyRare_03', 1, date('now')),
('Fake_Nose_And_Sunglasses', 'Fake_Nose_And_Sunglasses', 1, date('now')),
('Fastdraw_Holster', 'Fastdraw_Holster', 1, date('now')),
('Football_Helmet', 'Football_Helmet', 1, date('now')),
('Gas_Mask', 'Gas_Mask', 1, date('now')),
('Ghillie_suit', 'Ghillie_suit', 1, date('now')),
('Goalie_Helmet', 'Goalie_Helmet', 1, date('now')),
('Gun_Holster', 'Gun_Holster', 1, date('now')),
('Gym_Bag', 'Gym_Bag', 1, date('now')),
('Heavy_Ballistic_Armor', 'Heavy_Ballistic_Armor', 1, date('now')),
('Hiking_Backpack_02', 'Hiking_Backpack_02', 1, date('now')),
('Hiking_Backpack_03', 'Hiking_Backpack_03', 1, date('now')),
('Hiking_Backpack_04', 'Hiking_Backpack_04', 1, date('now')),
('Hiking_Backpack_05', 'Hiking_Backpack_05', 1, date('now')),
('Hiking_Backpack_06', 'Hiking_Backpack_06', 1, date('now')),
('Hiking_Backpack_07', 'Hiking_Backpack_07', 1, date('now')),
('Hiking_Backpack_08', 'Hiking_Backpack_08', 1, date('now')),
('Hiking_Boots_02', 'Hiking_Boots_02', 1, date('now')),
('Hiking_Boots_03', 'Hiking_Boots_03', 1, date('now')),
('Hiking_Boots_04', 'Hiking_Boots_04', 1, date('now')),
('Hippie_pants_01_02', 'Hippie_pants_01_02', 1, date('now')),
('Hippie_pants_01_03', 'Hippie_pants_01_03', 1, date('now')),
('Hippie_pants_01_04', 'Hippie_pants_01_04', 1, date('now')),
('Hippie_pants_02_01', 'Hippie_pants_02_01', 1, date('now')),
('Hippie_Pants_02_02', 'Hippie_Pants_02_02', 1, date('now')),
('Hippie_Pants_02_03', 'Hippie_Pants_02_03', 1, date('now')),
('Hippie_Shirt_02', 'Hippie_Shirt_02', 1, date('now')),
('Holster_Leg_Test', 'Holster_Leg_Test', 1, date('now')),
('Hoodie', 'Hoodie', 1, date('now')),
('Hoodie_02', 'Hoodie_02', 1, date('now')),
('Hoodie_03', 'Hoodie_03', 1, date('now')),
('Hoodie_04', 'Hoodie_04', 1, date('now')),
('Hoodie_05', 'Hoodie_05', 1, date('now')),
('Horror_Goalie_Mask', 'Horror_Goalie_Mask', 1, date('now')),
('Improvised_Pouch', 'Improvised_Pouch', 1, date('now')),
('Improvised_Wooden_Box', 'Improvised_Wooden_Box', 1, date('now')),
('Jeans_01_02', 'Jeans_01_02', 1, date('now')),
('Jeans_01_03', 'Jeans_01_03', 1, date('now')),
('Jeans_02_01', 'Jeans_02_01', 1, date('now')),
('Jeans_02_02', 'Jeans_02_02', 1, date('now')),
('Jeans_02_03', 'Jeans_02_03', 1, date('now')),
('Jeans_02_04', 'Jeans_02_04', 1, date('now')),
('Jeans_02_05', 'Jeans_02_05', 1, date('now')),
('Jeans_02_06', 'Jeans_02_06', 1, date('now')),
('Jeans_02_07', 'Jeans_02_07', 1, date('now')),
('Jeans_02_08', 'Jeans_02_08', 1, date('now')),
('Jeans_02_09', 'Jeans_02_09', 1, date('now')),
('Jeans_Jacket', 'Jeans_Jacket', 1, date('now')),
('Jersey_02', 'Jersey_02', 1, date('now')),
('Jersey_04', 'Jersey_04', 1, date('now')),
('Jersey_05', 'Jersey_05', 1, date('now')),
('Jersey_06', 'Jersey_06', 1, date('now')),
('Jersey_07', 'Jersey_07', 1, date('now')),
('Jersey_08', 'Jersey_08', 1, date('now')),
('Jersey_09', 'Jersey_09', 1, date('now')),
('Jock_Jacket_02', 'Jock_Jacket_02', 1, date('now')),
('Jock_Jacket_03', 'Jock_Jacket_03', 1, date('now')),
('Juicebox', 'Juicebox', 1, date('now')),
('Leather_Jacket', 'Leather_Jacket', 1, date('now')),
('Leather_Pants', 'Leather_Pants', 1, date('now')),
('Long_Johns', 'Long_Johns', 1, date('now')),
('MA1_Spitfire_01', 'MA1_Spitfire_01', 1, date('now')),
('MA1_Spitfire_02', 'MA1_Spitfire_02', 1, date('now')),
('MA1_Spitfire_03', 'MA1_Spitfire_03', 1, date('now')),
('MA1_Spitfire_04', 'MA1_Spitfire_04', 1, date('now')),
('Marine_Cap_02', 'Marine_Cap_02', 1, date('now')),
('Marine_Cap_03', 'Marine_Cap_03', 1, date('now')),
('Marine_Cap_04', 'Marine_Cap_04', 1, date('now')),
('Marine_Cap_05', 'Marine_Cap_05', 1, date('now')),
('Marine_Cap_06', 'Marine_Cap_06', 1, date('now')),
('Marine_Cap_07', 'Marine_Cap_07', 1, date('now')),
('Marine_Cap_08', 'Marine_Cap_08', 1, date('now')),
('Military_Cap_02', 'Military_Cap_02', 1, date('now')),
('Military_Cap_03', 'Military_Cap_03', 1, date('now')),
('Military_Cap_04', 'Military_Cap_04', 1, date('now')),
('Military_Cap_05', 'Military_Cap_05', 1, date('now')),
('Military_Cap_06', 'Military_Cap_06', 1, date('now')),
('Military_Helmet_02', 'Military_Helmet_02', 1, date('now')),
('Military_Helmet_03', 'Military_Helmet_03', 1, date('now')),
('Military_Helmet_04', 'Military_Helmet_04', 1, date('now')),
('Military_Helmet_05', 'Military_Helmet_05', 1, date('now')),
('Military_Helmet_06', 'Military_Helmet_06', 1, date('now')),
('Military_Helmet_07', 'Military_Helmet_07', 1, date('now')),
('Military_Helmet_08', 'Military_Helmet_08', 1, date('now')),
('Military_Helmet_09', 'Military_Helmet_09', 1, date('now')),
('Military_Pack_Big_Blue', 'Military_Pack_Big_Blue', 1, date('now')),
('Military_Shirt_02', 'Military_Shirt_02', 1, date('now')),
('Military_Shirt_03', 'Military_Shirt_03', 1, date('now')),
('Military_Shirt_04', 'Military_Shirt_04', 1, date('now')),
('Military_Shirt_05', 'Military_Shirt_05', 1, date('now')),
('Military_Shirt_07', 'Military_Shirt_07', 1, date('now')),
('Military_Shirt_08', 'Military_Shirt_08', 1, date('now')),
('MilitaryPants_03', 'MilitaryPants_03', 1, date('now')),
('MilitaryPants_04', 'MilitaryPants_04', 1, date('now')),
('MilitaryPants_05', 'MilitaryPants_05', 1, date('now')),
('MilitaryPants_06', 'MilitaryPants_06', 1, date('now')),
('MilitaryPants_07', 'MilitaryPants_07', 1, date('now')),
('Moonshine', 'Moonshine', 1, date('now')),
('Motorbike_Helmet', 'Motorbike_Helmet', 1, date('now')),
('Muscle_T_Shirt', 'Muscle_T_Shirt', 1, date('now')),
('Neoprene_Face_Mask', 'Neoprene_Face_Mask', 1, date('now')),
('Ninja_Suit', 'Ninja_Suit', 1, date('now')),
('Open_Finger_Gloves_02', 'Open_Finger_Gloves_02', 1, date('now')),
('Open_Finger_Gloves_03', 'Open_Finger_Gloves_03', 1, date('now')),
('Open_Finger_Gloves_04', 'Open_Finger_Gloves_04', 1, date('now')),
('Painkillers_02', 'Painkillers_02', 1, date('now')),
('PainKillers_03', 'PainKillers_03', 1, date('now')),
('Pants_Poop_01', 'Pants_Poop_01', 1, date('now')),
('Pants_Poop_02', 'Pants_Poop_02', 1, date('now')),
('Pants_Poop_03', 'Pants_Poop_03', 1, date('now')),
('Pants_Poop_04', 'Pants_Poop_04', 1, date('now')),
('Pants_Poop_05', 'Pants_Poop_05', 1, date('now')),
('Pants_Poop_06', 'Pants_Poop_06', 1, date('now')),
('Pants_Poop_07', 'Pants_Poop_07', 1, date('now')),
('Parsnips_roots', 'Parsnips_roots', 1, date('now')),
('Police_Belt', 'Police_Belt', 1, date('now')),
('Police_Cap_01', 'Police_Cap_01', 1, date('now')),
('Police_Complet_Test', 'Police_Complet_Test', 1, date('now')),
('Police_Tact_Duty_Vest', 'Police_Tact_Duty_Vest', 1, date('now')),
('Police_Zombie_02_Test', 'Police_Zombie_02_Test', 1, date('now')),
('Police_Zombie_Boots', 'Police_Zombie_Boots', 1, date('now')),
('Police_Zombie_Glove', 'Police_Zombie_Glove', 1, date('now')),
('Police_Zombie_Pants', 'Police_Zombie_Pants', 1, date('now')),
('PotassiumIodide_Pils_02', 'PotassiumIodide_Pils_02', 1, date('now')),
('PotassiumIodide_Pils_03', 'PotassiumIodide_Pils_03', 1, date('now')),
('Puffer_Jacket', 'Puffer_Jacket', 1, date('now')),
('QuinineSulphate_Pils_02', 'QuinineSulphate_Pils_02', 1, date('now')),
('QuinineSulphate_Pils_03', 'QuinineSulphate_Pils_03', 1, date('now')),
('Rare_01', 'Rare_01', 1, date('now')),
('Rare_02', 'Rare_02', 1, date('now')),
('Rare_03', 'Rare_03', 1, date('now')),
('Redneck_Rat', 'Redneck_Rat', 1, date('now')),
('Reflective_Arm_Bands', 'Reflective_Arm_Bands', 1, date('now')),
('Ribwort_plantain', 'Ribwort_plantain', 1, date('now')),
('Round_Sunglasses', 'Round_Sunglasses', 1, date('now')),
('Rucksack', 'Rucksack', 1, date('now')),
('Safety_Helmet', 'Safety_Helmet', 1, date('now')),
('Santa', 'Santa', 1, date('now')),
('Shepherds_Purse', 'Shepherds_Purse', 1, date('now')),
('Shirt_02', 'Shirt_02', 1, date('now')),
('Shirt_03', 'Shirt_03', 1, date('now')),
('Shorts_Pants_02', 'Shorts_Pants_02', 1, date('now')),
('Shorts_Pants_03', 'Shorts_Pants_03', 1, date('now')),
('Shorts_Pants_04', 'Shorts_Pants_04', 1, date('now')),
('Shorts_Pants_05', 'Shorts_Pants_05', 1, date('now')),
('Shorts_Pants_06', 'Shorts_Pants_06', 1, date('now')),
('Shorts_Pants_07', 'Shorts_Pants_07', 1, date('now')),
('Shorts_Pants_08', 'Shorts_Pants_08', 1, date('now')),
('Shorts_Pants_09', 'Shorts_Pants_09', 1, date('now')),
('Shorts_Pants_10', 'Shorts_Pants_10', 1, date('now')),
('Skateboard_Helmet', 'Skateboard_Helmet', 1, date('now')),
('Ski_Coat', 'Ski_Coat', 1, date('now')),
('Small_Leather_Backpack_02', 'Small_Leather_Backpack_02', 1, date('now')),
('Small_Leather_Backpack_03', 'Small_Leather_Backpack_03', 1, date('now')),
('Sneakers_02_02', 'Sneakers_02_02', 1, date('now')),
('Sneakers_02_03', 'Sneakers_02_03', 1, date('now')),
('Sneakers_02_04', 'Sneakers_02_04', 1, date('now')),
('Socks', 'Socks', 1, date('now')),
('Spartan_Helmet', 'Spartan_Helmet', 1, date('now')),
('SpecOps_Helmet', 'SpecOps_Helmet', 1, date('now')),
('Sport_Backpack', 'Sport_Backpack', 1, date('now')),
('Sport_Sunglasses', 'Sport_Sunglasses', 1, date('now')),
('Sweater_02', 'Sweater_02', 1, date('now')),
('Sweater_03', 'Sweater_03', 1, date('now')),
('Sweater_04', 'Sweater_04', 1, date('now')),
('Sweater_05', 'Sweater_05', 1, date('now')),
('Swimsuit_cap', 'Swimsuit_cap', 1, date('now')),
('T_Shirt', 'T_Shirt', 1, date('now')),
('Tactical_Gloves_02', 'Tactical_Gloves_02', 1, date('now')),
('Tactical_Gloves_03', 'Tactical_Gloves_03', 1, date('now')),
('Tactical_Gloves_04', 'Tactical_Gloves_04', 1, date('now')),
('Tactical_Gloves_05', 'Tactical_Gloves_05', 1, date('now')),
('Tactical_Gloves_06', 'Tactical_Gloves_06', 1, date('now')),
('Tactical_Gloves_07', 'Tactical_Gloves_07', 1, date('now')),
('Tactical_Gloves_08', 'Tactical_Gloves_08', 1, date('now')),
('Tactical_Gloves_09', 'Tactical_Gloves_09', 1, date('now')),
('Tactical_Jacket_02', 'Tactical_Jacket_02', 1, date('now')),
('Tactical_Jacket_03', 'Tactical_Jacket_03', 1, date('now')),
('Tactical_Jacket_04', 'Tactical_Jacket_04', 1, date('now')),
('Tactical_Jacket_05', 'Tactical_Jacket_05', 1, date('now')),
('Tactical_Jacket_06', 'Tactical_Jacket_06', 1, date('now')),
('Tactical_Jacket_07', 'Tactical_Jacket_07', 1, date('now')),
('Tactical_Jacket_08', 'Tactical_Jacket_08', 1, date('now')),
('Tactical_Jacket_09', 'Tactical_Jacket_09', 1, date('now')),
('Tactical_Military_Pants', 'Tactical_Military_Pants', 1, date('now')),
('Tactical_Shirt', 'Tactical_Shirt', 1, date('now')),
('Tactical_Sunglasses', 'Tactical_Sunglasses', 1, date('now')),
('Tactical_Sweater_02', 'Tactical_Sweater_02', 1, date('now')),
('Tactical_Sweater_03', 'Tactical_Sweater_03', 1, date('now')),
('Tactical_Sweater_04', 'Tactical_Sweater_04', 1, date('now')),
('Tactical_Sweater_05', 'Tactical_Sweater_05', 1, date('now')),
('Tactical_Sweater_06', 'Tactical_Sweater_06', 1, date('now')),
('Tactical_Sweater_07', 'Tactical_Sweater_07', 1, date('now')),
('Tactical_Sweater_08', 'Tactical_Sweater_08', 1, date('now')),
('Test_Bandage', 'Test_Bandage', 1, date('now')),
('TEST_Morph_Backpack', 'TEST_Morph_Backpack', 1, date('now')),
('TestBackpack', 'TestBackpack', 1, date('now')),
('Tracksuit_Pants_01_02', 'Tracksuit_Pants_01_02', 1, date('now')),
('Tracksuit_Pants_01_03', 'Tracksuit_Pants_01_03', 1, date('now')),
('Tracksuit_Pants_01_04', 'Tracksuit_Pants_01_04', 1, date('now')),
('Tracksuit_Pants_01_05', 'Tracksuit_Pants_01_05', 1, date('now')),
('Tracksuit_Pants_02_01', 'Tracksuit_Pants_02_01', 1, date('now')),
('Tracksuit_Pants_02_02', 'Tracksuit_Pants_02_02', 1, date('now')),
('Tracksuit_Pants_02_03', 'Tracksuit_Pants_02_03', 1, date('now')),
('Tracksuit_Pants_02_04', 'Tracksuit_Pants_02_04', 1, date('now')),
('Tracksuit_Pants_02_05', 'Tracksuit_Pants_02_05', 1, date('now')),
('Tracksuit_Top_01_02', 'Tracksuit_Top_01_02', 1, date('now')),
('Tracksuit_Top_01_03', 'Tracksuit_Top_01_03', 1, date('now')),
('Tracksuit_Top_01_04', 'Tracksuit_Top_01_04', 1, date('now')),
('Tracksuit_Top_01_05', 'Tracksuit_Top_01_05', 1, date('now')),
('Tracksuit_Top_02_01', 'Tracksuit_Top_02_01', 1, date('now')),
('Tracksuit_Top_02_02', 'Tracksuit_Top_02_02', 1, date('now')),
('Tracksuit_Top_02_03', 'Tracksuit_Top_02_03', 1, date('now')),
('Tracksuit_Top_02_04', 'Tracksuit_Top_02_04', 1, date('now')),
('Tracksuit_Top_02_05', 'Tracksuit_Top_02_05', 1, date('now')),
('Travel_Sunglasses', 'Travel_Sunglasses', 1, date('now')),
('Trucker_Jacket_02', 'Trucker_Jacket_02', 1, date('now')),
('Trucker_Jacket_03', 'Trucker_Jacket_03', 1, date('now')),
('Trucker_Jacket_04', 'Trucker_Jacket_04', 1, date('now')),
('Uncommon_01', 'Uncommon_01', 1, date('now')),
('Uncommon_02', 'Uncommon_02', 1, date('now')),
('Uncommon_03', 'Uncommon_03', 1, date('now')),
('Underwear', 'Underwear', 1, date('now')),
('V_mask', 'V_mask', 1, date('now')),
('VeryRare_01', 'VeryRare_01', 1, date('now')),
('VeryRare_02', 'VeryRare_02', 1, date('now')),
('VeryRare_03', 'VeryRare_03', 1, date('now')),
('Vest_01_02', 'Vest_01_02', 1, date('now')),
('Vest_01_03', 'Vest_01_03', 1, date('now')),
('Vest_01_04', 'Vest_01_04', 1, date('now')),
('Vest_01_05', 'Vest_01_05', 1, date('now')),
('VIP_Stab_Proof_Vest', 'VIP_Stab_Proof_Vest', 1, date('now')),
('Waist_Bag_Large', 'Waist_Bag_Large', 1, date('now')),
('Waist_Bag_Small_02', 'Waist_Bag_Small_02', 1, date('now')),
('Waist_Bag_Small_03', 'Waist_Bag_Small_03', 1, date('now')),
('Wellingtons', 'Wellingtons', 1, date('now')),
('White_Mustard', 'White_Mustard', 1, date('now')),
('WifeBeaterShirt', 'WifeBeaterShirt', 1, date('now')),
('Winter_Beanie', 'Winter_Beanie', 1, date('now')),
('Winter_Boots', 'Winter_Boots', 1, date('now')),
('Winter_Gloves', 'Winter_Gloves', 1, date('now')),
('Winter_Hat', 'Winter_Hat', 1, date('now')),
('Woodcutter_Shirt_02', 'Woodcutter_Shirt_02', 1, date('now')),
('Woodcutter_Shirt_03', 'Woodcutter_Shirt_03', 1, date('now')),
('Work_Jacket_02', 'Work_Jacket_02', 1, date('now')),
('Work_Jacket_03', 'Work_Jacket_03', 1, date('now')),
('Working_Boots', 'Working_Boots', 1, date('now')),
('Working_Gloves', 'Working_Gloves', 1, date('now')),
('Working_pants_02', 'Working_pants_02', 1, date('now')),
('Working_pants_03', 'Working_pants_03', 1, date('now')),
('WorkPants_01', 'WorkPants_01', 1, date('now')),
('WorkPants_02', 'WorkPants_02', 1, date('now')),
('WorkPants_03', 'WorkPants_03', 1, date('now')),
('WW2_US_Helmet', 'WW2_US_Helmet', 1, date('now')),
('Zombie_Boonie_Hat_14', 'Zombie_Boonie_Hat_14', 1, date('now')),
('Zombie_Boonie_Hat_15', 'Zombie_Boonie_Hat_15', 1, date('now')),
('Zombie_Jeans_02_01', 'Zombie_Jeans_02_01', 1, date('now')),
('Zombie_Jeans_02_03', 'Zombie_Jeans_02_03', 1, date('now')),
('Zombie_Jeans_02_06', 'Zombie_Jeans_02_06', 1, date('now')),
('Zombie_Jeans_02_08', 'Zombie_Jeans_02_08', 1, date('now')),
('Zombie_Tracksuit_Top_01_03', 'Zombie_Tracksuit_Top_01_03', 1, date('now')),
('Zombie_Tracksuit_Top_02_01', 'Zombie_Tracksuit_Top_02_01', 1, date('now')),
('Zombie_Vest_01_02', 'Zombie_Vest_01_02', 1, date('now')),
('Zombie_Working_pants_02', 'Zombie_Working_pants_02', 1, date('now')),
('Zombie_Working_pants_03', 'Zombie_Working_pants_03', 1, date('now')),
('Zombie_WorkPants', 'Zombie_WorkPants', 1, date('now'));
