
insert into "Items" ("Name", "Code", "Active", "CreateDate") values
('true9truetrue silver', 'true9truetrue', true, date('now')),
('Grenade 40 Mm', '40mm_G', true, date('now')),
('Shotgun Ammunition Box closed', 'true2_Gauge_Ammobox_Closed', true, date('now')),
('Shotgun Shell - Empty', 'true2_Gauge_Catrige', true, date('now')),
('Shotgun Ammunition Box open', 'true2_Gauge_Ammobox_Opentrue', true, date('now')),
('true2 Gauge Shell', 'true2_Gauge', true, date('now')),
('Pitchfork', '2H_Pitchfork', true, date('now')),
('Shovel', '2H_Shovel_02', true, date('now')),
('Pickaxe', '2H_Pickaxe', true, date('now')),
('Katana', '2H_Katana', true, date('now')),
('Baseball Bat with spikes', '2H_Baseball_Bat_with_spikes', true, date('now')),
('Baseball Bat with wire', '2H_Baseball_Bat_with_wire', true, date('now')),
('Stone Axe', '2H_Stone_Axe', true, date('now')),
('Pitchfork Bent', '2H_Pitchfork_Bent', true, date('now')),
('Baseball Bat', '2H_Baseball_Bat', true, date('now')),
('Improvised shovel', '2H_Improvised_shovel', true, date('now')),
('Metal Baseball Bat', '2H_Metal_Baseball_Bat', true, date('now')),
('Wooden Sword', '2H_Wooden_Sword', true, date('now')),
('Stone Axe Head', '2H_Stone_Axe_Head', true, date('now')),
('Metal Axe', '2H_Metal_Axe', true, date('now')),
('Spade Shovel', '2H_Shovel_0true', true, date('now')),
('Ax', '2H_Axe', true, date('now')),
('Hunter', 'trueH_Hunter', true, date('now')),
('Stone Axe Head', 'trueH_Stone_Axe_Head', true, date('now')),
('Improvised Hammer', 'trueH_Improvised_Hammer', true, date('now')),
('Kitchen Knife', 'trueH_KitchenKnife', true, date('now')),
('N9 Bayonet', 'trueH_N9_White', true, date('now')),
('Cleaver', 'trueH_Cleaver', true, date('now')),
('Stone Axe', 'trueH_Stone_Axe', true, date('now')),
('Kitchen Knife', 'trueH_KitchenKnife_04', true, date('now')),
('Crowbar', 'trueH_Crowbar', true, date('now')),
('Metal Knife', 'trueH_Improvised_metal_knife', true, date('now')),
('Kunai', 'trueH_Kunai', true, date('now')),
('MK5000 black', 'trueH_MK5000_Black', true, date('now')),
('Bushman', 'trueH_Bushman', true, date('now')),
('Improvised Hatchet', 'trueH_Hatchet', true, date('now')),
('Police Baton', 'trueH_Police_Baton', true, date('now')),
('Mk5000', 'trueH_MK5000_Metal', true, date('now')),
('Brass Knuckles', 'trueH_Brass_knuckles', true, date('now')),
('Scout White', 'trueH_Scout_White', true, date('now')),
('Metal Sword', 'trueH_Metal_Sword', true, date('now')),
('Shuriken', 'trueH_Shuriken', true, date('now')),
('Stone Knife', 'trueH_ImprovisedKnife', true, date('now')),
('Wooden club', 'trueH_Wooden_club', true, date('now')),
('Wrench Pipe', 'trueH_Wrench_Pipe', true, date('now')),
('N9 Bayonet', 'trueH_N9_Black_trueh_Melee', true, date('now')),
('Small Spade', 'trueH_Little_Spade', true, date('now')),
('Scout Black', 'trueH_Scout_Black', true, date('now')),
('N9 Bayonet', 'trueH_N9_Black', true, date('now')),
('Kitchen Knife', 'trueH_KitchenKnife_03', true, date('now')),
('Scalpel', 'trueH_Scalpel', true, date('now')),
('Kitchen Knife', 'trueH_KitchenKnife_02', true, date('now')),
('Wooden club with spikes', 'trueH_Wooden_club_with_spikes', true, date('now')),
('Wooden club with wire', 'trueH_Wooden_club_with_wire', true, date('now')),
('Small Meat Skewer', 'Skewer_Meat_small', true, date('now')),
('Chop_Horse_Skinned', 'Chop_Horse_Skinned', true, date('now')),
('Cabbage', 'Cabbage', true, date('now')),
('Zombie_Jeans_0true_02', 'Zombie_Jeans_0true_02', true, date('now')),
('Magazine_DEagle_50', 'Magazine_DEagle_50', true, date('now')),
('Coconut', 'Coconut', true, date('now')),
('Chop_Debree_Log_Big', 'Chop_Debree_Log_Big', true, date('now')),
('Smoke_Dry_food', 'Smoke_Dry_food', true, date('now')),
('Human Arm', 'Prisoner_Right_Arm', true, date('now')),
('Fish Trap', 'Fish_trap', true, date('now')),
('Cartridge Sleeve 7.62 × 39 Mm', 'Cal7_62x39mm_Empty', true, date('now')),
('Pie', 'Pate_02', true, date('now')),
('Chop_Tree_03', 'Chop_Tree_03', true, date('now')),
('Zombie_0true_Right_Leg', 'Zombie_0true_Right_Leg', true, date('now')),
('Ammunition Box .45 Acp', 'Cal45_AmmoboxOpen', true, date('now')),
('Vegetable Oil', 'VegetableOil', true, date('now')),
('antipsychotic Pils', 'antipsychotic_Pils', true, date('now')),
('Salted Fish', 'Salted_fish_0true', true, date('now')),
('Ak-74 (aks)', 'AK-74', true, date('now')),
('Chop_Wolf', 'Chop_Wolf', true, date('now')),
('Spoon', 'Spoon', true, date('now')),
('Stones', 'SearchForRocks', true, date('now')),
('Caramel Shower', 'PETBottle02', true, date('now')),
('Chop_Tinder_LWS', 'Chop_Tinder_LWS', true, date('now')),
('Grapefruit', 'GrapeFruit', true, date('now')),
('Donkey Hull', 'Donkey_Torso', true, date('now')),
('Cartridge 9 Mm', 'Cal_9mm_5_Bullets', true, date('now')),
('Holzgabel', 'Wooden_Fork', true, date('now')),
('Chop_Chicken_Torso', 'Chop_Chicken_Torso', true, date('now')),
('Onion Rings', 'Chips3', true, date('now')),
('Car Battery Cable', 'Car_Battery_Cables', true, date('now')),
('Slice_Clothes_0true', 'Slice_Clothes_0true', true, date('now')),
('Pantherpilz', 'Amanita_Pantheria', true, date('now')),
('Weapon_98k_Karabiner', 'Weapon_98k_Karabiner', true, date('now')),
('Pigeon Breasts', 'Pigeon_Breasts', true, date('now')),
('Chop_Crow', 'Chop_Crow', true, date('now')),
('Chocolate Toaster Pastries', 'Toaster_Pastries2', true, date('now')),
('Scrap Metal', 'Metal_Scrap_03', true, date('now')),
('Jersey Shirt', 'Zombie_Jersey_02', true, date('now')),
('Cooked Vegetables', 'CookVegetables2', true, date('now')),
('Bubbles', 'Can03', true, date('now')),
('Grapefruit Juice', 'GlassBottle02', true, date('now')),
('Chop_Destroy_Improvised_Metal_Chest', 'Chop_Destroy_Improvised_Metal_Chest', true, date('now')),
('Pine Cones', 'Pine_Cone', true, date('now')),
('Veal Steak', 'Veal_Steak', true, date('now')),
('Animal Skin', 'Animal_skin', true, date('now')),
('Army Glasses', 'Military_Goggles', true, date('now')),
('Night_Vision', 'Night_Vision', true, date('now')),
('Chillies', 'Chilipeper', true, date('now')),
('Electrician`s Tool', 'Electrician_Tools', true, date('now')),
('Bait Trap For Small Animals', 'Bait_trap_for_small_animals', true, date('now')),
('Zombie_Work_Jacket_02', 'Zombie_Work_Jacket_02', true, date('now')),
('Animal Fat', 'Small_Animal_Fat', true, date('now')),
('9mm Ammunition Box', 'Cal_9mm_AmmoboxOpen', true, date('now')),
('Spitfire Jacket', 'Zombie_College_Jacket_05', true, date('now')),
('Skewer_Sausages_small', 'Skewer_Sausages_small', true, date('now')),
('Sledgehammer', 'Sledgehammer', true, date('now')),
('Burger Bun', 'Burger_PATTIES', true, date('now')),
('Ak47_Strap_For_Holster', 'Ak47_Strap_For_Holster', true, date('now')),
('Celery', 'Celery', true, date('now')),
('Chop_Swan', 'Chop_Swan', true, date('now')),
('Chop_Destroy', 'Chop_Destroy', true, date('now')),
('Wolf Leg', 'Wolf_Left_Back_Leg', true, date('now')),
('Skewer', 'Skewer_Meat', true, date('now')),
('Zombie_Raincoat_Up_04', 'Zombie_Raincoat_Up_04', true, date('now')),
('Chop_Tree_02', 'Chop_Tree_02', true, date('now')),
('Chocolate', 'ChocolateCandy_07', true, date('now')),
('true M Wire', 'Wire', true, date('now')),
('Rehbein', 'Doe_Right_Back_Leg', true, date('now')),
('Torch', 'Torch', true, date('now')),
('Flannel Shirt', 'Zombie_Woodcutter_Shirt_0true', true, date('now')),
('Cake', 'Cake', true, date('now')),
('Baseball Cap', 'Zombie_Baseball_Cap_true2', true, date('now')),
('Soldiers-shirt', 'Zombie_Military_Shirt_02', true, date('now')),
('Blueberries', 'Blueberries', true, date('now')),
('Cannon Ammunition Container', 'Cal20mm_Empty', true, date('now')),
('Chop_Human_Limb', 'Chop_Human_Limb', true, date('now')),
('Zombie_Shirt_03', 'Zombie_Shirt_03', true, date('now')),
('Cheese', 'Cheese', true, date('now')),
('Branches Of A Shrub', 'Bush_Branches', true, date('now')),
('Fried Egg', 'Fried_Egg_0true', true, date('now')),
('Weapon_Hunter85', 'Weapon_Hunter85', true, date('now')),
('Soup', 'Soup_02', true, date('now')),
('Canned Corn', 'Canned_Corn', true, date('now')),
('UI_ClockFaceWidget', 'UI_ClockFaceWidget', true, date('now')),
('Currant', 'Currant', true, date('now')),
('Fishing Rod', 'Fishing_rod', true, date('now')),
('Cal_357_truepcs', 'Cal_357_truepcs', true, date('now')),
('Cigarettes "lucky Star"', 'Cigarettestrue', true, date('now')),
('Cat Food', 'CannedCatfood', true, date('now')),
('Canned Tuna', 'Canned_Tuna', true, date('now')),
('Spring', 'Spring', true, date('now')),
('Wild Cherry', 'Wild_Cherry', true, date('now')),
('Improvised Compass', 'Improvised_compass', true, date('now')),
('Human Hull', 'Prisoner_Torso', true, date('now')),
('Carrot Juice', 'GlassBottle0true', true, date('now')),
('Right Rabbit Fore-piece', 'Rabbit_Right_Front', true, date('now')),
('Dietrich', 'Lockpick', true, date('now')),
('Bundle Of Rags', 'Bundle_Of_Rags', true, date('now')),
('Matches', 'Matches', true, date('now')),
('Ammunition Box 7.92 X 57 Mm', 'Cal_7_92x57mm_AmmoboxOpen', true, date('now')),
('Flames Defense Shield', 'Fire_deflector_shield', true, date('now')),
('Barberry', 'Barberry', true, date('now')),
('Oysters', 'Oysters', true, date('now')),
('Scissors', 'Scissors_0true', true, date('now')),
('Barrel With Salted Mutton', 'Salted_meat_barrel_0true', true, date('now')),
('Spaghetti Bolognese', 'Spaghetti_Bolognese', true, date('now')),
('Wild Steak', 'Deer_Steak', true, date('now')),
('Half Bear Hull', 'Bear_Left_Torso_Half', true, date('now')),
('Chop_Goat', 'Chop_Goat', true, date('now')),
('Chop_Horse_Torso_Half', 'Chop_Horse_Torso_Half', true, date('now')),
('Cricket', 'Cricket', true, date('now')),
('Piece Of Rubber', 'Rubber_sheet', true, date('now')),
('Parachute', 'Parachute', true, date('now')),
('Black Pepper', 'BlackPepper', true, date('now')),
('Chop_Doe_Skinned', 'Chop_Doe_Skinned', true, date('now')),
('Absinthe "father"', 'Absinthe', true, date('now')),
('Ammunition Box 5.45 × 39 Mm', 'Cal_5_45x39_AmmoboxClosed', true, date('now')),
('Baked Meat', 'Baked_meat', true, date('now')),
('Pilot Jacket', 'Zombie_MAtrue_Spitfire_02', true, date('now')),
('Logs', 'Wooden_Log_Small_0true', true, date('now')),
('Firesteel', 'Flint_And_Steel', true, date('now')),
('Lens', 'Camera_Lens', true, date('now')),
('Scorzonera Hispanica', 'Salsify_roots', true, date('now')),
('BerettaM9', 'BerettaM9', true, date('now')),
('Cartridge Caliber .22', 'Cal22_Bullet', true, date('now')),
('Mp5 Magazine', 'Magazine_MP5', true, date('now')),
('Wolf Hull', 'Wolf_Torso', true, date('now')),
('Chop_Chicken', 'Chop_Chicken', true, date('now')),
('Popcorn', 'Popcorn_0true', true, date('now')),
('Bear Paws', 'Bear_Back_Paws', true, date('now')),
('Cartridge .50 Bwg', 'Cal50', true, date('now')),
('Rose Hip', 'Dog_Rose', true, date('now')),
('Small Bunch Of Wooden Sticks', 'Wooden_Sticks_Bundle_Meduim', true, date('now')),
('Pizza', 'Pizza', true, date('now')),
('Joints Of Meat', 'Bird_Legs_Medium', true, date('now')),
('Bear Paws', 'Bear_Front_Paws', true, date('now')),
('Chop_Donkey_Limb_Back', 'Chop_Donkey_Limb_Back', true, date('now')),
('Chop_Rabbit_lIMB', 'Chop_Rabbit_lIMB', true, date('now')),
('Hirsch Hull', 'Buck_Torso', true, date('now')),
('Chop_Wolf_Limbs', 'Chop_Wolf_Limbs', true, date('now')),
('Deagle_357', 'Deagle_357', true, date('now')),
('Event_2H_Baseball_Bat_with_wire', 'Event_2H_Baseball_Bat_with_wire', true, date('now')),
('Zombie_0true_Torso', 'Zombie_0true_Torso', true, date('now')),
('Agaricus Campestris', 'Agaricus_Campestris', true, date('now')),
('Chop_Boar', 'Chop_Boar', true, date('now')),
('Zombie_Driving_Gloves_04', 'Zombie_Driving_Gloves_04', true, date('now')),
('Gimlet', 'Hand_Drill', true, date('now')),
('Chop_Car_Cables', 'Chop_Car_Cables', true, date('now')),
('Nails', 'Nails', true, date('now')),
('Smartphone Battery', 'Smartphone_Battery', true, date('now')),
('Cal_50_AE_5pcs', 'Cal_50_AE_5pcs', true, date('now')),
('Rags', 'Rag_Stripes', true, date('now')),
('Scrap Metal', 'Metal_Scrap_04', true, date('now')),
('Glass', 'Jar', true, date('now')),
('Chop_Tinder_SWS', 'Chop_Tinder_SWS', true, date('now')),
('Zombie_Jock_Jacket_03', 'Zombie_Jock_Jacket_03', true, date('now')),
('Cartridge 7.92 X 57 Mm', 'Cal_7_92x57mm_5_bullets', true, date('now')),
('Hacksaw', 'Saw', true, date('now')),
('Chop_Human', 'Chop_Human', true, date('now')),
('Crab Claw', 'Crab_Right_Pincer', true, date('now')),
('Salted Potato Chips', 'Chips4', true, date('now')),
('Cream', 'Cream', true, date('now')),
('Beetroot', 'Beet', true, date('now')),
('Agaricus Augustus', 'Agaricus_Augustus', true, date('now')),
('Fork', 'Steel_Fork', true, date('now')),
('Pork Steak', 'Pork_Steak', true, date('now')),
('Smoked Rodent Meat', 'Smoked_RodentMeat', true, date('now')),
('Horse`s Rump', 'Horse_Torso', true, date('now')),
('Slice_Clothes_05', 'Slice_Clothes_05', true, date('now')),
('Soda', 'Can0true', true, date('now')),
('Cooking Pot', 'Pottrue', true, date('now')),
('Vitamin Tablets (glass)', 'Vitamins_03', true, date('now')),
('Beanie', 'Zombie_Beenie_02', true, date('now')),
('Wolf Leg', 'Wolf_Right_Back_Leg', true, date('now')),
('Event Improvised Metal Spear', 'Event_Improvised_Metal_Spear', true, date('now')),
('Ziegenkopf', 'Goat_Head', true, date('now')),
('Slice_Rags_Into_Stripes', 'Slice_Rags_Into_Stripes', true, date('now')),
('Bundle_Rag_Stripes', 'Bundle_Rag_Stripes', true, date('now')),
('Souse', 'Salted_meat_02', true, date('now')),
('Chop_Swan_Skinned', 'Chop_Swan_Skinned', true, date('now')),
('5 M Rope', 'Ropetrue', true, date('now')),
('SeaSalt_02', 'SeaSalt_02', true, date('now')),
('Banana', 'Banana', true, date('now')),
('Rabbit Meat', 'RabbitMeat', true, date('now')),
('Take_Page_out_of_diary', 'Take_Page_out_of_diary', true, date('now')),
('Slice_Zombie_Clothes_03', 'Slice_Zombie_Clothes_03', true, date('now')),
('Magazine_DEagle_357', 'Magazine_DEagle_357', true, date('now')),
('Bark Rope', 'Improvised_Plant_rope', true, date('now')),
('Candle', 'Candle_0true', true, date('now')),
('Batteries', 'Batteries', true, date('now')),
('Joints Of Meat', 'Bird_Legs_Large', true, date('now')),
('Cal30-06_Ammobox_Open', 'Cal30-06_Ammobox_Open', true, date('now')),
('Prisoners Shirt', 'Zombie_Inmate_shirt', true, date('now')),
('Cartridge Caliber .22', 'Cal22_Pile_5pcs', true, date('now')),
('People Sausage', 'Human_Sausages_0true', true, date('now')),
('Smoked Dog Steak', 'Smoked_Dog_Steak', true, date('now')),
('Cal7_62x39mm_20_bullets', 'Cal7_62x39mm_20_bullets', true, date('now')),
('Chop_Seagull_Skinned', 'Chop_Seagull_Skinned', true, date('now')),
('Donkey Leg', 'Donkey_Front_Leg', true, date('now')),
('Chop_Bush_03', 'Chop_Bush_03', true, date('now')),
('College Jacket', 'Zombie_Jock_Jacket_0true', true, date('now')),
('Peach', 'Peach', true, date('now')),
('Apple', 'Apple', true, date('now')),
('Green Peas', 'CannedPeas', true, date('now')),
('Salted Fish', 'Salted_fish_02', true, date('now')),
('Plastic Scissors', 'Scissors_Plastic', true, date('now')),
('NightVisionGoggles3_test', 'NightVisionGoggles3_test', true, date('now')),
('Hippie_Pants_02_04', 'Hippie_Pants_02_04', true, date('now')),
('Camouflage Jacket', 'Camouflage_Jacket_0true', true, date('now')),
('Combat Boots', 'CombatBoots', true, date('now')),
('Cotton Hoodie', 'Hoodie_0true', true, date('now')),
('Cotton Shirt', 'Shirt_0true', true, date('now')),
('Croatia Jersey', 'Jersey_03', true, date('now')),
('Auto Gloves', 'Driving_Gloves_0true', true, date('now')),
('Angler', 'Boonie_Hat_0true', true, date('now')),
('Flannel Shirt', 'Woodcutter_Shirt_0true', true, date('now')),
('High-tops', 'Sneakers_02_0true', true, date('now')),
('Hiking Backpack', 'Hiking_Backpack_0true', true, date('now')),
('Walking Boots', 'Hiking_Boots_0true', true, date('now')),
('Hippy Pants', 'Hippie_pants_0true_0true', true, date('now')),
('Bush Hat', 'Boonie_Hat_03', true, date('now')),
('Hippie-shirt', 'Hippie_Shirt_0true', true, date('now')),
('Improvised Backpack', 'Improvised_Backpack_Big', true, date('now')),
('Improvised Boots', 'Improvised_Shoes_0true', true, date('now')),
('Improvised Courier Backpack', 'Improvised_Bag_Small_0true', true, date('now')),
('Santa_Pants', 'Santa_Pants', true, date('now')),
('Prisoners Pants', 'Inmate_pants', true, date('now')),
('Prisoners Shirt', 'Inmate_shirt', true, date('now')),
('Jeans', 'Jeans_0true_0true', true, date('now')),
('Jersey Shirt', 'Jersey_0true', true, date('now')),
('College Jacket', 'Jock_Jacket_0true', true, date('now')),
('Kroks', 'Slippers_0true', true, date('now')),
('Leather Backpack', 'Small_Leather_Backpack_0true', true, date('now')),
('Tarnfleck Hiking Backpack', 'Camo_Backpack_0true', true, date('now')),
('Bee Pollen Pills', 'BeePollen_Pils_0true', true, date('now')),
('Leather Shoes', 'Leather_Shoes', true, date('now')),
('Animal Skin Jacket', 'Bear_Improvised_Jacket', true, date('now')),
('DEagle_50Gold', 'DEagle_50Gold', true, date('now')),
('Ak47 Magazine', 'Magazine_AK47', true, date('now')),
('Chop_Goat_Limb_Front', 'Chop_Goat_Limb_Front', true, date('now')),
('Zombie_Jeans_0true_03', 'Zombie_Jeans_0true_03', true, date('now')),
('Slice_Zombie_Clothes_04', 'Slice_Zombie_Clothes_04', true, date('now')),
('Chop_Bush_0true', 'Chop_Bush_0true', true, date('now')),
('Chop_Destroy_Wooden_Chest', 'Chop_Destroy_Wooden_Chest', true, date('now')),
('Bear Leg', 'Bear_Right_Front_Leg', true, date('now')),
('MeatSnack_02', 'MeatSnack_02', true, date('now')),
('Bear Leg', 'Bear_Right_Back_Leg', true, date('now')),
('Wurfpieß', 'Javelin', true, date('now')),
('Activated Carbon', 'ActivatedCharcoal_0true', true, date('now')),
('Animal Skin Pants', 'Bear_Improvised_Pants', true, date('now')),
('Bear Boots', 'Bear_Shoe', true, date('now')),
('Anti-radiation Pills', 'Anti_Radiation_Pils_0true', true, date('now')),
('Antibiotics', 'Antibiotics_0true', true, date('now')),
('Anti-malarial Pills', 'AntiMalariaPils_0true', true, date('now')),
('Antiparasitic', 'Antiparasitics_0true', true, date('now')),
('Assault Backpack', 'Backpack_0true_0true', true, date('now')),
('Backpack', 'Backpack_02_0true', true, date('now')),
('Balaclava', 'Beenie_3_hole_0true', true, date('now')),
('Baseball Cap', 'Baseball_Cap_0true', true, date('now')),
('Santa_Hat', 'Santa_Hat', true, date('now')),
('Beanie', 'Beenie_0true', true, date('now')),
('Bear Gloves', 'Bear_Pow', true, date('now')),
('Bear Head Cap', 'Bear_Head_Cap', true, date('now')),
('Leather Jacket', 'Jacket_0true', true, date('now')),
('Marine Cap', 'Marine_Cap_0true', true, date('now')),
('Horse`s Leg', 'Horse_Back_Limb', true, date('now')),
('Sniper', 'SnipingSkill', true, date('now')),
('Rags Footwear', 'Improvised_Shoe_02', true, date('now')),
('Slicker', 'Raincoat_Down_0true', true, date('now')),
('Respirator', 'Respirator_0true', true, date('now')),
('Rifles', 'RiflesSkill', true, date('now')),
('Helmet Use', 'Fireman_Helmet_0true', true, date('now')),
('Improvised_Stabproof', 'Improvised_Stabproof', true, date('now')),
('Einsatzweste', 'Stabproof_Vest_05', true, date('now')),
('Satchel', 'School_Backpack_boy_0true', true, date('now')),
('Shirt', 'Military_Shirt_06', true, date('now')),
('Shorts', 'Shorts_Pants_0true', true, date('now')),
('Small Improvised Backpack', 'Improvised_Bag_Small_02', true, date('now')),
('Spitfire Jacket', 'College_Jacket_0true', true, date('now')),
('Quinine Sulfate Tablets', 'QuinineSulphate_Pils_0true', true, date('now')),
('Training Pants', 'Tracksuit_Pants_0true_0true', true, date('now')),
('Tactical Gloves', 'Tactical_Gloves_0true', true, date('now')),
('Santa_Jacket', 'Santa_Jacket', true, date('now')),
('Tactical Jacket', 'Tactical_Jacket_0true', true, date('now')),
('Tactical Army Pants', 'MilitaryPants_02', true, date('now')),
('Tactical Sweater', 'Tactical_Sweater_0true', true, date('now')),
('Training Jacket', 'Tracksuit_Top_0true_0true', true, date('now')),
('Sneakers', 'HighTop_Shoes', true, date('now')),
('Trucker Jacket', 'Trucker_Jacket_0true', true, date('now')),
('Hüfttasche', 'Waist_Bag_Small_0true', true, date('now')),
('Wool Sweater', 'Sweater_0true', true, date('now')),
('Work Jacket', 'Work_Jacket_0true', true, date('now')),
('Rags Footwear', 'Zombie_Improvised_Shoe_02', true, date('now')),
('Potassium Iodide Pills', 'PotassiumIodide_Pils_0true', true, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_0true', true, date('now')),
('Night_Vision_Helmet_Down_08', 'Night_Vision_Helmet_Down_08', true, date('now')),
('MilitaryBoots JNA', 'MilitaryBoots_JNA', true, date('now')),
('Night_Vision_Googles', 'Night_Vision_Googles', true, date('now')),
('Soldier`s Cap', 'Military_Cap_0true', true, date('now')),
('Night_Vision_Helmet_Up_06', 'Night_Vision_Helmet_Up_06', true, date('now')),
('Night_Vision_Helmet_Up_03', 'Night_Vision_Helmet_Up_03', true, date('now')),
('Night_Vision_Helmet_Up_08', 'Night_Vision_Helmet_Up_08', true, date('now')),
('Night_Vision_Helmet_Down_05', 'Night_Vision_Helmet_Down_05', true, date('now')),
('Night_Vision_Helmet_Up_02', 'Night_Vision_Helmet_Up_02', true, date('now')),
('Night_Vision_Helmet_Down_06', 'Night_Vision_Helmet_Down_06', true, date('now')),
('Night_Vision_Helmet_Up_05', 'Night_Vision_Helmet_Up_05', true, date('now')),
('Night_Vision_Helmet_Down_09', 'Night_Vision_Helmet_Down_09', true, date('now')),
('Night_Vision_Helmet_Down_04', 'Night_Vision_Helmet_Down_04', true, date('now')),
('Night_Vision_Helmet_Up_07', 'Night_Vision_Helmet_Up_07', true, date('now')),
('Police Body Armor', 'Stabproof_Vest_0true', true, date('now')),
('Night_Vision_Helmet_Up_04', 'Night_Vision_Helmet_Up_04', true, date('now')),
('Night_Vision_Helmet_Up_0true', 'Night_Vision_Helmet_Up_0true', true, date('now')),
('Night_Vision_Helmet_Up_09', 'Night_Vision_Helmet_Up_09', true, date('now')),
('Night_Vision_Helmet_Down_07', 'Night_Vision_Helmet_Down_07', true, date('now')),
('Night_Vision_Helmet_Down_02', 'Night_Vision_Helmet_Down_02', true, date('now')),
('Night_Vision_Helmet_Down_0true', 'Night_Vision_Helmet_Down_0true', true, date('now')),
('Night_Vision_Helmet_Down_03', 'Night_Vision_Helmet_Down_03', true, date('now')),
('Soldier Helmet', 'Military_Helmet_0true', true, date('now')),
('Soldiers-shirt', 'Military_Shirt_0true', true, date('now')),
('Mma Gloves', 'MMA_Glove', true, date('now')),
('Fingerless Gloves', 'Open_Finger_Gloves_0true', true, date('now')),
('Painkillers', 'Painkillers_0true', true, date('now')),
('Watermelon Slice', 'Watermelon_slice', true, date('now')),
('Kitchen Board', 'Kitchen_Board_0true', true, date('now')),
('Chop_Bush_02', 'Chop_Bush_02', true, date('now')),
('Razor_Blade', 'Razor_Blade', true, date('now')),
('Chop_Pigeon', 'Chop_Pigeon', true, date('now')),
('Smoked Bird Meat', 'Smoked_BirdMeat', true, date('now')),
('Slice_Clothes_03', 'Slice_Clothes_03', true, date('now')),
('Chop_Boar_Skinned', 'Chop_Boar_Skinned', true, date('now')),
('Cereal UpNGo', 'Cereal_UpNGo', true, date('now')),
('Zombie_Police_Cap_0true', 'Zombie_Police_Cap_0true', true, date('now')),
('Chop_Rat_Torso', 'Chop_Rat_Torso', true, date('now')),
('Zombie_Baseball_Cap_true8', 'Zombie_Baseball_Cap_true8', true, date('now')),
('Ammunition Box Caliber .22', 'Cal22_Ammobox_Closed', true, date('now')),
('Zombie_0true_Right_Arm', 'Zombie_0true_Right_Arm', true, date('now')),
('Riot_Helmet2', 'Riot_Helmet2', true, date('now')),
('Cartridge 7.92 X 57 Mm', 'Cal_7_92x57mm_Bullet', true, date('now')),
('Pie', 'Pate_0true', true, date('now')),
('Helmet Use', 'Riot_Helmet', true, date('now')),
('Egg', 'Egg', true, date('now')),
('Mango', 'Mango', true, date('now')),
('Chop_Log_Big', 'Chop_Log_Big', true, date('now')),
('Sodium Hydroxide', 'Sodium_Hydroxide', true, date('now')),
('Frag Grenade', 'Frag_Grenade', true, date('now')),
('Skinned Deer', 'Doe_Skinned', true, date('now')),
('Chop_Rabbit', 'Chop_Rabbit', true, date('now')),
('Chop_Destroy_Improved_Wooden_Chest', 'Chop_Destroy_Improved_Wooden_Chest', true, date('now')),
('Zombie_0true_Right_Foot', 'Zombie_0true_Right_Foot', true, date('now')),
('Chop_Horse_Torso', 'Chop_Horse_Torso', true, date('now')),
('Cartridge 7.62 × 54 Mm R', 'Cal7_62x54mmR_5_bullets', true, date('now')),
('Ammunition Box 7.92 X 57 Mm', 'Cal_7_92x57mm_AmmoboxClosed', true, date('now')),
('Chop_Zombie_Limb', 'Chop_Zombie_Limb', true, date('now')),
('Steak With Potatoes', 'Steak_With_Potatoes_02', true, date('now')),
('Half Horse Swamp', 'Horse_Torso_Half', true, date('now')),
('Marine Cap', 'Zombie_Marine_Cap_0true', true, date('now')),
('Tactical Army Pants', 'Zombie_MilitaryPants_02', true, date('now')),
('Rehbein', 'Doe_Left_Back_Leg', true, date('now')),
('Smoked Goose Meat', 'Smoked_GooseMeat', true, date('now')),
('Prisoners Pants', 'Zombie_Inmate_pants', true, date('now')),
('Orange Juice', 'Can02', true, date('now')),
('Tin', 'CannedFood2', true, date('now')),
('Bear Hull', 'Bear_Torso', true, date('now')),
('Chop_Debree_Log_Big_02', 'Chop_Debree_Log_Big_02', true, date('now')),
('Wolf Leg', 'Wolf_Right_Front_Leg', true, date('now')),
('Right Rabbit Spine Piece', 'Rabbit_Right_Back', true, date('now')),
('Boar Leg', 'Boar_Back_Leg', true, date('now')),
('Bean Stew', 'Beans_Stew_0true', true, date('now')),
('Bark', 'Tree_Bark', true, date('now')),
('Bone Needle', 'Bone_Needle', true, date('now')),
('Chop_Donkey_Skinned', 'Chop_Donkey_Skinned', true, date('now')),
('Toadstool', 'Amanita_Muscaria', true, date('now')),
('Fingerless Gloves', 'Zombie_Open_Finger_Gloves_0true', true, date('now')),
('0_Empty', '0_Empty', true, date('now')),
('Slice_Clothes_04', 'Slice_Clothes_04', true, date('now')),
('Wolf Steak', 'Wolf_Steak', true, date('now')),
('Stew', 'Stewtrue', true, date('now')),
('Olive', 'Olives', true, date('now')),
('Human Foot', 'Prisoner_Left_Foot', true, date('now')),
('Mp5', 'Weapon_MP5', true, date('now')),
('Deagle 50', 'Deagle_50', true, date('now')),
('Plucked Chicken', 'Hen_Torso', true, date('now')),
('Hot Nachos', 'Chips2', true, date('now')),
('Chop_Long_Wooden_Stick', 'Chop_Long_Wooden_Stick', true, date('now')),
('Marine Cap', 'Zombie_Marine_Cap_06', true, date('now')),
('Horse Steak', 'Horse_Steak', true, date('now')),
('Donkey Leg', 'Donkey_Back_Leg', true, date('now')),
('Butter', 'Butter', true, date('now')),
('Crab Hull', 'Crab_Torso', true, date('now')),
('Ring Of Fire', 'Fireplacetrue', true, date('now')),
('Improved_Wooden_Chest', 'Improved_Wooden_Chest', true, date('now')),
('Bag of Almonds', 'Bag_of_Almonds', true, date('now')),
('Zombie_MAtrue_Spitfire_04', 'Zombie_MAtrue_Spitfire_04', true, date('now')),
('Pelinkovac', 'Pelinkovac', true, date('now')),
('Rehrumpf', 'Doe_Torso', true, date('now')),
('Bone', 'Bone', true, date('now')),
('Deer Head', 'Buck_Head', true, date('now')),
('Cooked Vegetables', 'BakeVegetables2', true, date('now')),
('Chop_Deer_Torso', 'Chop_Deer_Torso', true, date('now')),
('Chop_Rabbit_Skinned', 'Chop_Rabbit_Skinned', true, date('now')),
('Skinned Horse', 'Horse_Skinned', true, date('now')),
('Crab Claw', 'Crab_Left_Pincer', true, date('now')),
('Cartridge 7.92 X 57 Mm', 'Cal_7_92x57mm', true, date('now')),
('Chocolate Bar', 'ChocolateCandy_0true', true, date('now')),
('Zombie_0true_Left_Leg', 'Zombie_0true_Left_Leg', true, date('now')),
('Chop_Bear_Limbs', 'Chop_Bear_Limbs', true, date('now')),
('Make_Rag_Stripes', 'Make_Rag_Stripes', true, date('now')),
('Cal_5_45x39_5_pcs', 'Cal_5_45x39_5_pcs', true, date('now')),
('Cal30-06', 'Cal30-06', true, date('now')),
('Chop_Pigeon_Skinned', 'Chop_Pigeon_Skinned', true, date('now')),
('Souse', 'Salted_meat_0true', true, date('now')),
('Sunflower Seeds', 'Sunflower_Seeds', true, date('now')),
('Chop_Bear_Torso', 'Chop_Bear_Torso', true, date('now')),
('Chop_Bear_Torso_Half', 'Chop_Bear_Torso_Half', true, date('now')),
('Barrel', 'Barrel', true, date('now')),
('Wool Sweater', 'Zombie_Sweater_03', true, date('now')),
('Smoker', 'Smoker_02', true, date('now')),
('Glasses', 'Geek_Goggels', true, date('now')),
('Chop_Goat_Torso', 'Chop_Goat_Torso', true, date('now')),
('Tipi', 'Tepee', true, date('now')),
('Boar Leg', 'Boar_Front_Leg', true, date('now')),
('Toolbox', 'Tool_Box', true, date('now')),
('Vitamin Tablets (blister)', 'Vitamins_0true', true, date('now')),
('Ammunition Box 7,62 × 54 Mm R', 'Cal7_62x54mmR_Ammobox_Closed', true, date('now')),
('Chop_Bear', 'Chop_Bear', true, date('now')),
('Bear Steak', 'Bear_Steak', true, date('now')),
('Rag', 'Ragstrue', true, date('now')),
('Tactical Army Pants', 'Zombie_MilitaryPants_06', true, date('now')),
('SpicesMix_02', 'SpicesMix_02', true, date('now')),
('Bolt', 'Bolts', true, date('now')),
('Fingerless Gloves', 'Zombie_Open_Finger_Gloves_02', true, date('now')),
('Hirschbein', 'Buck_Right_Back_Leg', true, date('now')),
('Toast', 'Toast', true, date('now')),
('Chop_Boar_Limbs', 'Chop_Boar_Limbs', true, date('now')),
('Slice_Zombie_Clothes_05', 'Slice_Zombie_Clothes_05', true, date('now')),
('Cooked Pasta', 'Cooked_Pasta_0true', true, date('now')),
('Glass', 'Jar_02', true, date('now')),
('Dolls Meat', 'ZombieMeat', true, date('now')),
('Chocolate Bar', 'ChocolateCandy_09', true, date('now')),
('Zombie_0true_Head', 'Zombie_0true_Head', true, date('now')),
('Chop_Deer_Limbs', 'Chop_Deer_Limbs', true, date('now')),
('Weapon_Improvised_Handgun', 'Weapon_Improvised_Handgun', true, date('now')),
('Horsehead', 'Horse_Head', true, date('now')),
('Take_Bandage_Out', 'Take_Bandage_Out', true, date('now')),
('Cracker', 'Crackers', true, date('now')),
('Dirty Rags', 'Rags_Dirty', true, date('now')),
('Baked Beans', 'BakedBeans', true, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_02_03', true, date('now')),
('Hippy Pants', 'Zombie_Hippie_Pants_0true_03', true, date('now')),
('Logs', 'Wooden_Log_02', true, date('now')),
('Egg For Cooking', 'CookEgg2', true, date('now')),
('Human Foot', 'Prisoner_Right_Foot', true, date('now')),
('Ammunition Box 5.45 × 39 Mm', 'Cal_5_45x39_AmmoboxOpen', true, date('now')),
('Pear', 'Pear', true, date('now')),
('Leather Strips', 'Leather_Strip', true, date('now')),
('Slice_Zombie_Clothes_02', 'Slice_Zombie_Clothes_02', true, date('now')),
('Skinned Bear', 'Bear_Skinned', true, date('now')),
('Smoked Rabbit Meat', 'Smoked_RabbitMeat', true, date('now')),
('Orange Juice', 'GlassBottle04', true, date('now')),
('Cotton Shirt', 'Zombie_Shirt_0true', true, date('now')),
('Carrot', 'Carrot', true, date('now')),
('Rehbein', 'Doe_Left_Front_Leg', true, date('now')),
('Smoked Bear Steak', 'Smoked_Bear_Steak', true, date('now')),
('Hirschbein', 'Buck_Right_Front_Leg', true, date('now')),
('Beanie', 'Zombie_Beenie_07', true, date('now')),
('Human Head', 'Prisoner_Head', true, date('now')),
('Wild Steak', 'Doe_0true_Steak', true, date('now')),
('People Steak', 'Human_Steak', true, date('now')),
('Improvised Water Tank', 'Improvised_Water_container', true, date('now')),
('Wine', 'Wine', true, date('now')),
('Brake Fluid', 'Break_Oil', true, date('now')),
('Emergency bandage', 'Emergency_bandage', true, date('now')),
('Cartridge Sleeve .50 Bwg', 'Cal50_Empty', true, date('now')),
('Leather Pieces', 'Leather_Sheet', true, date('now')),
('Magnifying Glass', 'Magnifying_Glasstrue', true, date('now')),
('Wooden Spoon', 'Wooden_Spoon', true, date('now')),
('Smoked Sausages', 'Smoked_Sausages', true, date('now')),
('Lemon', 'Lemon', true, date('now')),
('Chop_Duck_Skinned', 'Chop_Duck_Skinned', true, date('now')),
('Grapes', 'Grapes_Raw', true, date('now')),
('Emergency bandage Big', 'Emergency_bandage_Big', true, date('now')),
('Bear Leg', 'Bear_Left_Back_Leg', true, date('now')),
('TEC0true M9', 'M9', true, date('now')),
('Blue Bald Head', 'Psilocybe_Cyanescens', true, date('now')),
('Duck Legs', 'White_Duck_Legs', true, date('now')),
('Stew', 'Stew2', true, date('now')),
('Pasta', 'Cooked_Pasta_02', true, date('now')),
('Zombie_0true_Left_Arm', 'Zombie_0true_Left_Arm', true, date('now')),
('Coal', 'Charcoal', true, date('now')),
('Breast Meat', 'Bird_Breasts_Small', true, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_02_0true', true, date('now')),
('Donkey Steak', 'Donkey_Steak', true, date('now')),
('Glue', 'Glue', true, date('now')),
('Trucker Jacket', 'Zombie_Trucker_Jacket_02', true, date('now')),
('Magazine SVD Dragunov', 'Magazine_SVD_Dragunov', true, date('now')),
('Mtrue Rifle', 'Weapon_Mtrue_Garand', true, date('now')),
('Instant Oatmeal', 'Instant_OatMeal', true, date('now')),
('Smoked Chicken Meat', 'Smoked_ChickenMeat', true, date('now')),
('Gulls Keulen', 'Seagull_Legs', true, date('now')),
('Sweet And Sour Chicken In Canton Style', 'Cantonese_Sweet_And_sour_0true', true, date('now')),
('Ammunition Box Caliber .22', 'Cal22_Ammobox_Open', true, date('now')),
('Ammunition Container .50 Bwg', 'Cal50_AmmoboxOpen', true, date('now')),
('Hippy Pants', 'Zombie_Hippie_Pants_02_0true', true, date('now')),
('Zombie_0true_Left_Foot', 'Zombie_0true_Left_Foot', true, date('now')),
('ACOG Scope', 'WeaponScope_ACOG_0true', true, date('now')),
('Whiskey', 'Whiskey', true, date('now')),
('Chop_Tree_0true', 'Chop_Tree_0true', true, date('now')),
('Ris Adapter For Ak47', 'ScopeRail_AK47', true, date('now')),
('Smoked Sheep Steak', 'Smoked_Sheep_Steak', true, date('now')),
('Rubber Band', 'Rubber_band', true, date('now')),
('Sardine', 'CannedSardine', true, date('now')),
('Crow Breasts', 'Crow_Breasts', true, date('now')),
('Canteen', 'Canteen', true, date('now')),
('Kiwi', 'Kiwi', true, date('now')),
('Bear Leg', 'Bear_Left_Front_Leg', true, date('now')),
('Cartridge .45 Acp', 'Cal45', true, date('now')),
('Event_2H_Katana', 'Event_2H_Katana', true, date('now')),
('Cannon Ammunition', 'Cal20mm_AmmoBoxClosed', true, date('now')),
('Cal_50_AE_Ammobox_Open', 'Cal_50_AE_Ammobox_Open', true, date('now')),
('Wooden Board', 'Wooden_Plank', true, date('now')),
('Cartridge 7.62 X 5true Mm', 'Cal7_62x5truemm', true, date('now')),
('Chop_Watermelon', 'Chop_Watermelon', true, date('now')),
('Slice_Clothes_02', 'Slice_Clothes_02', true, date('now')),
('Smoked Calf Steak', 'Smoked_Veal_Steak', true, date('now')),
('Cal_357_Ammobox_Open', 'Cal_357_Ammobox_Open', true, date('now')),
('Cooked Vegetables', 'Cooked_Vegetables_0true', true, date('now')),
('Angler', 'Zombie_Boonie_Hat_true3', true, date('now')),
('Scrap Metal', 'Metal_Scrap_05', true, date('now')),
('"uncle Pong" Rice', 'Rice', true, date('now')),
('Stone', 'Stone', true, date('now')),
('Cone-headed Tuber-leaved Mushroom', 'Amanita_Virosa', true, date('now')),
('Dirty Rags', 'Rag_Stripes_Dirty', true, date('now')),
('Mosin-nagant', 'Mosin_nagant', true, date('now')),
('Improvised Rope', 'Improvised_rope', true, date('now')),
('Beretta M9', 'BerettaM9', true, date('now')),
('Date', 'Date', true, date('now')),
('Chop_Crow_Skinned', 'Chop_Crow_Skinned', true, date('now')),
('Guava', 'GuavaHalves', true, date('now')),
('Paper', 'Paper', true, date('now')),
('Skinned Rat', 'Rat_torso', true, date('now')),
('Adrenaline Syringe', 'Adrenaline_Shot', true, date('now')),
('Chips "classic"', 'Chips', true, date('now')),
('Sausages', 'Sausages', true, date('now')),
('Improvised Metal Spear', 'Improvised_Metal_Spear', true, date('now')),
('Cal_50_AE_truepcs', 'Cal_50_AE_truepcs', true, date('now')),
('Skewer', 'Skewer_Vegetables', true, date('now')),
('Smoker', 'Smoker_0true', true, date('now')),
('Tin Opener', 'CanOpener', true, date('now')),
('Rehbein', 'Goat_Horns', true, date('now')),
('Produce Preserve', 'CanningFood', true, date('now')),
('Bundle_Wooden_Plank', 'Bundle_Wooden_Plank', true, date('now')),
('Copper Coins', 'Copper_Coins', true, date('now')),
('Water Bottle', 'Water_05l', true, date('now')),
('Tactical Gloves', 'Zombie_Tactical_Gloves_03', true, date('now')),
('Pot Roast', 'Pot_meat', true, date('now')),
('Big Nettle', 'Stinging_Nettle', true, date('now')),
('Cal_50_AE_Ammobox_Closed', 'Cal_50_AE_Ammobox_Closed', true, date('now')),
('Walnut', 'Walnut', true, date('now')),
('Tomato Sauce', 'TomatoSouce', true, date('now')),
('Superglue', 'Super_Glue', true, date('now')),
('Mulberry', 'Mulberry', true, date('now')),
('Event_Sledgehammer', 'Event_Sledgehammer', true, date('now')),
('Goats Hull', 'Goat_Torso', true, date('now')),
('Ingredients For Chili Con Carne', 'Chili_con_Carne_Preparation', true, date('now')),
('Spas-true2', 'SPAS-true2', true, date('now')),
('Scrap Metal', 'Metal_Scrap_02', true, date('now')),
('Sugar Beet', 'SugarBeet', true, date('now')),
('Skewer_Sausages', 'Skewer_Sausages', true, date('now')),
('Chop_Goat_Limb_Back', 'Chop_Goat_Limb_Back', true, date('now')),
('Tangerine', 'Tangerine', true, date('now')),
('Gunpowder', 'Gun_Powder', true, date('now')),
('Tinder', 'Tinder', true, date('now')),
('Skinned Swan', 'Swan_Skinned', true, date('now')),
('Lime Shower', 'PETBottle04', true, date('now')),
('Lighter', 'Lighter', true, date('now')),
('Slice_Clothes_06_RagsWithAnimalSkin', 'Slice_Clothes_06_RagsWithAnimalSkin', true, date('now')),
('Small Stone', 'Stone_Small', true, date('now')),
('Car Battery', 'Car_Battery', true, date('now')),
('Plastic Bowl', 'Pot2', true, date('now')),
('Ammunition Box 7,62 × 54 Mm R', 'Cal7_62x54mmR_Ammobox_Open', true, date('now')),
('Beef Stew Preserve', 'CannedGoulash', true, date('now')),
('Eselskopf', 'Donkey_Head', true, date('now')),
('Chop_Donkey', 'Chop_Donkey', true, date('now')),
('Aks-74u', 'Weapon_AKS_74U', true, date('now')),
('Santa_Glove', 'Santa_Glove', true, date('now')),
('Skinned Boar', 'Boar_Skinned', true, date('now')),
('Chop_Bear_Skinned', 'Chop_Bear_Skinned', true, date('now')),
('Cantaloupe', 'CantaloupeMelon', true, date('now')),
('Real Chanterelle', 'Cantharellus_Cibarius', true, date('now')),
('Vodka "majestic Bear"', 'Vodka', true, date('now')),
('Ammunition Box 7.62 X 5true Mm', 'Cal7_62x5truemm_Ammobox_Open_2', true, date('now')),
('Cartridge Sleeve .45 Acp', 'Cal45_Empty', true, date('now')),
('Smoked Pork Steak', 'Smoked_Pork_Steak', true, date('now')),
('Bunch Of Wooden Sticks', 'Wooden_Sticks_Bundle_Large', true, date('now')),
('Fishing Hook', 'Fishing_hook', true, date('now')),
('Smoked Cat Steak', 'Smoked_Cat_Steak', true, date('now')),
('Breast Meat', 'Bird_Breasts_Large', true, date('now')),
('Smoked Human Sausage', 'Smoked_Human_Sausages', true, date('now')),
('Aspirin', 'Aspirin', true, date('now')),
('Cola', 'Can04', true, date('now')),
('Peachcompote', 'CannedPeach', true, date('now')),
('Cartridge Sleeve Caliber .22', 'Cal22_Empty', true, date('now')),
('Soap', 'Soap', true, date('now')),
('CantaloupeMelon Slice', 'CantaloupeMelon_Slice', true, date('now')),
('Slice_Zombie_Clothes_0true', 'Slice_Zombie_Clothes_0true', true, date('now')),
('Skinned Seagull', 'Seagull_Skinned', true, date('now')),
('Smoked Rat Meat', 'Smoked_RatMeat', true, date('now')),
('Soy Sauce', 'SoySauce', true, date('now')),
('Cannon Ammunition 20 Mm', 'Cal20mm', true, date('now')),
('Orange', 'Orange', true, date('now')),
('Penicillin', 'Penicillin0true', true, date('now')),
('MRE Stew', 'MRE_Stew', true, date('now')),
('Cal30-06_5_bullets', 'Cal30-06_5_bullets', true, date('now')),
('Pancakes', 'Pancakes', true, date('now')),
('Cal_357_5pcs', 'Cal_357_5pcs', true, date('now')),
('Blackberry', 'Blackberry', true, date('now')),
('Slice_Dirty_Rags_Into_Stripes', 'Slice_Dirty_Rags_Into_Stripes', true, date('now')),
('Logs', 'Wooden_Log_0true', true, date('now')),
('Cartridge 5.45 × 39 Mm', 'Cal_5_45x39_Bullet', true, date('now')),
('Atropinspritze', 'AtropineInjection', true, date('now')),
('Goat Steak', 'Goat_Steak', true, date('now')),
('Small Wooden Stick', 'Wooden_Stick', true, date('now')),
('Bone', 'Animal_Bone_Big', true, date('now')),
('Coprinus Comatus', 'Coprinus_Comatus', true, date('now')),
('Cartridge 5.45 × 39 Mm', 'Cal_5_45x39_empty', true, date('now')),
('Dandelion', 'Dandelion', true, date('now')),
('Dog Food', 'CannedDogFood', true, date('now')),
('Jerrycan', 'Gasoline_Canister', true, date('now')),
('Milk', 'Milk', true, date('now')),
('Chop_Deer_Skinned', 'Chop_Deer_Skinned', true, date('now')),
('Silberband', 'Silver_Strip', true, date('now')),
('Wild Boar Head', 'Boar_head', true, date('now')),
('Peachcompote', 'CannedPear', true, date('now')),
('Fire Drill', 'Fire_Hand_Drill_new', true, date('now')),
('Tactical Jacket', 'Zombie_Tactical_Jacket_0true', true, date('now')),
('Boar Claws', 'Boar_Hooves_Back', true, date('now')),
('Bärenkopf', 'Bear_Head', true, date('now')),
('Thread', 'Thread', true, date('now')),
('Hüfttasche', 'Zombie_Waist_Bag_Small_0true', true, date('now')),
('Onion', 'Onion', true, date('now')),
('Tomato', 'Tomato', true, date('now')),
('Hirschbein', 'Buck_Left_Back_Leg', true, date('now')),
('Apple_2', 'Apple_2', true, date('now')),
('Slicker', 'Zombie_Raincoat_Down_0true', true, date('now')),
('Tin', 'CannedFoodtrue', true, date('now')),
('Big Stone', 'Stone_Large', true, date('now')),
('Meat Snack Spicy', 'MeatSnack_0true', true, date('now')),
('Cucumber', 'Cucumber', true, date('now')),
('Long Wooden Stick', 'Long_wooden_stick', true, date('now')),
('Burger', 'Burger', true, date('now')),
('Strawberry Toaster Pastries', 'Toaster_Pastries', true, date('now')),
('Ammunition Box .45 Acp', 'Cal45_AmmoboxClosed', true, date('now')),
('Chop_Zombie', 'Chop_Zombie', true, date('now')),
('Cal_357_Ammobox_Closed', 'Cal_357_Ammobox_Closed', true, date('now')),
('Joints Of Meat', 'Bird_Legs_Small', true, date('now')),
('Smoked Duck Meat', 'Smoked_DuckMeat', true, date('now')),
('Zucchini', 'Zucchini', true, date('now')),
('Sea-salt', 'SeaSalt_0true', true, date('now')),
('Left Rabbit Spine Piece', 'Rabbit_Left_Back', true, date('now')),
('Ammunition Box 7.62 × 39 Mm', 'Cal7_62x39mm_Ammobox_Open', true, date('now')),
('Fat', 'Big_Animal_Fat', true, date('now')),
('MRE TunaSalad', 'MRE_TunaSalad', true, date('now')),
('Smoked Pheasant Meat', 'Smoked_PheasantMeat', true, date('now')),
('Cal30-06_Bullet', 'Cal30-06_Bullet', true, date('now')),
('Hammock', 'Hammock', true, date('now')),
('Cal30-06_Ammobox_Closed', 'Cal30-06_Ammobox_Closed', true, date('now')),
('Smoked Wild Boar Meat', 'Smoked_Boar_Steak', true, date('now')),
('Lead Plate', 'Lead_Plate', true, date('now')),
('Goose Meat', 'GooseMeat', true, date('now')),
('Bean Stew', 'Beans_Stew_02', true, date('now')),
('Cartridge Sleeve 9 Mm', 'Cal_9mm_empty', true, date('now')),
('Cal7_62x39mm_5_Pile', 'Cal7_62x39mm_5_Pile', true, date('now')),
('Event_2H_Axe', 'Event_2H_Axe', true, date('now')),
('Safety Pin', 'Safety_pin', true, date('now')),
('Horse`s Leg', 'Horse_Front_Limb', true, date('now')),
('Caramel Shower', 'PETBottle0true', true, date('now')),
('Blue Jeans', 'Zombie_Jeans_0true_0true', true, date('now')),
('Work Trousers', 'Zombie_MilitaryPants_0true', true, date('now')),
('Sedative', 'Sedative', true, date('now')),
('Skinned Bird', 'Bird_Skinned_Large', true, date('now')),
('Ammunition Box Caliber .500 S & M', 'Cal500SW_AmmoboxOpen', true, date('now')),
('Duct Tape', 'Duct_Tape', true, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_0true_0true', true, date('now')),
('Hazel', 'Hazelnuts', true, date('now')),
('Acorns', 'Oak_Nuts', true, date('now')),
('Zombie_Tactical_Jacket_05', 'Zombie_Tactical_Jacket_05', true, date('now')),
('Spaghetti Bolognese', 'Spaghetti_bolognese_02', true, date('now')),
('Ziegenbein', 'Goat_Back_Limb', true, date('now')),
('Smoke Grenade', 'Smoke_Grenade', true, date('now')),
('Steak With Potatoes', 'Steak_With_Potatoes_0true', true, date('now')),
('Ammunition Box 7.62 × 39 Mm', 'Cal7_62x39mm_Ammobox_Closed', true, date('now')),
('Chop_Donkey_Limb_Front', 'Chop_Donkey_Limb_Front', true, date('now')),
('Motherboard', 'MOtherboard', true, date('now')),
('Potato', 'Potato', true, date('now')),
('Cooked Potato', 'Cooked_potato', true, date('now')),
('Logs', 'Wooden_Log_Small_03', true, date('now')),
('Tripwire Trap', 'Trip_wire_dead_fall_for_large_animals', true, date('now')),
('Pigeons Keulen', 'Pigeon_Legs', true, date('now')),
('TEC0true 490', 'Weapon_590Atruetrue', true, date('now')),
('Chop_Doe_Torso', 'Chop_Doe_Torso', true, date('now')),
('Soup', 'Soup_0true', true, date('now')),
('Riesenbovist', 'Lycoperdon_Gigantea', true, date('now')),
('Bicarbonate Of Soda', 'BakingSoda', true, date('now')),
('Broccoli', 'Broccoli', true, date('now')),
('Freshwater Fish', 'FishFreshwater', true, date('now')),
('Lime Juice', 'GlassBottle03', true, date('now')),
('Flashbang', 'Flashbang', true, date('now')),
('Portable Gas Cooker', 'Portable_Gas_Stove', true, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_0true_02', true, date('now')),
('Kitchen Board', 'Kitchen_Board_02', true, date('now')),
('Anode Plate', 'Anode_Plate', true, date('now')),
('Sewing', 'Sewing_kit', true, date('now')),
('Flannel Shirt', 'Zombie_Woodcutter_Shirt_03', true, date('now')),
('Intestines', 'Big_Animal_guts', true, date('now')),
('Beef Stew', 'BeefStew', true, date('now')),
('Vinegar', 'Vinegar', true, date('now')),
('Ammunition Box Caliber .500 S & M', 'Cal500SW_Ammoboxclosed', true, date('now')),
('Scope Rail (Dragunov)', 'ScopeRail_Dragunov', true, date('now')),
('Cartridge 7.62 × 54 Mm R', 'Cal7_62x54mmR', true, date('now')),
('Skinned Goat', 'Goat_Skinned', true, date('now')),
('Aks-74u Magazine', 'Magazine_AKS_74U', true, date('now')),
('Honeycomb', 'Honeycomb', true, date('now')),
('Lime', 'Lime', true, date('now')),
('Logs', 'Wooden_Log_Small_02', true, date('now')),
('Left Rabbit Front Piece', 'Rabbit_Left_Front', true, date('now')),
('Sheep Steak', 'Sheep_Steak', true, date('now')),
('Spice Mix', 'SpicesMix_0true', true, date('now')),
('Pike', 'Skewer_02', true, date('now')),
('Strawberry', 'Wild_Strawberry', true, date('now')),
('Schokoküchlein', 'ChocolateCandy_03', true, date('now')),
('Tactical Sweater', 'Zombie_Tactical_Sweater_06', true, date('now')),
('Dogs Steak', 'Dog_Steak', true, date('now')),
('Yeast', 'Yeast', true, date('now')),
('Scrap Metal', 'Metal_Scrap_0true', true, date('now')),
('Pineapple', 'Pineapple', true, date('now')),
('Parsley', 'Parsley', true, date('now')),
('Chow Mein', 'Chow_Mein', true, date('now')),
('Ammunition Container .50 Bwg', 'Cal50_AmmoboxClosed', true, date('now')),
('Chop_Duck', 'Chop_Duck', true, date('now')),
('Weapon_Improvised_Rifle', 'Weapon_Improvised_Rifle', true, date('now')),
('Ingredients For Stew', 'StewPreparation', true, date('now')),
('Barrel With Saltwater Fish', 'Salted_fish_Barrel_0true', true, date('now')),
('NightVisionGoggles2_Test', 'NightVisionGoggles2_Test', true, date('now')),
('Grill', 'Grill', true, date('now')),
('Training Pants', 'Zombie_Tracksuit_Pants_02_02', true, date('now')),
('Chop_Doe', 'Chop_Doe', true, date('now')),
('Breast Meat', 'Bird_Breasts_Medium', true, date('now')),
('Aloe Vera', 'Aloe_Vera', true, date('now')),
('Hirschbein', 'Buck_Left_Front_Leg', true, date('now')),
('Wolf Leg', 'Wolf_Left_Front_Leg', true, date('now')),
('Diary', 'Diary', true, date('now')),
('Ammunition Box 7.62 X 5true Mm', 'Cal7_62x5truemm_Ammobox_Closed_2', true, date('now')),
('Loaf', 'Bread', true, date('now')),
('Needle', 'Needle', true, date('now')),
('Apple Pie', 'Apple_Pie', true, date('now')),
('Rodent Meat', 'RodentMeat', true, date('now')),
('Zombie_Shirt_02', 'Zombie_Shirt_02', true, date('now')),
('Mtrue-loading Frame', 'Mtrue_Clip', true, date('now')),
('Chop_Horse_Back_Limb', 'Chop_Horse_Back_Limb', true, date('now')),
('Improvised Wooden Spear', 'Improvised_Wooden_Spear', true, date('now')),
('Skinned Crow', 'Crow_Skinned', true, date('now')),
('Canned Meat', 'Spam', true, date('now')),
('Skinned Bird', 'Bird_Skinned_Medium', true, date('now')),
('Improvised Magnifying Glass', 'Magnifying_Glass', true, date('now')),
('Aluminum Strips', 'Aluminium_Strip', true, date('now')),
('Improvised_Wooden_Chest', 'Improvised_Wooden_Chest', true, date('now')),
('Copper Tape', 'Copper_Strip', true, date('now')),
('Duck Meat', 'DuckMeat', true, date('now')),
('Skinned Rabbit', 'Rabbit_Skinned', true, date('now')),
('Cigarettes "classics"', 'Cigarettes', true, date('now')),
('ChocolateCandy_05', 'ChocolateCandy_05', true, date('now')),
('Akm', 'Weapon_AKM', true, date('now')),
('Swan Keulen', 'Swan_Legs', true, date('now')),
('Boar Hull', 'Boar_Torso', true, date('now')),
('Cotton Hoodie', 'Zombie_Hoodie_02', true, date('now')),
('Smoked Human Steak', 'Smoked_Human_Steak', true, date('now')),
('Swan Chest', 'Swan_Breasts', true, date('now')),
('Boiled Egg', 'Cooked_egg', true, date('now')),
('Cauliflower', 'Cauliflower', true, date('now')),
('Antler', 'Buck_Antlers', true, date('now')),
('Glossy Lackporling', 'Ganoderma_Lucidum', true, date('now')),
('Skinned Wolf', 'Wolf_Skinned', true, date('now')),
('Chili Con Carne', 'Chilli_Con_Carne_02', true, date('now')),
('Garlic', 'Garlic', true, date('now')),
('Cartridge 7.62 × 39 Mm', 'Cal7_62x39mm', true, date('now')),
('Crab_Apple', 'Crab_Apple', true, date('now')),
('Chop_Wolf_Torso', 'Chop_Wolf_Torso', true, date('now')),
('Auto Gloves', 'Zombie_Driving_Gloves_03', true, date('now')),
('Biscuits', 'Pastry', true, date('now')),
('ChocolateCandy_06', 'ChocolateCandy_06', true, date('now')),
('Zombie_Tactical_Gloves_07', 'Zombie_Tactical_Gloves_07', true, date('now')),
('Cereal BunnyStars', 'Cereal_BunnyStars', true, date('now')),
('Rice', 'Cooked_Rice', true, date('now')),
('Improvised Stone Spear', 'Improvised_Stone_Spear', true, date('now')),
('Honey Yellow Hamburger', 'Armillaria_Mellea', true, date('now')),
('Cartridge 5.45 × 39 Mm', 'Cal_5_45x39_Pile', true, date('now')),
('Baby Food', 'BabyFood', true, date('now')),
('Shorts', 'Zombie_Shorts_Pants_07', true, date('now')),
('Egg For Cooking', 'CookEggtrue', true, date('now')),
('Skinned Deer', 'Buck_Skinned', true, date('now')),
('Make_Lead_Plates', 'Make_Lead_Plates', true, date('now')),
('Pasta', 'Pasta', true, date('now')),
('Chop_Seagull', 'Chop_Seagull', true, date('now')),
('Cartridge Sleeve 7.62 × 54 Mm R', 'Cal7_62x54mmR_Empty', true, date('now')),
('Popcorn', 'Popcorn_02', true, date('now')),
('Half Bear Hull', 'Bear_Right_Torso_Half', true, date('now')),
('Schokopraline', 'ChocolateCandy_true0', true, date('now')),
('Pheasant', 'PheasantMeat', true, date('now')),
('Common Giant Parakeet', 'Lepiota_Procera', true, date('now')),
('Chop_Horse', 'Chop_Horse', true, date('now')),
('Chop_Wolf_Skinned', 'Chop_Wolf_Skinned', true, date('now')),
('Chicken', 'ChickenMeat', true, date('now')),
('Cartridge 9 Mm', 'Cal_9mm', true, date('now')),
('M9 Magazine', 'Magazine_M9', true, date('now')),
('Duck Breast', 'White_Duck_Breasts', true, date('now')),
('Tactical Army Pants', 'Zombie_MilitaryPants_04', true, date('now')),
('Slate Schillerporling', 'Inonotus_Obliquus', true, date('now')),
('Zombie_WorkPants_03', 'Zombie_WorkPants_03', true, date('now')),
('Camouflage Jacket', 'Zombie_Camouflage_Jacket_0true', true, date('now')),
('Cartridge Sleeve .500 S & M', 'Cal500SW_Empty', true, date('now')),
('Skinned Donkey', 'Donkey_skinned', true, date('now')),
('Vitamin Tablets (box)', 'Vitamins_02', true, date('now')),
('Fruit Cocktail', 'CannedFruitCoctail', true, date('now')),
('Saltwater Fish', 'SeaWaterFish', true, date('now')),
('Work Jacket', 'Zombie_Work_Jacket_0true', true, date('now')),
('Cartridge .500 S & M', 'Cal500SW', true, date('now')),
('Earthworm', 'Earthworm', true, date('now')),
('Chop_Boar_Torso', 'Chop_Boar_Torso', true, date('now')),
('Barbed Wire', 'Barbed_Wire', true, date('now')),
('SVD Dragunov', 'Weapon_SVD_Dragunov', true, date('now')),
('Paper', 'Test_Paper', true, date('now')),
('Improvised_Metal_Chest', 'Improvised_Metal_Chest', true, date('now')),
('Rehbein', 'Doe_Right_Front_Leg', true, date('now')),
('Ziegenbein', 'Goat_Front_Limb', true, date('now')),
('Pan', 'Pan', true, date('now')),
('Common Cep', 'Boletus_Edulis', true, date('now')),
('Animal Bones', 'Animal_Bone_SMall', true, date('now')),
('Crow Keulen', 'Crow_Legs', true, date('now')),
('Green Tuber Leaf Mushroom', 'Amantia_phalloides', true, date('now')),
('Zombie_Working_pants_0true', 'Zombie_Working_pants_0true', true, date('now')),
('Gear', 'Gear', true, date('now')),
('Rat`s Head', 'Rat_Head', true, date('now')),
('Chop_Deer', 'Chop_Deer', true, date('now')),
('Chop_Horse_Front_Limb', 'Chop_Horse_Front_Limb', true, date('now')),
('Chili Con Carne', 'Chilli_Con_Carne_0true', true, date('now')),
('Watermelon', 'Watermelon', true, date('now')),
('Smoked Wild Steak', 'Smoked_Deer_Steak', true, date('now')),
('Wolf Head', 'Wolf_Head', true, date('now')),
('Coward', 'Fig', true, date('now')),
('Skinned Duck', 'White_Duck_Skinned', true, date('now')),
('Shelter', 'Shelter', true, date('now')),
('Pike', 'Skewer', true, date('now')),
('Fried Egg', 'Fried_Egg_02', true, date('now')),
('Crab Legs', 'Crab_Legs', true, date('now')),
('Tequila', 'Tequila', true, date('now')),
('Leather Jacket', 'Zombie_Jacket_0true', true, date('now')),
('German Helmet (2nd Ww)', 'WW2_German_Helmet', true, date('now')),
('Skinned Pigeon', 'Pigeon_Skinned', true, date('now')),
('SVD Scope', 'WeaponScope_Dragunov', true, date('now')),
('Standing_Torch_0true', 'Standing_Torch_0true', true, date('now')),
('Ak-47', 'Weapon_AK47', true, date('now')),
('Chocolate Bar', 'ChocolateCandy_08', true, date('now')),
('Small Toolbox', 'Tool_Box_SMall', true, date('now')),
('Spaghetti With Meatballs', 'CannedSpaghetti', true, date('now')),
('Sugar', 'Sugar', true, date('now')),
('MRE Cheeseburger', 'MRE_Cheeseburger', true, date('now')),
('Chocolate Bar', 'ChocolateCandy_truetrue', true, date('now')),
('Carbon Electrodes', 'Carbon_Electrodes', true, date('now')),
('Seagulls Chest', 'Seagull_Breasts', true, date('now')),
('Black Olives', 'BlackOlives', true, date('now')),
('Event_trueH_N9_Black', 'Event_trueH_N9_Black', true, date('now')),
('PrepareCannedFood', 'PrepareCannedFood', true, date('now')),
('Human Leg', 'Prisoner_Left_Leg', true, date('now')),
('Peeled Tomatoes', 'TomatoPelate', true, date('now')),
('Improvised Fireplace', 'Fireplace2', true, date('now')),
('Rat Meat', 'RatMeat', true, date('now')),
('Sweet And Sour Chicken In Canton Style', 'Cantonese_Sweet_And_sour_02', true, date('now')),
('Chop_Goat_Skinned', 'Chop_Goat_Skinned', true, date('now')),
('Chop_Debree_Log_Big_03', 'Chop_Debree_Log_Big_03', true, date('now')),
('Isopropanol', 'Isopropyl_alcohol', true, date('now')),
('Cornflakes', 'Corn_flakes', true, date('now')),
('Shorts', 'Zombie_Shorts_Pants_04', true, date('now')),
('Rehkopf', 'Doe_Head', true, date('now')),
('NightVisionGoggles Test', 'NightVisionGoggles_Test', true, date('now')),
('Chop_Donkey_Torso', 'Chop_Donkey_Torso', true, date('now')),
('Chocolate', 'ChocolateCandy_04', true, date('now')),
('Lime Shower', 'PETBottle03', true, date('now')),
('Chop_Doe_Limbs', 'Chop_Doe_Limbs', true, date('now')),
('Smoked Goat Steak', 'Smoked_Goat_Steak', true, date('now')),
('Training Jacket', 'Vest_0true_0true', true, date('now')),
('Human Leg', 'Prisoner_Right_Leg', true, date('now')),
('Boar Claws', 'Boar_Hooves_front', true, date('now')),
('Intestines', 'Small_Animal_guts', true, date('now')),
('Skinned Bird', 'Bird_Skinned_Small', true, date('now')),
('Human Arm', 'Prisoner_Left_Arm', true, date('now')),
('Wild Garlic', 'Ramsons', true, date('now')),
('E_trueH_Small_Axe', 'E_trueH_Small_Axe', true, date('now')),
('Antenna', 'Antena', true, date('now')),
('Corn', 'Corn', true, date('now')),
('Beer', 'Beer', true, date('now')),
('Chop_Big_Log', 'Chop_Big_Log', true, date('now')),
('Wheat Flour', 'WhiteFlour', true, date('now')),
('9mm Ammunition Box', 'Cal_9mm_AmmoboxClosed', true, date('now')),
('Larva', 'Larve', true, date('now')),
('Ravioli With Beef', 'BeefRavioli', true, date('now')),
('Chop_Rat', 'Chop_Rat', true, date('now')),
('Beefsteak Fungus', 'Fistula_Hepatica', true, date('now')),
('Work Trousers', 'Working_pants_0true', true, date('now')),
('M9 Silver', 'M9_Silver', true, date('now')),
('School Backpack Girl 03', 'School_Backpack_Girl_03', true, date('now')),
('School Backpack Girl 02', 'School_Backpack_Girl_02', true, date('now')),
('School Backpack Girl 0true', 'School_Backpack_Girl_0true', true, date('now')),
('School Backpack Boy 03', 'School_Backpack_Boy_03', true, date('now')),
('School Backpack Boy 02', 'School_Backpack_Boy_02', true, date('now')),
('Cal7 62x54mm', 'Cal7_62x54mm', true, date('now')),
('BeePollen Pils 03', 'BeePollen_Pils_03', true, date('now')),
('BeePollen Pils 02', 'BeePollen_Pils_02', true, date('now')),
('Antiparasitics 03', 'Antiparasitics_03', true, date('now')),
('Antiparasitics 02', 'Antiparasitics_02', true, date('now')),
('AntiMalariaPils 03', 'AntiMalariaPils_03', true, date('now')),
('AntiMalariaPils 02', 'AntiMalariaPils_02', true, date('now')),
('Antibiotics 03', 'Antibiotics_03', true, date('now')),
('Antibiotics 02', 'Antibiotics_02', true, date('now')),
('Anti Radiation Pils 03', 'Anti_Radiation_Pils_03', true, date('now')),
('Anti Radiation Pils 02', 'Anti_Radiation_Pils_02', true, date('now')),
('ActivatedCharcoal 03', 'ActivatedCharcoal_03', true, date('now')),
('ActivatedCharcoal 02', 'ActivatedCharcoal_02', true, date('now')),
('MilitaryBoots Peace', 'MilitaryBoots_Peace', true, date('now')),
('Police Zombie Helmet2', 'Police_Zombie_Helmet2', true, date('now')),
('Police Zombie Helmet', 'Police_Zombie_Helmet', true, date('now')),
('Fireman Helmet 03', 'Fireman_Helmet_03', true, date('now')),
('Fireman Helmet 02', 'Fireman_Helmet_02', true, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_06', true, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_05', true, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_04', true, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_03', true, date('now')),
('Military Ballistic Vest', 'Bulletproof_Vest_02', true, date('now')),
('Bulletproof test', 'Bulletproof_test', true, date('now')),
('Stabproof Vest 09', 'Stabproof_Vest_09', true, date('now')),
('Stabproof Vest 08', 'Stabproof_Vest_08', true, date('now')),
('Stabproof Vest 07', 'Stabproof_Vest_07', true, date('now')),
('Stabproof Vest 06', 'Stabproof_Vest_06', true, date('now')),
('Stabproof Vest 04', 'Stabproof_Vest_04', true, date('now')),
('Stabproof Vest 03', 'Stabproof_Vest_03', true, date('now')),
('Stabproof Vest 02', 'Stabproof_Vest_02', true, date('now')),
('Camo Backpack 05', 'Camo_Backpack_05', true, date('now')),
('Camo Backpack 04', 'Camo_Backpack_04', true, date('now')),
('Camo Backpack 03', 'Camo_Backpack_03', true, date('now')),
('Camo Backpack 02', 'Camo_Backpack_02', true, date('now')),
('Assault Backpack', 'Backpack_0true_09', true, date('now')),
('Assault Backpack', 'Backpack_0true_08', true, date('now')),
('Assault Backpack', 'Backpack_0true_07', true, date('now')),
('Assault Backpack', 'Backpack_0true_06', true, date('now')),
('Assault Backpack', 'Backpack_0true_05', true, date('now')),
('Assault Backpack', 'Backpack_0true_04', true, date('now')),
('Assault Backpack', 'Backpack_0true_03', true, date('now')),
('Assault Backpack', 'Backpack_0true_02', true, date('now')),
('Backpack', 'Backpack_02_true4', true, date('now')),
('Backpack', 'Backpack_02_true3', true, date('now')),
('Backpack', 'Backpack_02_true2', true, date('now')),
('Backpack', 'Backpack_02_truetrue', true, date('now')),
('Backpack', 'Backpack_02_true0', true, date('now')),
('Backpack', 'Backpack_02_09', true, date('now')),
('Backpack', 'Backpack_02_08', true, date('now')),
('Backpack', 'Backpack_02_07', true, date('now')),
('Backpack', 'Backpack_02_06', true, date('now')),
('Backpack', 'Backpack_02_05', true, date('now')),
('Backpack', 'Backpack_02_04', true, date('now')),
('Backpack', 'Backpack_02_03', true, date('now')),
('Backpack', 'Backpack_02_02', true, date('now')),
('Raincoat Up 06', 'Raincoat_Up_06', true, date('now')),
('Raincoat Up 05', 'Raincoat_Up_05', true, date('now')),
('Raincoat Up 04', 'Raincoat_Up_04', true, date('now')),
('Raincoat Up 03', 'Raincoat_Up_03', true, date('now')),
('Raincoat Up 02', 'Raincoat_Up_02', true, date('now')),
('Raincoat Up 0true', 'Raincoat_Up_0true', true, date('now')),
('Raincoat Down 06', 'Raincoat_Down_06', true, date('now')),
('Raincoat Down 05', 'Raincoat_Down_05', true, date('now')),
('Raincoat Down 04', 'Raincoat_Down_04', true, date('now')),
('Raincoat Down 03', 'Raincoat_Down_03', true, date('now')),
('Raincoat Down 02', 'Raincoat_Down_02', true, date('now')),
('Abundant_0true', 'Abundant_0true', true, date('now')),
('Abundant_02', 'Abundant_02', true, date('now')),
('Abundant_03', 'Abundant_03', true, date('now')),
('Animal_Skin_Jacket', 'Animal_Skin_Jacket', true, date('now')),
('Animal_Skin_Pants', 'Animal_Skin_Pants', true, date('now')),
('Assault_Backpack', 'Assault_Backpack', true, date('now')),
('Assault_Backpacktrue', 'Assault_Backpacktrue', true, date('now')),
('Assault_Vest', 'Assault_Vest', true, date('now')),
('Aviators', 'Aviators', true, date('now')),
('Balaclava', 'Balaclava', true, date('now')),
('Bandana', 'Bandana', true, date('now')),
('Baseball_Cap_02', 'Baseball_Cap_02', true, date('now')),
('Baseball_Cap_true0', 'Baseball_Cap_true0', true, date('now')),
('Baseball_Cap_truetrue', 'Baseball_Cap_truetrue', true, date('now')),
('Baseball_Cap_true2', 'Baseball_Cap_true2', true, date('now')),
('Baseball_Cap_true3', 'Baseball_Cap_true3', true, date('now')),
('Baseball_Cap_true4', 'Baseball_Cap_true4', true, date('now')),
('Baseball_Cap_true5', 'Baseball_Cap_true5', true, date('now')),
('Baseball_Cap_true6', 'Baseball_Cap_true6', true, date('now')),
('Baseball_Cap_true7', 'Baseball_Cap_true7', true, date('now')),
('Baseball_Cap_true8', 'Baseball_Cap_true8', true, date('now')),
('Baseball_Cap_true9', 'Baseball_Cap_true9', true, date('now')),
('Basic_Shirt', 'Basic_Shirt', true, date('now')),
('Bear_Pow_One_Hand', 'Bear_Pow_One_Hand', true, date('now')),
('Bear_Pow_Shoe', 'Bear_Pow_Shoe', true, date('now')),
('Beenie_02', 'Beenie_02', true, date('now')),
('Beenie_03', 'Beenie_03', true, date('now')),
('Beenie_04', 'Beenie_04', true, date('now')),
('Beenie_05', 'Beenie_05', true, date('now')),
('Beenie_06', 'Beenie_06', true, date('now')),
('Beenie_07', 'Beenie_07', true, date('now')),
('Beenie_08', 'Beenie_08', true, date('now')),
('Beenie_09', 'Beenie_09', true, date('now')),
('Beenie_3_hole_02', 'Beenie_3_hole_02', true, date('now')),
('Beenie_3_hole_03', 'Beenie_3_hole_03', true, date('now')),
('Beenie_3_hole_04', 'Beenie_3_hole_04', true, date('now')),
('Beenie_3_hole_05', 'Beenie_3_hole_05', true, date('now')),
('Beenie_3_hole_06', 'Beenie_3_hole_06', true, date('now')),
('Beenie_3_hole_07', 'Beenie_3_hole_07', true, date('now')),
('Beenie_3_hole_08', 'Beenie_3_hole_08', true, date('now')),
('Beenie_3_hole_09', 'Beenie_3_hole_09', true, date('now')),
('Beenie_Test_02', 'Beenie_Test_02', true, date('now')),
('BeerCan', 'BeerCan', true, date('now')),
('Beret_Hat', 'Beret_Hat', true, date('now')),
('Biker_Goggles', 'Biker_Goggles', true, date('now')),
('Biker_Hat', 'Biker_Hat', true, date('now')),
('Biker_Sunglasses', 'Biker_Sunglasses', true, date('now')),
('Boonie_Hat_02', 'Boonie_Hat_02', true, date('now')),
('Boonie_Hat_04', 'Boonie_Hat_04', true, date('now')),
('Boonie_Hat_05', 'Boonie_Hat_05', true, date('now')),
('Boonie_Hat_06', 'Boonie_Hat_06', true, date('now')),
('Boonie_Hat_07', 'Boonie_Hat_07', true, date('now')),
('Boonie_Hat_08', 'Boonie_Hat_08', true, date('now')),
('Boonie_Hat_09', 'Boonie_Hat_09', true, date('now')),
('Boonie_Hat_true0', 'Boonie_Hat_true0', true, date('now')),
('Boonie_Hat_truetrue', 'Boonie_Hat_truetrue', true, date('now')),
('Boonie_Hat_true2', 'Boonie_Hat_true2', true, date('now')),
('Boonie_Hat_true3', 'Boonie_Hat_true3', true, date('now')),
('Boonie_Hat_true4', 'Boonie_Hat_true4', true, date('now')),
('Boonie_Hat_true5', 'Boonie_Hat_true5', true, date('now')),
('Borage', 'Borage', true, date('now')),
('DropZoneKey', 'DropZoneKey', true, date('now')),
('Weapon_98k_Karabiner_EVENT', 'Weapon_98k_Karabiner_EVENT', true, date('now')),
('Bracken', 'Bracken', true, date('now')),
('Buckwheat_grains', 'Buckwheat_grains', true, date('now')),
('Business_Pants', 'Business_Pants', true, date('now')),
('BusinessSuit', 'BusinessSuit', true, date('now')),
('Cal20mm_AmmoBoxOpen', 'Cal20mm_AmmoBoxOpen', true, date('now')),
('Cal7_62x39mm_20_Pile', 'Cal7_62x39mm_20_Pile', true, date('now')),
('Cal7_62x39mm_5_bullets', 'Cal7_62x39mm_5_bullets', true, date('now')),
('Camouflage_Jacket_02', 'Camouflage_Jacket_02', true, date('now')),
('Camouflage_Jacket_03', 'Camouflage_Jacket_03', true, date('now')),
('Cargo_Pants', 'Cargo_Pants', true, date('now')),
('Cateye_Sunglasses', 'Cateye_Sunglasses', true, date('now')),
('Chicory', 'Chicory', true, date('now')),
('Chocolate_Milk', 'Chocolate_Milk', true, date('now')),
('College_Jacket_02', 'College_Jacket_02', true, date('now')),
('College_Jacket_03', 'College_Jacket_03', true, date('now')),
('College_Jacket_04', 'College_Jacket_04', true, date('now')),
('College_Jacket_05', 'College_Jacket_05', true, date('now')),
('College_Jacket_06', 'College_Jacket_06', true, date('now')),
('College_Jacket_07', 'College_Jacket_07', true, date('now')),
('College_Jacket_08', 'College_Jacket_08', true, date('now')),
('Common_0true', 'Common_0true', true, date('now')),
('Common_02', 'Common_02', true, date('now')),
('Common_03', 'Common_03', true, date('now')),
('Cowboy_boots', 'Cowboy_boots', true, date('now')),
('Cowboy_Hat', 'Cowboy_Hat', true, date('now')),
('Cuff_Beanie_Hat', 'Cuff_Beanie_Hat', true, date('now')),
('Dr_Gl', 'Dr_Gl', true, date('now')),
('Driving_Gloves_02', 'Driving_Gloves_02', true, date('now')),
('Driving_Gloves_03', 'Driving_Gloves_03', true, date('now')),
('Driving_Gloves_04', 'Driving_Gloves_04', true, date('now')),
('Duffle_Bag', 'Duffle_Bag', true, date('now')),
('Energy_Drink', 'Energy_Drink', true, date('now')),
('ExtremelyRare_0true', 'ExtremelyRare_0true', true, date('now')),
('ExtremelyRare_02', 'ExtremelyRare_02', true, date('now')),
('ExtremelyRare_03', 'ExtremelyRare_03', true, date('now')),
('Fake_Nose_And_Sunglasses', 'Fake_Nose_And_Sunglasses', true, date('now')),
('Fastdraw_Holster', 'Fastdraw_Holster', true, date('now')),
('Football_Helmet', 'Football_Helmet', true, date('now')),
('Gas_Mask', 'Gas_Mask', true, date('now')),
('Ghillie_suit', 'Ghillie_suit', true, date('now')),
('Goalie_Helmet', 'Goalie_Helmet', true, date('now')),
('Gun_Holster', 'Gun_Holster', true, date('now')),
('Gym_Bag', 'Gym_Bag', true, date('now')),
('Heavy_Ballistic_Armor', 'Heavy_Ballistic_Armor', true, date('now')),
('Hiking_Backpack_02', 'Hiking_Backpack_02', true, date('now')),
('Hiking_Backpack_03', 'Hiking_Backpack_03', true, date('now')),
('Hiking_Backpack_04', 'Hiking_Backpack_04', true, date('now')),
('Hiking_Backpack_05', 'Hiking_Backpack_05', true, date('now')),
('Hiking_Backpack_06', 'Hiking_Backpack_06', true, date('now')),
('Hiking_Backpack_07', 'Hiking_Backpack_07', true, date('now')),
('Hiking_Backpack_08', 'Hiking_Backpack_08', true, date('now')),
('Hiking_Boots_02', 'Hiking_Boots_02', true, date('now')),
('Hiking_Boots_03', 'Hiking_Boots_03', true, date('now')),
('Hiking_Boots_04', 'Hiking_Boots_04', true, date('now')),
('Hippie_pants_0true_02', 'Hippie_pants_0true_02', true, date('now')),
('Hippie_pants_0true_03', 'Hippie_pants_0true_03', true, date('now')),
('Hippie_pants_0true_04', 'Hippie_pants_0true_04', true, date('now')),
('Hippie_pants_02_0true', 'Hippie_pants_02_0true', true, date('now')),
('Hippie_Pants_02_02', 'Hippie_Pants_02_02', true, date('now')),
('Hippie_Pants_02_03', 'Hippie_Pants_02_03', true, date('now')),
('Hippie_Shirt_02', 'Hippie_Shirt_02', true, date('now')),
('Holster_Leg_Test', 'Holster_Leg_Test', true, date('now')),
('Hoodie', 'Hoodie', true, date('now')),
('Hoodie_02', 'Hoodie_02', true, date('now')),
('Hoodie_03', 'Hoodie_03', true, date('now')),
('Hoodie_04', 'Hoodie_04', true, date('now')),
('Hoodie_05', 'Hoodie_05', true, date('now')),
('Horror_Goalie_Mask', 'Horror_Goalie_Mask', true, date('now')),
('Improvised_Pouch', 'Improvised_Pouch', true, date('now')),
('Improvised_Wooden_Box', 'Improvised_Wooden_Box', true, date('now')),
('Jeans_0true_02', 'Jeans_0true_02', true, date('now')),
('Jeans_0true_03', 'Jeans_0true_03', true, date('now')),
('Jeans_02_0true', 'Jeans_02_0true', true, date('now')),
('Jeans_02_02', 'Jeans_02_02', true, date('now')),
('Jeans_02_03', 'Jeans_02_03', true, date('now')),
('Jeans_02_04', 'Jeans_02_04', true, date('now')),
('Jeans_02_05', 'Jeans_02_05', true, date('now')),
('Jeans_02_06', 'Jeans_02_06', true, date('now')),
('Jeans_02_07', 'Jeans_02_07', true, date('now')),
('Jeans_02_08', 'Jeans_02_08', true, date('now')),
('Jeans_02_09', 'Jeans_02_09', true, date('now')),
('Jeans_Jacket', 'Jeans_Jacket', true, date('now')),
('Jersey_02', 'Jersey_02', true, date('now')),
('Jersey_04', 'Jersey_04', true, date('now')),
('Jersey_05', 'Jersey_05', true, date('now')),
('Jersey_06', 'Jersey_06', true, date('now')),
('Jersey_07', 'Jersey_07', true, date('now')),
('Jersey_08', 'Jersey_08', true, date('now')),
('Jersey_09', 'Jersey_09', true, date('now')),
('Jock_Jacket_02', 'Jock_Jacket_02', true, date('now')),
('Jock_Jacket_03', 'Jock_Jacket_03', true, date('now')),
('Juicebox', 'Juicebox', true, date('now')),
('Leather_Jacket', 'Leather_Jacket', true, date('now')),
('Leather_Pants', 'Leather_Pants', true, date('now')),
('Long_Johns', 'Long_Johns', true, date('now')),
('MAtrue_Spitfire_0true', 'MAtrue_Spitfire_0true', true, date('now')),
('MAtrue_Spitfire_02', 'MAtrue_Spitfire_02', true, date('now')),
('MAtrue_Spitfire_03', 'MAtrue_Spitfire_03', true, date('now')),
('MAtrue_Spitfire_04', 'MAtrue_Spitfire_04', true, date('now')),
('Marine_Cap_02', 'Marine_Cap_02', true, date('now')),
('Marine_Cap_03', 'Marine_Cap_03', true, date('now')),
('Marine_Cap_04', 'Marine_Cap_04', true, date('now')),
('Marine_Cap_05', 'Marine_Cap_05', true, date('now')),
('Marine_Cap_06', 'Marine_Cap_06', true, date('now')),
('Marine_Cap_07', 'Marine_Cap_07', true, date('now')),
('Marine_Cap_08', 'Marine_Cap_08', true, date('now')),
('Military_Cap_02', 'Military_Cap_02', true, date('now')),
('Military_Cap_03', 'Military_Cap_03', true, date('now')),
('Military_Cap_04', 'Military_Cap_04', true, date('now')),
('Military_Cap_05', 'Military_Cap_05', true, date('now')),
('Military_Cap_06', 'Military_Cap_06', true, date('now')),
('Military_Helmet_02', 'Military_Helmet_02', true, date('now')),
('Military_Helmet_03', 'Military_Helmet_03', true, date('now')),
('Military_Helmet_04', 'Military_Helmet_04', true, date('now')),
('Military_Helmet_05', 'Military_Helmet_05', true, date('now')),
('Military_Helmet_06', 'Military_Helmet_06', true, date('now')),
('Military_Helmet_07', 'Military_Helmet_07', true, date('now')),
('Military_Helmet_08', 'Military_Helmet_08', true, date('now')),
('Military_Helmet_09', 'Military_Helmet_09', true, date('now')),
('Military_Pack_Big_Blue', 'Military_Pack_Big_Blue', true, date('now')),
('Military_Shirt_02', 'Military_Shirt_02', true, date('now')),
('Military_Shirt_03', 'Military_Shirt_03', true, date('now')),
('Military_Shirt_04', 'Military_Shirt_04', true, date('now')),
('Military_Shirt_05', 'Military_Shirt_05', true, date('now')),
('Military_Shirt_07', 'Military_Shirt_07', true, date('now')),
('Military_Shirt_08', 'Military_Shirt_08', true, date('now')),
('MilitaryPants_03', 'MilitaryPants_03', true, date('now')),
('MilitaryPants_04', 'MilitaryPants_04', true, date('now')),
('MilitaryPants_05', 'MilitaryPants_05', true, date('now')),
('MilitaryPants_06', 'MilitaryPants_06', true, date('now')),
('MilitaryPants_07', 'MilitaryPants_07', true, date('now')),
('Moonshine', 'Moonshine', true, date('now')),
('Motorbike_Helmet', 'Motorbike_Helmet', true, date('now')),
('Muscle_T_Shirt', 'Muscle_T_Shirt', true, date('now')),
('Neoprene_Face_Mask', 'Neoprene_Face_Mask', true, date('now')),
('Ninja_Suit', 'Ninja_Suit', true, date('now')),
('Open_Finger_Gloves_02', 'Open_Finger_Gloves_02', true, date('now')),
('Open_Finger_Gloves_03', 'Open_Finger_Gloves_03', true, date('now')),
('Open_Finger_Gloves_04', 'Open_Finger_Gloves_04', true, date('now')),
('Painkillers_02', 'Painkillers_02', true, date('now')),
('PainKillers_03', 'PainKillers_03', true, date('now')),
('Pants_Poop_0true', 'Pants_Poop_0true', true, date('now')),
('Pants_Poop_02', 'Pants_Poop_02', true, date('now')),
('Pants_Poop_03', 'Pants_Poop_03', true, date('now')),
('Pants_Poop_04', 'Pants_Poop_04', true, date('now')),
('Pants_Poop_05', 'Pants_Poop_05', true, date('now')),
('Pants_Poop_06', 'Pants_Poop_06', true, date('now')),
('Pants_Poop_07', 'Pants_Poop_07', true, date('now')),
('Parsnips_roots', 'Parsnips_roots', true, date('now')),
('Police_Belt', 'Police_Belt', true, date('now')),
('Police_Cap_0true', 'Police_Cap_0true', true, date('now')),
('Police_Complet_Test', 'Police_Complet_Test', true, date('now')),
('Police_Tact_Duty_Vest', 'Police_Tact_Duty_Vest', true, date('now')),
('Police_Zombie_02_Test', 'Police_Zombie_02_Test', true, date('now')),
('Police_Zombie_Boots', 'Police_Zombie_Boots', true, date('now')),
('Police_Zombie_Glove', 'Police_Zombie_Glove', true, date('now')),
('Police_Zombie_Pants', 'Police_Zombie_Pants', true, date('now')),
('PotassiumIodide_Pils_02', 'PotassiumIodide_Pils_02', true, date('now')),
('PotassiumIodide_Pils_03', 'PotassiumIodide_Pils_03', true, date('now')),
('Puffer_Jacket', 'Puffer_Jacket', true, date('now')),
('QuinineSulphate_Pils_02', 'QuinineSulphate_Pils_02', true, date('now')),
('QuinineSulphate_Pils_03', 'QuinineSulphate_Pils_03', true, date('now')),
('Rare_0true', 'Rare_0true', true, date('now')),
('Rare_02', 'Rare_02', true, date('now')),
('Rare_03', 'Rare_03', true, date('now')),
('Redneck_Rat', 'Redneck_Rat', true, date('now')),
('Reflective_Arm_Bands', 'Reflective_Arm_Bands', true, date('now')),
('Ribwort_plantain', 'Ribwort_plantain', true, date('now')),
('Round_Sunglasses', 'Round_Sunglasses', true, date('now')),
('Rucksack', 'Rucksack', true, date('now')),
('Safety_Helmet', 'Safety_Helmet', true, date('now')),
('Santa', 'Santa', true, date('now')),
('Shepherds_Purse', 'Shepherds_Purse', true, date('now')),
('Shirt_02', 'Shirt_02', true, date('now')),
('Shirt_03', 'Shirt_03', true, date('now')),
('Shorts_Pants_02', 'Shorts_Pants_02', true, date('now')),
('Shorts_Pants_03', 'Shorts_Pants_03', true, date('now')),
('Shorts_Pants_04', 'Shorts_Pants_04', true, date('now')),
('Shorts_Pants_05', 'Shorts_Pants_05', true, date('now')),
('Shorts_Pants_06', 'Shorts_Pants_06', true, date('now')),
('Shorts_Pants_07', 'Shorts_Pants_07', true, date('now')),
('Shorts_Pants_08', 'Shorts_Pants_08', true, date('now')),
('Shorts_Pants_09', 'Shorts_Pants_09', true, date('now')),
('Shorts_Pants_true0', 'Shorts_Pants_true0', true, date('now')),
('Skateboard_Helmet', 'Skateboard_Helmet', true, date('now')),
('Ski_Coat', 'Ski_Coat', true, date('now')),
('Small_Leather_Backpack_02', 'Small_Leather_Backpack_02', true, date('now')),
('Small_Leather_Backpack_03', 'Small_Leather_Backpack_03', true, date('now')),
('Sneakers_02_02', 'Sneakers_02_02', true, date('now')),
('Sneakers_02_03', 'Sneakers_02_03', true, date('now')),
('Sneakers_02_04', 'Sneakers_02_04', true, date('now')),
('Socks', 'Socks', true, date('now')),
('Spartan_Helmet', 'Spartan_Helmet', true, date('now')),
('SpecOps_Helmet', 'SpecOps_Helmet', true, date('now')),
('Sport_Backpack', 'Sport_Backpack', true, date('now')),
('Sport_Sunglasses', 'Sport_Sunglasses', true, date('now')),
('Sweater_02', 'Sweater_02', true, date('now')),
('Sweater_03', 'Sweater_03', true, date('now')),
('Sweater_04', 'Sweater_04', true, date('now')),
('Sweater_05', 'Sweater_05', true, date('now')),
('Swimsuit_cap', 'Swimsuit_cap', true, date('now')),
('T_Shirt', 'T_Shirt', true, date('now')),
('Tactical_Gloves_02', 'Tactical_Gloves_02', true, date('now')),
('Tactical_Gloves_03', 'Tactical_Gloves_03', true, date('now')),
('Tactical_Gloves_04', 'Tactical_Gloves_04', true, date('now')),
('Tactical_Gloves_05', 'Tactical_Gloves_05', true, date('now')),
('Tactical_Gloves_06', 'Tactical_Gloves_06', true, date('now')),
('Tactical_Gloves_07', 'Tactical_Gloves_07', true, date('now')),
('Tactical_Gloves_08', 'Tactical_Gloves_08', true, date('now')),
('Tactical_Gloves_09', 'Tactical_Gloves_09', true, date('now')),
('Tactical_Jacket_02', 'Tactical_Jacket_02', true, date('now')),
('Tactical_Jacket_03', 'Tactical_Jacket_03', true, date('now')),
('Tactical_Jacket_04', 'Tactical_Jacket_04', true, date('now')),
('Tactical_Jacket_05', 'Tactical_Jacket_05', true, date('now')),
('Tactical_Jacket_06', 'Tactical_Jacket_06', true, date('now')),
('Tactical_Jacket_07', 'Tactical_Jacket_07', true, date('now')),
('Tactical_Jacket_08', 'Tactical_Jacket_08', true, date('now')),
('Tactical_Jacket_09', 'Tactical_Jacket_09', true, date('now')),
('Tactical_Military_Pants', 'Tactical_Military_Pants', true, date('now')),
('Tactical_Shirt', 'Tactical_Shirt', true, date('now')),
('Tactical_Sunglasses', 'Tactical_Sunglasses', true, date('now')),
('Tactical_Sweater_02', 'Tactical_Sweater_02', true, date('now')),
('Tactical_Sweater_03', 'Tactical_Sweater_03', true, date('now')),
('Tactical_Sweater_04', 'Tactical_Sweater_04', true, date('now')),
('Tactical_Sweater_05', 'Tactical_Sweater_05', true, date('now')),
('Tactical_Sweater_06', 'Tactical_Sweater_06', true, date('now')),
('Tactical_Sweater_07', 'Tactical_Sweater_07', true, date('now')),
('Tactical_Sweater_08', 'Tactical_Sweater_08', true, date('now')),
('Test_Bandage', 'Test_Bandage', true, date('now')),
('TEST_Morph_Backpack', 'TEST_Morph_Backpack', true, date('now')),
('TestBackpack', 'TestBackpack', true, date('now')),
('Tracksuit_Pants_0true_02', 'Tracksuit_Pants_0true_02', true, date('now')),
('Tracksuit_Pants_0true_03', 'Tracksuit_Pants_0true_03', true, date('now')),
('Tracksuit_Pants_0true_04', 'Tracksuit_Pants_0true_04', true, date('now')),
('Tracksuit_Pants_0true_05', 'Tracksuit_Pants_0true_05', true, date('now')),
('Tracksuit_Pants_02_0true', 'Tracksuit_Pants_02_0true', true, date('now')),
('Tracksuit_Pants_02_02', 'Tracksuit_Pants_02_02', true, date('now')),
('Tracksuit_Pants_02_03', 'Tracksuit_Pants_02_03', true, date('now')),
('Tracksuit_Pants_02_04', 'Tracksuit_Pants_02_04', true, date('now')),
('Tracksuit_Pants_02_05', 'Tracksuit_Pants_02_05', true, date('now')),
('Tracksuit_Top_0true_02', 'Tracksuit_Top_0true_02', true, date('now')),
('Tracksuit_Top_0true_03', 'Tracksuit_Top_0true_03', true, date('now')),
('Tracksuit_Top_0true_04', 'Tracksuit_Top_0true_04', true, date('now')),
('Tracksuit_Top_0true_05', 'Tracksuit_Top_0true_05', true, date('now')),
('Tracksuit_Top_02_0true', 'Tracksuit_Top_02_0true', true, date('now')),
('Tracksuit_Top_02_02', 'Tracksuit_Top_02_02', true, date('now')),
('Tracksuit_Top_02_03', 'Tracksuit_Top_02_03', true, date('now')),
('Tracksuit_Top_02_04', 'Tracksuit_Top_02_04', true, date('now')),
('Tracksuit_Top_02_05', 'Tracksuit_Top_02_05', true, date('now')),
('Travel_Sunglasses', 'Travel_Sunglasses', true, date('now')),
('Trucker_Jacket_02', 'Trucker_Jacket_02', true, date('now')),
('Trucker_Jacket_03', 'Trucker_Jacket_03', true, date('now')),
('Trucker_Jacket_04', 'Trucker_Jacket_04', true, date('now')),
('Uncommon_0true', 'Uncommon_0true', true, date('now')),
('Uncommon_02', 'Uncommon_02', true, date('now')),
('Uncommon_03', 'Uncommon_03', true, date('now')),
('Underwear', 'Underwear', true, date('now')),
('V_mask', 'V_mask', true, date('now')),
('VeryRare_0true', 'VeryRare_0true', true, date('now')),
('VeryRare_02', 'VeryRare_02', true, date('now')),
('VeryRare_03', 'VeryRare_03', true, date('now')),
('Vest_0true_02', 'Vest_0true_02', true, date('now')),
('Vest_0true_03', 'Vest_0true_03', true, date('now')),
('Vest_0true_04', 'Vest_0true_04', true, date('now')),
('Vest_0true_05', 'Vest_0true_05', true, date('now')),
('VIP_Stab_Proof_Vest', 'VIP_Stab_Proof_Vest', true, date('now')),
('Waist_Bag_Large', 'Waist_Bag_Large', true, date('now')),
('Waist_Bag_Small_02', 'Waist_Bag_Small_02', true, date('now')),
('Waist_Bag_Small_03', 'Waist_Bag_Small_03', true, date('now')),
('Wellingtons', 'Wellingtons', true, date('now')),
('White_Mustard', 'White_Mustard', true, date('now')),
('WifeBeaterShirt', 'WifeBeaterShirt', true, date('now')),
('Winter_Beanie', 'Winter_Beanie', true, date('now')),
('Winter_Boots', 'Winter_Boots', true, date('now')),
('Winter_Gloves', 'Winter_Gloves', true, date('now')),
('Winter_Hat', 'Winter_Hat', true, date('now')),
('Woodcutter_Shirt_02', 'Woodcutter_Shirt_02', true, date('now')),
('Woodcutter_Shirt_03', 'Woodcutter_Shirt_03', true, date('now')),
('Work_Jacket_02', 'Work_Jacket_02', true, date('now')),
('Work_Jacket_03', 'Work_Jacket_03', true, date('now')),
('Working_Boots', 'Working_Boots', true, date('now')),
('Working_Gloves', 'Working_Gloves', true, date('now')),
('Working_pants_02', 'Working_pants_02', true, date('now')),
('Working_pants_03', 'Working_pants_03', true, date('now')),
('WorkPants_0true', 'WorkPants_0true', true, date('now')),
('WorkPants_02', 'WorkPants_02', true, date('now')),
('WorkPants_03', 'WorkPants_03', true, date('now')),
('WW2_US_Helmet', 'WW2_US_Helmet', true, date('now')),
('Zombie_Boonie_Hat_true4', 'Zombie_Boonie_Hat_true4', true, date('now')),
('Zombie_Boonie_Hat_true5', 'Zombie_Boonie_Hat_true5', true, date('now')),
('Zombie_Jeans_02_0true', 'Zombie_Jeans_02_0true', true, date('now')),
('Zombie_Jeans_02_03', 'Zombie_Jeans_02_03', true, date('now')),
('Zombie_Jeans_02_06', 'Zombie_Jeans_02_06', true, date('now')),
('Zombie_Jeans_02_08', 'Zombie_Jeans_02_08', true, date('now')),
('Zombie_Tracksuit_Top_0true_03', 'Zombie_Tracksuit_Top_0true_03', true, date('now')),
('Zombie_Tracksuit_Top_02_0true', 'Zombie_Tracksuit_Top_02_0true', true, date('now')),
('Zombie_Vest_0true_02', 'Zombie_Vest_0true_02', true, date('now')),
('Zombie_Working_pants_02', 'Zombie_Working_pants_02', true, date('now')),
('Zombie_Working_pants_03', 'Zombie_Working_pants_03', true, date('now')),
('Zombie_WorkPants', 'Zombie_WorkPants', true, date('now'));